lib/yunohost/app.py

This commit add app settings to redirect a page with ssowat.
Exemple of use:
>  sudo yunohost app setting $app redirected_urls -v "{'/ynhpanel.js':'$path/menu.js'}"
This allow to redirect the ynh_panel.js, like that I can display a menu on all pages in place of the square yunohost panel.

[enh] Add app settings to redirect request

---

lib/yunohost/domain.py

The current default configuration of dnsmasq allows anyone to do DNS recursive requests from the internet. Each server with this configuration is a candidate for participating to a DNS DDoS Amplification Attack.
Setting the resolv-file parameter is the only way I found to disable the forwarding to upstream servers. It could be added directly into dnsmasq.conf, instead of in each zone file as in my commit.

Disable DNS forwarding

---

lib/yunohost/app.py

Fix this problem during an installation:
yunohost app install /vagrant/apps/owncloud_ynh/
Extracting...
Done.
File "/usr/bin/yunohost", line 160, in <module>
print_json=PRINT_JSON, use_cache=USE_CACHE)
File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 117, in cli
moulinette.run(args, print_json)
File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 202, in run
ret = self.actionsmap.process(args, timeout=5)
File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 462, in process
File "/usr/lib/moulinette/yunohost/app.py", line 436, in app_install
if file[:1] != '.':
UnboundLocalError: local variable 'file' referenced before assignment

[fix] 2nd installation of apps with a hooks directory

---

debian/control
lib/yunohost/dyndns.py

Following the discussion on #89 
I based my work ontop of [kload commit](https://github.com/YunoHost/moulinette-yunohost/commit/1ceb1259bc5f65cc94ce7447aa71117f9ad33dd2#diff-29d74bbf0c8633566b2ba97ef48d4b33R135) which includes some parts of #89.

Get ipv6 locally (instead of from ip6.yunohost.org)

---

data/templates/mysql/my.cnf

By default, mysql creates its mysql database in MyISAN mode which self corrupt itself way too frequently on the internet cube configuration. InnoDB seems fine in comparison. Also MyISAN is bullcrap.

Avoid self corruption of mysql on power failure

---

data/hooks/conf_regen/15-nginx
data/templates/nginx/global.conf
data/templates/nginx/server.conf.sed
data/templates/nginx/yunohost_admin.conf

This hides the Nginx version in error pages to make it harder for script kiddies to target vulnerabilities specific to a version.
Before:
```html
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```
After:
```html
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
I also did some whitespace cleanup.
This is my first PR to get to know the _yunohost_ codebase. I used https://yunohost.org/#/docker to test my changes and it worked relatively well but I'm wondering if you have any kind of automated testsuite or build system? Thank you for this great project!

Don't emit Nginx version

---

bin/yunopaste

Thanks to @opi, we now have our Haste server back. As also suggested by @opi, we could easily provide a script for users to paste commands output - and especially YunoHost ones - to it. This script attempts to do that.

[enh] Add a yunopaste script to paste data to YunoHost Haste server

---

data/hooks/conf_regen/34-mysql

`service mysql status` seems to fail on some systems, even if the service is running. This makes use of `ps` to check if MySQL is running instead, which is more reliable.

[fix] Use ps to check if MySQL is running in conf_regen hook (fix #232)

---

data/helpers.d/filesystem
data/hooks/backup/05-conf_ldap
data/hooks/backup/08-conf_ssh
data/hooks/backup/11-conf_ynh_mysql
data/hooks/backup/14-conf_ssowat
data/hooks/backup/17-data_home
data/hooks/backup/20-conf_ynh_firewall
data/hooks/backup/21-conf_ynh_certs
data/hooks/backup/23-data_mail
data/hooks/backup/26-conf_xmpp
data/hooks/backup/29-conf_nginx
data/hooks/backup/32-conf_cron
data/hooks/backup/40-conf_ynh_currenthost
src/yunohost/hook.py

It adds `set -eu` to each backup hook to ensure that it will fail on command error and/or unset variable. The goal is to prevent [this situation](https://forum.yunohost.org/t/yunohost-in-read-only-mode/) where a system hook is considered as successful even if it failed. It will by the way also prevent to let the user think that he/she has a system backup - even if it's an empty one!
It also makes use of `ynh_backup` for each file/directory backup.

Harden backup hooks to handle errors

---

data/actionsmap/yunohost.yml
src/yunohost/monitor.py

Since monitoring statistics was not finished - and by the way not usable, it inverts the behavior of monitor_enable to disable it by default. See [#395](https://dev.yunohost.org/issues/395) for more details.

[ref] Invert no-stats option to with-stats in monitor_enable

---

data/hooks/conf_regen/25-dovecot

This is needed by Dovecot - and especially by Sieve. If the permission is incorrectly set - as it was on my server: `drwxrwsr-x root:man`, *managesieve* will not be able to create any folder inside. Here is the error when trying to manage Sieve filters with Roundcube:
dovecot[1150]: managesieve(camille): Error: sieve-storage: mkdir_parents_chgrp(/var/mail/sievescript/camille/scripts//tmp) failed: Permission denied (euid=500(vmail) egid=8(mail) missing +w perm: /var/mail, we're not in group 12(man), dir owned by 0:12 mode=0775)
dovecot[1150]: managesieve(camille): Fatal: Failed to open Sieve storage.

[fix] Set /var/mail folder owners and permissions

---

src/yunohost/app.py

We've chosen to use boolean everywhere for multi_instance apps, but some app still use string, we need to ensure that we have boolean value everywhere in the mean time (and we'll remove that code in the future).
This is done because for now yunohost-admin expect string and that breaks app that uses a boolean (they aren't detected as multi instance apps by yunohost-admin but ones that uses strings are).
I'm going to do a pr for yunohost-admin too.

[fix] ensure that multi_instance key value is always a boolean

---

src/yunohost/hook.py

Move from displaying
```
"ERROR File does not exist"
```
To:
```
"ERROR File does not exist: '/path/to/file'"
```
Requires https://github.com/YunoHost/moulinette/pull/123 (and thus a release of both moulinette and yunohost)

[enh] display file path on file_not_exist error

---

src/yunohost/backup.py

if /home/yunohost.backup/archives is on a different device (for instance, a NAS), backups fail with the message:
...
File "/usr/lib/moulinette/yunohost/backup.py", line 303, in backup_create
'{:s}/{:s}.info.json'.format(archives_path, name))
OSError: [Errno 18] Invalid cross-device link
A simple solution is to use shutil.move because, as stated in the documentation, "If the destination is on the current filesystem, then os.rename() is used. Otherwise, src is copied (using shutil.copy2()) to dst and then removed.", which is the needed behavior.
This PR has been successfully tested.

Fix backup when /home/yunohost.backup/archives is on a different device

---

src/yunohost/app.py

Fix this issue https://dev.yunohost.org/issues/593
It fix an unlisted other bug. Before the fix it was possible to install an app on /a/b and next install an other app on /a .

[fix] Can't restore app on a root domain

---

src/yunohost/app.py

I tried to use git submodule for assure the iso sources but yunohost doesn't support it with a non github url because the git clone is not recursive.
Since git 2.9 there is an option to force submodule to just download the last commit --shallow-submodules https://git-scm.com/docs/git-clone , but with the current yunohost (debian jessie) git is in version 2.1 so we should wait before adding this option.
This Merge Request is linked to the ticket https://dev.yunohost.org/issues/533

[fix] Support git ynh app with submodules #533

---

data/helpers.d/filesystem

Le helper `ynh_mkdir_tmp` est inutile. Il existe la commande `mktemp -d` pour créer des dossiers temporaires.

Remove helper ynh_mkdir_tmp

---

locales/en.json
src/yunohost/tools.py

Follow-up of #172 after some investigation with @Psycojoker (thanks to him ! Had no idea about that nslcd/nscd thing 😛). Not entirely sure this is the real cause of the issue people reported, but there's a good 95% that it is.
Funnily enough, before this fix, if you attempted to log as admin (or `su admin`) before launching post-install, post-install would fail - because the cache of nscd remembers that user admin doesn't exists for the next minute at least. Maybe something like `su admin` happens somewhere in the procedure for raspberry install and others ? Or maybe the cache config is different ?
@Psycojoker suggested on the chat that if this doesn't solves all issues, we could check that nscd and nslcd (and slapd?) are correctly running.

[fix] Fix ldap caching on postinstall, which might cause 'Unknown admin user'

---

data/actionsmap/yunohost.yml
locales/en.json
src/yunohost/domain.py
src/yunohost/tools.py

Attempt to fix [issue 639](https://dev.yunohost.org/issues/639).
I refactorized `tools_maindomain()` in the same time, which had a lot of weird stuff (old_domain option not actually used ? dyndns option not documented, only used in postinstall ? duplicated and outdated code with domain_add ? automatically create the new main domain if it does not exist ?)
I still need to check that this doesn't break postinstall.

[fix] Disable removal of main domain and clarify tools_maindomain

---

debian/control

See https://dev.yunohost.org/issues/656
nscd is called during user_create and user_delete, but this package is only in Recommends for libnss-ldapd.

[fix] Add missing dependency to nscd package #656

---

data/helpers.d/string

With bracket we get string like "3KFEc[xm4[udnZ6pDJ8LvP0n"
Without "El0nMO3thacDwrjeRzgKnb30"

[fix] Bracket in passwd from ynh_string_random

---

debian/control

Increase entropy on virtual servers. Speed up key generation by openssl and dnssec
See https://github.com/YunoHost/yunohost/pull/201 & https://bugs.launchpad.net/ubuntu/+source/bind9/+bug/963368

[enh] Add haveged as Debian dependency

---

data/hooks/conf_regen/06-slapd

Hello,
As reported [here](https://dev.yunohost.org/issues/447) or
[here](https://dev.yunohost.org/issues/463), YunoHost post install fails on
slow hardware/vps because slapd is to slow to restart itself after its
regen-conf.
This patch is an attempt to fix this but I don't have a good testing
environment (my vagrant is too fast for that). Maybe testing that it's possible
to run something using the admin user could be a better test but I don't see
how to do it easily.
A workarround would be to use my patch to runs this kind of operation using
root instead of admin but this is a workaround, not a real fix (and this bug
could still generate other problems).
Cheers,

Attemp to fix broken installation on slow hardware / VPS

---

debian/control

[#662](https://dev.yunohost.org/issues/662): missing `python-openssl` dependency for Let's Encrypt integration.

[fix] Missing 'python-openssl' dependency for Let's Encrypt integration.

---

data/hooks/conf_regen/25-dovecot
data/templates/dovecot/dovecot.conf
data/templates/dovecot/post-ext.conf
data/templates/dovecot/pre-ext.conf

This set of commits allow anyone (apps typically) to extend dovecot configuration.
The intendend use is to enable specific plugins not included in the base yunohost conf.
One use case experiment is : https://github.com/YunoHost-Apps/ftssolr_ynh to enable Solr based Full Text Search. (which I currently run successfully in production on my ynh box)

[enh] Dovecot extensible configuration

---

locales/en.json
src/yunohost/user.py

See https://dev.yunohost.org/issues/640
To solve it there is a try except and a warning display to the user about dovecot status.
There are small fixes in more: it removes a bad eval and the way to parse `doveadm` result is more reliable (the percentage was sometimes the number of message).
Optionaly: I suggest a linked PR on yunohost-admin with https://github.com/YunoHost/yunohost-admin/pull/137 .
Here are some examples of the new api
**Classic case** 
```
root@yunohost:/vagrant# yunohost user info test
firstname: Jean
fullname: Jean Dupont
lastname: Dupont
mail: test@testle4.nohost.me
mailbox-quota: 
limit: 500M
use: 5M (1%)
username: test
```
**No quota case : the percentage in use is not displayed**
```
root@yunohost:/vagrant# yunohost user info test
firstname: Jean
fullname: Jean …
```

[fix] Can't get mailbox used space if dovecot is down

---

locales/en.json
src/yunohost/app.py

Rework of https://github.com/YunoHost/yunohost/issues/210.
----
Fix [#218](https://dev.yunohost.org/issues/218).
List available domains when installing an app by CLI, and set main domain as the default value.
Features:
- main domain is set as default value
- all domain names are displayed
```bash
yunohost app install my_webapp
Available domains:
- ynh.local
- duniter.ynh.local
Choose a domain for your Webapp (default: ynh.local):
```

[enh] List available domains when installing an app by CLI.

---

README.md

I choosed to add this badge [among the others](https://translate.yunohost.org/widgets/yunohost/?lang=).
If you are agreed with this PR, I will push directly to add badges for `yunohost-admin`, `moulinette` and `ssowat` repositories.

[enh] readme: add translation badge status.

---

src/yunohost/dyndns.py

See https://bugs.launchpad.net/ubuntu/+source/bind9/+bug/963368
Using /dev/urandom is not a perfect solution, as it is only a pseudo random generator. Do we care here ? (serious question)
Another solution is to had 'haveged' Debian package as dependency, which could be a great improvment for entropy related stuff. But users have to `dist-upgrade` their system
( Note that I encounter this bug only on a ARM Scaleway server )

[fix] Improve dnssec key generation on low entropy devices

---

locales/en.json
src/yunohost/backup.py

This fixes https://dev.yunohost.org/issues/618
After fixing the reported bug, I realized that when using -o to set a custom directory, code didn't keep track of the path to the backup. I fixed it by adding a symlink to the archive + an exception handling later in case the link is broken.

[fix] Correctly handle custom backup directory

---

src/yunohost/app.py

Hello,
It as been observed at least twice by 2 different people that fetchlist could indefinitely idle because of weird networking issues, due to the locking mecanism of moulette this can freeze YunoHost entirely which sound critical to me.
For reference here is wget man section regarding timeout:
```
-T seconds
--timeout=seconds
Set the network timeout to seconds seconds.  This is equivalent to specifying --dns-timeout, --connect-timeout, and --read-timeout, all at the same time.
When interacting with the network, Wget can check for timeout and abort the operation if it takes too long.  This prevents anomalies like hanging reads and
infinite connects.  The only timeout enabled by default is a 900-second read timeout.  Setting a timeout to 0 disables it altogether.  Unless you know what …
```

[fix] add timeout to fetchlist's wget

---

data/helpers.d/mysql
debian/changelog

In my nginx_error.log, the authentication errors are "helpers.lua", not "access.lua".

[fix] Wrong fail2ban regex for yunohost

---

locales/en.json
src/yunohost/certificate.py

This fixes https://dev.yunohost.org/issues/670

[fix] Check ACME challenge conf exists in nginx when renewing a certificate

---

src/yunohost/certificate.py

Attempt to address https://dev.yunohost.org/issues/695, though I don't quite understand so far why the `shutil.move()` would not keep the permissions of the original file :/

[fix] Attempt to fix missing perm for metronome in weird cases

---

src/yunohost/tools.py

This morning I have got 2 issues on unstable branches when I have tried to postinstall.
One was due to a non built commit on moulinette (it should be done this night).
The 2 others are fixed by this PR.
> yunohost tools postinstall test.local --verbose --debug
fails due to the missing option --ignore-dyndns. But it shouldn't fail because it's a short domain so it's not a dyndns one...
Note: I am not sure about the good behaviour to have with 3 parts domain ( eg: toto.example.org ). We don't support for the moment dyndns on it but in future it could be the case...

[fix] Fix 693 invalid domain dyndns postinstall

---

data/hooks/conf_regen/28-rmilter
data/hooks/conf_regen/31-rspamd
data/templates/postfix/main.cf
data/templates/rmilter/rmilter.conf
data/templates/rmilter/rmilter.socket

https://dev.yunohost.org/issues/645
cf https://rspamd.com/announce/2016/08/01/rspamd-1.3.1.html
>Systemd activation has been removed from Rspamd and Rmilter
>
>Over the recent years, we have experienced constant issues reported by users about Systemd socket activation. This feature seems to be completely broken in systems with both IPv4/IPv6 enabled. Moreover, it seems to be harmful as Rspamd setup time is quite significant whilst socket activation is mostly intended for interactive on-demand daemons. Socket activation has been added under the pressure of Debian packaging rules, though Rspamd is completely rotten in Debian official repos and we strongly discourage Debian users from using the official Debian packages. While we are still looking for a new Debian maintainer for Rspamd, I can …

[fix] new rspamd version replace rspamd.socket with rspamd.service

---

locales/en.json
src/yunohost/certificate.py

As discussed with @julienmalik and @alexAubin, I'm starting this PR so we can discuss about how we should handle timeouting requests in the cert management.

[mod] start putting timeout in certificate code

---

src/yunohost/service.py

This is intended to clean some post-installation logs when runned with `--debug`. Currently, since there's no "conffiles" entries in services.yml during post-install, we get some messages lilke :
```
45152 unable to retrieve conf hashes for glances
File "/usr/lib/moulinette/yunohost/service.py", line 640, in _get_conf_hashes
return _get_services()[service]['conffiles']
KeyError: 'conffiles'
```
This is a problem for my continous integration stuff which alwats report these errors (see post-installations logs [here](http://bicyclette.netlib.re/))

[mod] Cleaner _get_conf_hashes logs

---

data/templates/yunohost/services.yml

Changes introduced by https://github.com/YunoHost/yunohost/commit/b419c8c5641f29284befc29b059ee37db0b74a59

[fix] Rspamd & Rmilter are no more sockets

---

src/yunohost/app.py
src/yunohost/backup.py
src/yunohost/firewall.py
src/yunohost/hook.py
src/yunohost/monitor.py
src/yunohost/service.py
src/yunohost/tools.py

We wanted to do some code cleaning for this release therefor I've started doing this. My plan is to do a small series of easy to review PR that only does one thing so we can move forward without having a huge PR that no one will never read.
This one is for adopting a python convention: global variables should always be uppercase so you can directly see their nature when reading them.
I've tested the code (not all commands, but at least one per module like `domain list`) and this doesn't seems to break anything. I've also took the time to grep every variable to see if they weren't imported anywhere.
I'm labeling this as a small decision but that could be a micro one.
Next, I'll run autopep8 on app.py.

[mod] rename all global variables to uppercase

---

debian/install
sbin/yunohost-reset-ldap-password

Hello,
I'm opening this PR both to start the work and both to start the discussion.
* do we want an utility to reset ldap admin password?
* if so, how do we want to do it?
This is a common request but making it super available doesn't necessary seems like the best idea in the world.
If we do it I would recommend that we have a separate script only executable by root (which I think that you still need to be root to do all the operations).

[enh] Add a script to reset ladp admin password

---

src/yunohost/tests/conftest.py

TO BE MERGED AFTER GLOBAL SETTINGS.
After years of frustration, I've finally took the time to write tests for YunoHost \o\ /o/
I had to do an ugly hack to "enter the moulinette world". Sadly, those tests only run on a setup environment (like ynh-dev).
To launch the tests:
apt-get install python-pytest
cd /usr/lib/moulinette/yunohost
py.test tests

Add unit testing for global settings

---

data/helpers.d/print

Un hack vraiment sale pour contourner le log de YunoHost pour les commandes en conditionnel.
Autrement, la commande log une erreur dans son log et est considérée comme une commande échouée par l'intégration continue.
Le fruit d'une longue discussion stérile:
>(14:01:23) Maniack C: @Bram, tu sais comment sont gérés les sorties d'erreurs des commandes YunoHost, par rapport au log?
(14:01:44) Bram: Maniack C: il va falloir que tu détails ta question
(14:02:27) Maniack C: Les commandes ynh en cli log dans le fichier de log, mais si on redirige la sortie des commandes dans /dev/null, elles log toujours de la même manière
(14:03:11) Maniack C: On dirait qu'on a aucun contrôle sur le log des commandes
(14:04:13) Maniack C: Est-ce que l'argument --quiet change se comportement?
(14:05:00) Bram: je …

Hack dégueux pour éviter d'écrire dans le log cli

---

data/templates/dnsmasq/domain.tpl

With [dnsmasq configured as a local dns resolver](https://yunohost.org/#/dns_resolver_en).
This file which is automatically configured for domain names on `/etc/dnsmasq.d/domain.tld` are used by DNS resolver dnsmasq.
You could check that locally, the dns record is resolved with one of following commands:
```bash
host -t SRV _jabber._tcp.${domain.tld}
dig _jabber._tcp.${domain.tld} SRV
nslookup -querytype=SRV _jabber._tcp.${domain.tld}
```
In the future, if we want to use dnsmasq as an authoritative DNS server, it's better to remove [jabber._tcp SRV record which is deprecated](https://serverfault.com/questions/582106/should-i-specify-the-srv-record-jabber-tcp).

[mod] dnsmasq conf: remove deprecated XMPP DNS record line.

---

data/templates/dnsmasq/domain.tpl

With [dnsmasq configured as a local dns resolver](https://yunohost.org/#/dns_resolver_en).
This file which is automatically configured for domain names on `/etc/dnsmasq.d/domain.tld` are used by DNS resolver dnsmasq.
There is no file specified for this line, and on some case dns resolution like for metronome could not works caused by this line:
- [Forum post 1](https://forum.yunohost.org/t/xmpp-cant-connect-to-conference-yunohost-org/2142)
- [Forum post 2](https://forum.yunohost.org/t/metronome-narrive-pas-a-communiquer-avec-lexterieur/1327)

[fix] dnsmasq conf: remove 'resolv-file' line.

---

src/yunohost/tests/conftest.py

Feels dirty, but does the trick :s. Feel free to suggest a better way to do it. (I guess the proper way would be to tweak the moulinette directly)

Trigger exception if string key aint defined during unit tests

---

src/yunohost/app.py

Attempt to fix https://dev.yunohost.org/issues/773

[fix] launch ssowatconf at the end of a broken install to avoid sso bad state

---

src/yunohost/tools.py

After this change, `/etc/ssowat/conf.json` is updated every time the main domain is changed.
Fixes https://dev.yunohost.org/issues/672

[fix] Regenerate SSOwat conf during main_domain operation. #672

---

data/helpers.d/package

- `ynh_package_remove` and `ynh_package_autoremove` were just moved up.
- Small modifications on `ynh_package_install_from_equivs`. Just added some comments and used popd instead of cd.
- Added `ynh_app_dependencies` to manage easily installation of dependencies with equivs
- And `ynh_remove_app_dependencies` to remove them.

[enh] New helpers for equivs use

---

data/templates/nginx/plain/yunohost_admin.conf
data/templates/nginx/server.tpl.conf

Following this topic https://forum.yunohost.org/t/ssl-security-disable-diffie-hellman-key-exchange-per-default/2540 I'm opening this PR following his instruction for further discussion.
*Please not that I haven't tested this PR.*
This PR, if good, should be backported to stable.
*Edit by Alex:*
So right now the proposal is to follow the Modern Compat' recommendation from Mozilla (cf. [this](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility) and this [this](https://mozilla.github.io/server-side-tls/ssl-config-generator/)). 
Pros : 
- Mozilla are good guys and we can trust their recommendations ;
- With modern compat, we don't need DH params anymore (we used non-custom 1024 bit DH params so far, which was bad) ;
- We probably get A+ on SSLLabs by default ;
- Modern …

[enh] upgrade ciphers suit to more secure ones

---

src/yunohost/app.py
src/yunohost/dyndns.py
src/yunohost/monitor.py
src/yunohost/user.py

https://github.com/YunoHost/yunohost/pull/187 introduced a new helper command `_get_maindomain` that should be used whenever we need to get this information.

[enh] Use _get_maindomain helper.

---

data/hooks/conf_regen/01-yunohost
data/templates/yunohost/services.yml
src/yunohost/service.py

Hello,
This is an attempt to clean `/etc/yunohost/services.yml` from outdated services.
Right we have a series of old/not used anymore/doesn't make sens services and this confused users (can be confirmed from several feedback with this internet cube, this was a very frequent request like "is it normal that those services doesn't run?").
`services.yml` is used for 2 things: saying which services are tracked with which logs files AND keeping track of the regen-conf. This collide sometime because it happens that we handle the regen-conf of stuff that *aren't services* but they end up being listed as inactive services.
This PR attempt to do 3 things to fix that:
* don't list as a service an entry that doesn't have a `status` key, by default the "service %(service name)s" was used when no …

Clean services.yml

---

src/yunohost/app.py
src/yunohost/backup.py
src/yunohost/hook.py

Hello,
I'm opening this PR to avoid forgetting it but I'm not calling for a decision yet.
It's the implementation of "don't use admin user for installing apps because it doesn't brings anything and that forgetting sudo is the first bug ever while developping apps", also will greatly reduce broken situation du to missing admin user (well ... hide them).
We'll probably need to talk again about this choice.

Use the root user for app installation

---

data/templates/nginx/plain/yunohost_panel.conf.inc

This PR:
- brings back [this PR](https://github.com/YunoHost/yunohost-config-nginx/pull/3/files) which seems to have stayed behind when migrating from `yunohost-config-nginx`. It fixes the missing tile for Jirafeau app (and maybe others).
- adds a fix to serve `ynhpanel.*` files whatever the app ningx rules are (some apps nginx conf files block them, like duniter or nextcloud).
This work is linked to [this issue](https://dev.yunohost.org/issues/285), as well as [this PR](https://github.com/YunoHost/SSOwat/pull/71) on SSOwat.

Fix for missing YunoHost tiles

---

debian/control

See https://dev.yunohost.org/issues/760 ; It'll help discovering Yunohost boxes through `yunohost.local` domain, on local networks.

[enh] Add libnss-mdns as Debian dependency.

---

data/actionsmap/yunohost.yml
locales/en.json

Allow underscore in backup name, to allow backup with the name of multi-instance apps.
If there are no reason to avoid this character.
The error message allow this character, so there are a error in one of them.
https://github.com/YunoHost/yunohost/blob/unstable/locales/en.json#L156

Allow underscore in backup name

---

locales/en.json
src/yunohost/tools.py

Right now the post-install still displays some ugly logs such as : 
```
Generating a 2048 bit RSA private key
.+++
.......+++
writing new private key to '/usr/share/yunohost/yunohost-config/ssl/yunoCA/ca/cakey.pem'
---
Updating certificates in /etc/ssl/certs... 0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
```
which pollutes the screen. With this PR and #159 (which removes the ugly wget verbose logs), we can achieve much cleaner postinstall logs.
Edit : the purpose of this PR is not to simply remove information, it is to replace it with more meaningful one.

[enh] Cleaner postinstall logs during CA creation

---

data/actionsmap/yunohost.yml
src/yunohost/app.py
src/yunohost/tools.py

- Current `app checkport` is not very semantic : it's not specific to apps and 'check' is really vague
- Current implementation raises an error if port doesn't exists, which led to introducting #230 
- introduce a `tools portavailable` in the actionmap, which does the same thing as `app checkport` except it simply returns a dictionnary with the form `{ "available" : "Yes" }` (or No). (Even if that's json, it's pretty easy to build a bash helper around it with a grep.)
- add a deprectation warning for `app checkport`.

[enh] Adding new port availability checker

---

data/hooks/conf_regen/43-dnsmasq
data/templates/dnsmasq/plain/dnsmasq.conf
data/templates/dnsmasq/plain/etcdefault
data/templates/dnsmasq/plain/resolv.dnsmasq.conf
data/templates/nsswitch/nsswitch.conf
debian/control
src/yunohost/tools.py

Ready for review and tests (Feel free also to discuss the strategy adopted)
(Imho this is a serious bug and should be treated as a release blocker for 2.6.x)
This is an attempt to fix https://dev.yunohost.org/issues/822 and other related issues. Right now, on some setups (such as ynh-dev / vagrant), resolvconf is not present and therefore `/etc/resolv.conf` does not point to 127.0.0.1 / dnsmasq. This leads to several issues since [the main domain is now the hostname](https://github.com/YunoHost/yunohost/pull/219), such as `Warning: sudo: unable to resolve host the.main.domain`. 
As long as at least `/etc/resolv.conf` or `/etc/hosts` is not managed properly, we will also always have people who will get messages such as "Cannot resolve some.domain.tld locally" (when installing Let's Encrypt …

[fix] Properly manage resolv.conf, dns resolvers and dnsmasq

---

data/helpers.d/filesystem

A secure way to remove a file or directory.
Prevent to knew issues.
Tested with this paths:
- / -> Not removed
- /var -> Not removed
- /var/www -> Not removed
- /var/www/file -> Removed
- /opt -> Not removed
- /opt/file -> Removed
- /home/yunohost.app -> Not removed
- /home -> Not removed
- /home/ -> Not removed
- // -> Not removed
- /etc/cron.d/ -> Not removed
- /etc -> Not removed
- /etc/ -> Not removed
- /etc/X11 -> Removed
- /etc/X11/$var -> Removed (if $var is not empty)

New helper ynh_secure_remove

---

src/yunohost/tests/conftest.py

Right now it's difficult to have an equivalent to --debug when running pytest. You need to tweak the conftest.py manually.
Add a custom --yunodebug option to pytest. (Cannot use --debug because it's already a pytest option)

[enh] Add a custom --yunodebug option for pytest

---

data/helpers.d/network

Simplement un wrapper de yunohost app checkurl.
Peut-être une occasion de lui donner un autre nom plus parlant.
Il me semble justement qu'il en était question.

Nouveau helper ynh_webpath_available et ynh_webpath_register

---

src/yunohost/app.py

Before:
```bash
yunohost app checkport 8999
Warnung: 'yunohost app checkport' ist veraltet und wird bald entfernt werden
File "/usr/bin/yunohost", line 217, in <module>
timeout=opts.timeout,
File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 139, in cli
moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 358, in run
File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 484, in process
File "/usr/lib/moulinette/yunohost/app.py", line 1076, in app_checkport
if availability["available"]:
TypeError: 'bool' object has no attribute '__getitem__'
``` …

[fix] app_checkport was broken.

---

data/helpers.d/utils

Weirdly, POST arguments aren't given to the request if quotes are used...
I'm puzzled as @maniackcrudelis has certainly tested this helper.
Also @scith wasn't able to make it work, but I don't know if this can be the cause.

Fix ynh_local_curl

---

data/hooks/conf_regen/43-dnsmasq

Micro-decision
A comment line in the template line contained the string "nameserver" and therefore was showing up in generated file randomly

[fix] Unexpected comment line ending up in /etc/resolv.dnsmasq.conf

---

src/yunohost/certificate.py

See https://dev.yunohost.org/issues/673
I think this should be included in stable instead of migrating it later (though it shouldn't be a big deal anyway)
- metronome/prosody
- mumble
- matrix

[enh] Use ssl-cert group instead of metronome for certificates

---

src/yunohost/certificate.py

Follow-up of https://github.com/YunoHost/yunohost/pull/222#issuecomment-303127134, I found that there was a patch between the beginning of #222 and the current unstable where permissions were explicitly changed for the key at the end. But since the PR wasn't rebased it wasn't apparent when looking at the file in the branch.
Anyway, this fixes it.

[fix] Missing change from metronome to ssl-cert

---

src/yunohost/app.py
src/yunohost/tests/test_appslist.py

This fixes https://dev.yunohost.org/issues/929 (migration was not triggered because of the typo, but tests were fines because the typo was also in the tests)

[fix] Typo in applist migration

---

src/yunohost/tools.py

For some reason, `hostnamectl` can't be used to change hostname inside LXC's. This is troublesome for bicyclette because [the postinstall crashes because of this](http://bicyclette.netlib.re) and therefore is quite useless.
Use some [black magic](https://stackoverflow.com/questions/20010199/determining-if-a-process-runs-inside-lxc-docker) to check if we're running inside a LXC. I wrapped this in a small  `_is_inside_container()` helper

[fix] Don't attempt to change hostname in LXC

---

data/helpers.d/mysql

For restore script, do not change the password.
Keep the primary password and recreate a new database with it.

[enh] Do not change the db_pwd

---

debian/control

Archivemount depends on fuse, which cannot be installed on some specific machines likes OpenVZ containers (see https://dev.yunohost.org/issues/942). This make `apt-get install yunohost` crash because fuse can't be configured (and also the update to 2.6 / current testing).
- *[This PR]* Move archivemount as a suggested dependency. Therefore it won't be installed automatically.
- *[To be done in another PR]* In the install script, attempt to install fuse (or check fuse can be installed) and install archivemount if this works
- *[To be done later]* For the migration 2.5 -> 2.6, tell people to install archivemount manually if they want to have an optimized 'restore'. (Ideally this could be added as a migration once the migration framework is there)

[fix] Move archivemount to suggested dependency

---

src/yunohost/backup.py

As reported in https://dev.yunohost.org/issues/953, `yunohost backup restore` crashes when archivemount is not installed.
Simple quick and dirty fix is to wrap the call in a try/except.
```bash
yunohost backup create
yunohost backup list
yunohost backup restore backup_archive_name
```

[fix] "backup restore" crashes when archivemount is not installed

---

data/helpers.d/backend

Standard configuration of php-fpm.
Use local files stored in conf/, so it's still possible to use a specific config

New helpers ynh_add_fpm_config and ynh_remove_fpm_config

---

data/actionsmap/yunohost.yml
src/yunohost/backup.py

The backup refacto has been stopped at a state where all old features was ok but some new one, has been disable. It's the case for the --method feature.
This PR fix some errors on the --methods and allow you to create custom backup hooks.
You can test by folowing this tuto https://forum.yunohost.org/t/the-backup-roadmap/2643/4?u=ljf . You can also adapt it and create your own backup connector.
This PR works, (i used it) but I am not sure all bugs are fixed in this part. I think you can start to review it.

[fix] Errors in backup custom methods

---

data/helpers.d/package

Add an autoremove with purge.
Some deb packages, like transmission let a lot of shit behind itself.
In case of remove then install, transmission doesn't work anymore.

[enh] New helper autopurge

---

src/yunohost/app.py

Due to parallel development (I guess) of change-url feature and script execution by root, change_url scripts are not run as root at the moment.
Here is a fix proposal; it can be tested with [this PR](https://github.com/YunoHost/test_apps/pull/1) on the test set.

Run change_url scripts as root as a matter of homogeneity

---

src/yunohost/domain.py
src/yunohost/dyndns.py

- Ready for reviews
- We need to tweak the dynette [here](https://github.com/YunoHost/dynette/blob/master/dynette.cron.py#L12-L19) to allow all the records of the recommended DNS conf (especially the DKIM/DMARC ones) to be manipulated via the dyndns update stuff. (c.f. [corresponding PR](https://github.com/YunoHost/dynette/pull/6))
Right now, the handling of the recommended DNS configuration is messy. There are inconsistencies in yunohost between the "recommended" configuration shown via `yunohost domain dns-conf` and the one used in dyndns update and dnsmasq (c.f. https://dev.yunohost.org/issues/267). For the dydns update, no DKIM key is provided, therefore all nohost.me don't have valid DKIM emails ! (c.f. https://dev.yunohost.org/issues/848)
Also it turns out that `yunohost domain …

[fix] Refactor DNS conf management for domains

---

src/yunohost/tests/test_changeurl.py

See https://github.com/YunoHost/test_apps/pull/1 : for some reason, when running unit tests for changeurl, python-requests doesnt want to validate the request because of SSL error. Not sure what this is coming from... I think it was working before. Maybe some update in the python-requests version (I've seen some similar weird stuff on tartare where python-requests don't want to validate a requests to dev.yunohost.org because of SSL)
Disable the SSL verification for the request 😕

[fix] Don't verify SSL during changeurl tests :/

---

tests/_test_m18nkeys.py

Remembering which i18n/m18n keys are defined and their names is a pain in the ass. Also it's easy to forget about testing or defining some keys while focusing on writing actual code.
I wrote a draft of script to analyze the code to look for m18n keys which are used. This is not perfect though, as sometimes m18n calls are not simply `m18n.n("foo")`, sometimes the key is computed on the fly (using concatenation, or conditions). Also it doesn't test that the arguments like `{bar:s}` are correctly passed and with the right format (string, integer, ...). But it's a start.
Right now it returns the following : 
```
> Error ! Those keys are used in some files but not defined :
- ask_path
- backup_archive_writing_error
> Warning ! Those keys are defined but seems unused :
- …
```

[enh] Add a script to test m18n keys usage

---

src/yunohost/backup.py

Minor issue where running `yunohost backup restore <archivename>` shows the depreciation warning about `--hooks` despite it not being used
Copied what was done in `backup create`
Create a backup archive, then try to restore it with an without this patch while not using `--hooks`.

[fix] Depreciation warning in backup for --hooks was always shown

---

data/helpers.d/backend

Add a --non-append option to avoid to add the new config at the end of the existing config file.
In case of upgrade, it's a real problem because it will duplicates the same entry.
https://forum.yunohost.org/t/installation-etherpad-mypads/2890/48
[Minor decision](https://github.com/YunoHost/project-organization/blob/master/yunohost_project_organization.md#minor-decision), close on 20 of june, or 16 of june.
I've made a complete test, with or without the arguments. And with the new argument at the first and the second place.

[fix] Logrotate append

---

data/templates/postfix/main.cf

Mail can only be sent if the sender is owner of the address or have the mail alias linked to his account.
Issue: https://dev.yunohost.org/issues/891#change-3384

[enh] Check that user is legitimate to use an email adress when sending mail

---

bin/yunohost
src/yunohost/app.py
src/yunohost/backup.py
src/yunohost/certificate.py
src/yunohost/domain.py
src/yunohost/dyndns.py
src/yunohost/firewall.py
src/yunohost/hook.py
src/yunohost/monitor.py
src/yunohost/service.py
src/yunohost/settings.py
src/yunohost/tests/test_backuprestore.py
src/yunohost/tools.py
src/yunohost/user.py
src/yunohost/utils/packages.py

Matching PR for https://github.com/YunoHost/moulinette/pull/145
In addition to makes things cleaner this will also allows to uses tools like `pyflakes` or `pylint` in travis-ci for static analysis.

[mod] explicitely import previously globals magic variables

---

locales/en.json
src/yunohost/app.py

Kanhu on support@ room experienced issue with invalid manifest.json during app packaging development. Yunohost should return a proper error message insead of this kind of python trace : 
```
Downloading...
Extracting...
File "/usr/bin/yunohost", line 217, in <module>
timeout=opts.timeout,
File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 139, in cli
moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 358, in run
File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 484, in process
File "/usr/lib/moulinette/yunohost/app.py", line 660, in …
```

[fix] Properly catch Invalid manifest json with ValueError.

---

src/yunohost/backup.py

Change test to match the case the `methods` parameter is `None`.

[fix] No default backup method (redmine 968)

---

src/yunohost/dyndns.py

Right now the dyndns process can block because we miss a timeout, this is a bad because this will block the whole moulinette due to the locking mechanism and the fact that we put  dyndns-update in a cron tab.
This is a hot fix for that and it's quite important that we release this fast.
This has been tested and seems okay.

[fix] timeout on request to avoid blocking process

---

src/yunohost/backup.py
src/yunohost/tests/test_backuprestore.py

https://dev.yunohost.org/issues/988
yunohost backup info return an error if the backup has no info.json outside or inside the archive.
Note: the backup code written in october 2015 already put the info.json in the archive. I don't know why there is archive without info.json. The bug was reported with an archive of 20GB.
Return a MoulinetteError
```
$ yunohost backup create --ignore-apps --system conf_ldap -n goodbackup
$ touch afile
$ tar czf  /home/yunohost.backup/archives/badbackup.tar.gz ./afile
$ yunohost backup info badbackup
Error: Invalid backup archive
$ yunohost backup list
archives: 
- goodbackup
- badbackup
$ yunohost backup list --with-info
Warning: badbackup: Invalid backup archive
archives: 
goodbackup: 
created_at: 08/08/2017 02:41 PM
description: 
path: …
```

[fix] Backup without info.json

---

data/actionsmap/yunohost.yml
src/yunohost/tools.py
src/yunohost/user.py

This started as a "let's clean a bit user.py" until I realized that we were using md5 to store users password. In reaction to that, I went rampage and destroyed every occurrence I could find of using bad hashing algorithm and integrated auto upgrade code ON LOGIN of weakly hashed password to sha-512.
We actually managed to impressive exploit of using: MD5, SSHA and SHA1 for password hashing depending from where it's used.
This PR is **important** and security related, we should merge it soon and probably do a security release only for that.
Since password handling is spread across all YunoHost, this PR also depends on https://github.com/YunoHost/moulinette/pull/152 and https://github.com/YunoHost/SSOwat/pull/87
The information we need to transmit to our users is: you need to ask every …

[fix] Use SHA-512 for passwords in LDAP

---

locales/en.json
src/yunohost/domain.py

Users who use `yunohost domain dns-conf` sometimes think that this shows some sort of actual configuration. We should tell them explicitly that this is only the recommended configuration which should be configured in the registrar.
Related issue on redmine : https://dev.yunohost.org/issues/559
For the CLI, display a warning. For the webadmin, display a warning block (see [related PR](https://github.com/YunoHost/yunohost-admin/pull/168))

[fix] Tell user that domain dns-conf shows a recommendation only

---

src/yunohost/certificate.py

Many people report that `domain cert-install/cert-renew` often thinks that the domain is not correctly configured. After investigating some cases, it appears that we do a check that the domain is correctly resolved locally via `socket.gethostbyname` (in [here](https://github.com/YunoHost/yunohost/blob/baf0d098f5c3547076f9f8477d383c4a3a5e21cb/src/yunohost/certificate.py#L859)). At the time we wrote this, a domain in Yunohost was not necessarily resolved (because of missing DNS conf and/or because domains were not automatically in /etc/hosts). 
BUT sometimes `socket.gethostbyname` gets crazy and returns stuff like `192.168.x.y` which is neither the global ip nor 127.0.0.1. Thus we cannot assert that domain is correctly resolved locally...
Nowadays, we should not need this because, if …

[fix] Local domain resolution in cert-install/renew

---

data/actionsmap/yunohost.yml
src/yunohost/tools.py

This PR allows to do a
yunohost tools shell
And be drop into an IPython shell (if installed, else python default shell) in the moulinette context for rapid prototyping and debugging (for example to talk to ldap using the `auth` object)
This also allows
yunohost tools shell -c "command"
À la
python -c "command"
I've been using this a lot during the sha-512 thingy for rapid debugging.
This is exactly the same thing that Django's `python manage.py shell`. Once you get addicted to it, it become quite life changer.
I'm tempted to pass this as a micro decision since this is trivial and not that much worth it discussing.

Integrate a command to launch a dev shell from within moulinette context

---

src/yunohost/app.py

Hello,
This is a security micro decision, there was another place where we weren't using good random generator for passwords. This code is nearly identical to this already existing and working code https://github.com/YunoHost/yunohost/blob/c6b5284be8da39cf2da4e1036a730eb5e0515096/src/yunohost/user.py#L469 (the only difference is the 16 -> length).
This is not critical security situation but it's still quite meh.
I've tagged it as a micro decision but I did a PR for communication purpose. I'll probably merge it soon.

[fix] use cryptorandom to generate password

---

src/yunohost/tools.py

Hello,
`tools_ldapinit` is used during post install to initialized the ldap db content/schema (which is stored in some yaml in `data/`).
Problem: everything is being ugly catchall try/except which mask every errors during initialization thus making things very hard to debug when they go wrong because we have strictly no informations.
This PR logs this by showing every errors.
This PR needs more testing to see if it fits the targeted used case.

Make tools_ldapinit more verbose

---

src/yunohost/app.py

Fix https://dev.yunohost.org/issues/999
Tested using "yunohost tools shell" and works as expected.
This seems to be quite blocking for the integration of change_url into apps according to feedback.
To test using "yunohost tools shell" do something like this:
```
$ yunohost tools shell
In [1]: from yunohost.app import normalize_url_path
In [2]: normalize_url_path("/")
Out[2]: '/'
In [3]: normalize_url_path("//")
Out[3]: '/'
In [4]: normalize_url_path("/////")
Out[4]: '/'
In [5]: normalize_url_path("a")                                                                                                                                                                                 
Out[5]: '/a/'
In [6]: normalize_url_path("qsd/qsd/qsd/") …
```

'/' was resulting in '//' in change_url

---

data/helpers.d/mysql

Currently, if you make 2 successive dumps, their checksum will be different only because the dump dates are different.
So, you can't compare sql dumps.
Adding the `skip-dump-date` option will remove this date in the sql dump.
So, you can make a comparaison between 2 dumps by comparing their checksums.
You keep a date by the timestamp of the file.
Tested on my own server with the fallback app.

[enh] Remove date from sql dump

---

data/helpers.d/string

`ynh_replace_string` helper doesn't explicitely invite to use regexp. As it is based on `sed`, complex expressions can be used (including `\1`, etc.).
Enhance the comments to better relate the possibilities.
Working, only comments!

Complete ynh_replace_string helper comments to mention the possible use of regexps

---

src/yunohost/backup.py

Hello,
This fix the infamous UnicodeDecodeError that we have on backup-restore. Tested on a buggy backup, I can confirm that this is working.
This is worth a small release I think.
The problem was that we were returning unicode strings and trying to merge them against regular strings, I've fixed the problem at the source.

[fix] fix this UnicodeDecodingError on backup-restore

---

data/helpers.d/backend

Avoid to put a double slash when the path is /.  
That can induce some errors in a nginx config.

[enh] Handle root path in nginx conf

---

data/helpers.d/string

- *Some characters are interpreted by sed, especially in strong password.  
It sometimes fails the install script*
- *Escape backslash and &
Both of them are special characters for sed.*
*Medium decision*
- ~**Upgrade previous version** :~
- ~**CI succeeded** :~
- ~**CI succeeded** :~
~One public package check log is enough instead of two checks.~  
When the PR is mark as ready to merge, you have to wait for 7 days before really merge it.

[enh] Escape some special character in ynh_replace_string

---

src/yunohost/app.py

I need to display log info after app upgrade in the web admin
Do like in yunohost tools upgrade return the log if it's an api call
This PR is related to the web admin PR https://github.com/YunoHost/yunohost-admin/pull/172
You can test with by upgrading an app
To upgrade an app, you can change the update_time by editing your apps settings /etc/yunohost/apps/APP/settings.yml
Opinion needed

[enh] Return log after app upgrade with api

---

data/templates/yunohost/services.yml
src/yunohost/service.py

Following the changes in the lock system in Moulinette, it was noticed that it causes an issue for services that need to run yunohost command. Basically this kind of situation : 
```
PID     PPID
5     N/A     yunohost service foo start
6      5      '-- systemctl foo start
10     1       ./foo_start.sh
11     10      '-- yunohost app foo setting bar -v meh
```
Process 10 is detached from process 6, therefore the lock taken by 5 cannot be used by 11...
This kind of situation happens at least in three different context : 
- Firewall reload at the end of postinstall
- Firewall reload at any time from the yunohost admin
- All (?) apps of Internet Cube (e.g. [here](https://github.com/labriqueinternet/hotspot_ynh/blob/master/conf/ynh-hotspot#L263))
The proposed solution is that, everytime we …

Be able to give lock to son processes detached by systemctl

---

data/helpers.d/utils

Add only a condition to check if there's a backup script before trying to make a backup.
To prevent a failing of the upgrade script in case of missing backup script.

Fix for old apps without backup script.

---

data/helpers.d/package

- *Fake packages can't be updated, because it will be filtrate by ynh_package_is_installed
In case of upgrade of a fake package, nothing will be done. So you can't add or remove a dependency.*
- *Remove the condition with ynh_package_is_installed. Not sure why I added that before (in this [commit](https://github.com/YunoHost/yunohost/commit/5f3fcefc882c66ccb7cd60b05fef6cde3d4f81d0)).*

Fix upgrade fake package

---

data/helpers.d/backend

Actually when we use the command `ynh_use_logrotate /var/log/abcd/` the result in the logrotate conf file is `/opt/yunohost/abcd/logs//.log` witch is not what we want.

Solve ynh_use_logrotate

---

data/helpers.d/string

- *The just released commit https://github.com/YunoHost/yunohost/commit/e3a4b307f7c307820c83afce9489f8a128ffb966 break ynh_replace_string if you want to use it with a some special sed characters.*
- *For example, you can't use &, or sub-expression. If you try `ynh_replace_string "\(string\)" "\1"`, the helper will change that into `s@\\(string\\)@\\1@`, which obviously doesn't work...*
- *Remove those escapes from ynh_replace_string to restore a correct behavior.*
- *And add a new helper, `ynh_replace_password_string` which use ynh_replace_string, but escape all the potential problematics characters to allow password with special characters.*
This fix should be quickly merged in stable, because it affects most of the change_url scripts.

Fix broken ynh_replace_string

---

src/yunohost/domain.py

If copy-pasted into a registrar zone file, the provided DNS zone sample for a given domain will fail on a DNS zone Syntax error.
That is because comments lines in the ynh template start with "#".  However, comment character in DNS zone files is ";" not "#".
https://en.wikipedia.org/wiki/Zone_file
...

Fix comment lines in DNS zone example (using ";")

---

src/yunohost/app.py

When install an application (or upgrading it), the "conf" folder is not saved which makes some operations quite hard to do, in particular the `change_url` one. This is a long time requested feature from the app group.
Redmine ticket https://dev.yunohost.org/issues/871
Save it #lol
Personally tested, work as expected.

[enh] save the conf/ directory of app during installation and upgrade

---

data/templates/ssh/sshd_config

In some nat configuration, inactive ssh connexion are killed by the router.
https://sysadmincasts.com/episodes/39-cli-monday-how-to-keep-your-ssh-sessions-alive
Relative Redmine ticket: https://dev.yunohost.org/issues/1039
Add the `ClientAliveInterval 60` option to keep active all client ssh connexion.
It will avoid to get Broken Pipe or freeze in some cases.
Note: User can also define a client side config with the directive ServerAliveInterval, I have tested this one, and it works well.
Test needed

[enh] Maintain ssh client connexion

---

src/yunohost/utils/packages.py

We want to display if the installed version of YunoHost is from stable/testing/unstable on the admin internface. Solve this ticket https://dev.yunohost.org/issues/718
Provide this information.
Tested and working. Admin code needs to be adapted.

Package version stable testing unstable

---

src/yunohost/tools.py

This will provide useful information for debugging since a broken nginx configuration file will crash everything :/
yunohost tools diagnosis
Look for the "nginx" section.

[enh] add nginx -t output to diagnosis

---

src/yunohost/service.py
src/yunohost/tools.py

When updating/cleaning the commands used at postinstall to enable/start the firewall, I realized that our current way of enabling/disabling services is weird and actually doesn't work ?
Basically doing a `service_enable("yunohost-firewall")` doesn't seem to really work, since the firewall was still disabled after postinstall. 
I'm not a init expert, but our current way of doing things, which is using `update_rc.d <service> defaults|remove` is pretty weird and I'm not sure it's the right thing ? When trying to use `systemctl enable <service>`, I see that it's actually running both these commands :
```
update-rc.d <service> defaults
update-rc.d <service> enable
```
(and same thing for disable, replacing 'enable' by 'disable') ...
Apparently the current code dates back from 2014 at which …

Use systemd for all service operations (+ update postinstall firewall enable/start)

---

src/yunohost/tools.py

Source: https://dev.yunohost.org/issues/694
Backport packages can easily breaks YunoHost, having this information in the diagnosis tool could help in some situations.
Work and tested.

[enh] display backports .deb in diagnosis

---

src/yunohost/tools.py

When a disk was not available, the current code was replace the whole dictionnary with a string and the following commands failed.
As reported here https://dev.yunohost.org/issues/1023
For validation, this was the value of the various variable during his run:
```python
print disks, disk, diagnosis['system']['disks']
{'dm-1': 'not-available', u'sda2': {u'mnt_point': u'/home', u'used': '3.2GiB', u'percent': 0.7, 'avail': '435.4GiB', u'fs_type': u'ext4', u'size': '438.6GiB'}, u'sda1': {u'mnt_point': u'/', u'used': '16.0GiB', u'percent': 83.8, 'avail': '3.1GiB', u'fs_type': u'ext4', u'size': '19.1GiB'}} dm-1 {}
{'dm-1': 'not-available', u'sda2': {u'mnt_point': u'/home', u'used': '3.2GiB', u'percent': 0.7, 'avail': '435.4GiB', u'fs_type': u'ext4', u'size': '438.6GiB'}, u'sda1': {u'mnt_point': …
```

[fix] was replacing the dictionnary with a string and thus breaking everything

---

data/actionsmap/yunohost.yml
src/yunohost/app.py

You can't change the label of an application in YunoHost once it's installed if you don't know how to play with the settings and regenerating ssowatconf. This is a long time requested feature and we got yet another ticket for that https://dev.yunohost.org/issues/1045
Add a command for that and a new api entry point.
yunohost app change-label $app_id $new_label
Then open the ssowat to see that the label has been updated.

[enh] new command 'app change-label'

---

locales/en.json
src/yunohost/backup.py

Symlink /home/yunohost.backup/archives make the backup fails if they are broken, even if we use a custom backup methods...
See the error on https://dev.yunohost.org/issues/1044
I suggest to warn the users who have made this kind of symlink like inthis howto https://forum.yunohost.org/t/backup-on-an-usb-key/1811
Tested on an arm yunohost
Microdecision, but i would like the point of view of one of you (and a review of this english sentences)

[fix] Broken symlink to the archives dir

---

data/helpers.d/utils

In case of failure during the upgrade, the function ynh_restore_upgradebackup will be used. But, because '$backup_number' is defined as local in ynh_backup_before_upgrade, this variable does not exist in ynh_restore_upgradebackup.
So the app is deleted...
Define '$backup_number' as a standard variable.
Nice and kind ? :)
Or maybe not tested... :D
Add a `false` somewhere in the upgrade script.

[Fix] Fix ynh_restore_upgradebackup

---

locales/en.json
src/yunohost/app.py

A lot of app still use `yunohost app checkurl`, but the depreciation warning doesn't really tell what else to use :/
Try to incentivize packagers with a bigger and more explicit depreciation warning...
Not tested, just yolo-committed é_è
Try to install an app that uses checkurl, see if the new message correctly shows up.

Moar depreciation warning about checkurl

---

src/yunohost/certificate.py
src/yunohost/domain.py
src/yunohost/dyndns.py
src/yunohost/monitor.py
src/yunohost/tools.py
src/yunohost/utils/network.py

Currently, `get_public_ip(6)` display a dirty traceback and confusing error message for instance when running `dyndns update` with no IPv6 sat up. This repeatedly confused user when debugging some nohost.me/noho.st situations, because it appeared to them that something was broken - when in fact it's just that they did not have IPv6, which is fine.
Also we use `get_public_ip` in many places, but always have to do a `try/except` to keep 'None' (or similar value) in the exception.
Just return `None` if no ip was found. Also, move `get_public_ip` to a dedicated 'util' file instead of having it in domain.py leading to weird imports.
Not fully tested, so still kinda WIP
Check all occurrences of `get_public_ip` are still working properly.

[fix] Simplify get_public_ip

---

src/yunohost/app.py

Conf folder is now saved on YunoHost when installing, thanks to https://github.com/YunoHost/yunohost/pull/407, but it is not available when using the `change_url` script... which was the main motivation to save the conf folder 😢 .
Thanks to @Josue-T for [pointing out the exact problem](https://github.com/YunoHost/example_ynh/pull/45#issuecomment-360219642) 😉 
Here is a proposal to make the conf folder available to the `change_url` script : it is executed in a temporary folder, in which we need to copy the conf folder the same way we copy the scripts folder.
Can be tested with wallabag2 application, for which I committed [this change](https://github.com/YunoHost-Apps/wallabag2_ynh/commit/2314b9b32a78). You can see here that it looks much more maintainable now 😉

Add access to conf folder when executing change_url script

---

data/helpers.d/backend
data/helpers.d/system

PHP and php-fpm versions are upgraded from 5 to 7.0 when upgrading from jessie to stretch.
This upgrade aims at:
- ensuring a functional php-fpm configuration depending on the Debian release
- ensuring a smooth upgrade/uninstallation for apps in stretch when they had been installed on jessie
Set and store the php-fpm configuration directory AND php-fpm service name in app settings, based on Debian release name.
Use that settings when removing the app.
This PR should be merged in YunoHost 2.8 to prepare for later stretch migration.
Successfully tested on jessie and stretch sides.
Not tested on a stretch migrated from jessie yet.

Update php-fpm helpers to handle stretch/php7 and a smooth migration

---

src/yunohost/app.py

Some apps are dependent of others apps (vpnclient&hotspot, baikal&agendav, coin&openvpn ...).
There is a lot of scenario where an app could want do an action if another app is installed, removed, upgraded or change url.
Add this for hooks
I have set up some env var like recommended in this ticket : https://dev.yunohost.org/issues/818
The var are the same than var sending to the scripts/ACTION
/etc/yunohost/hooks.d
```
.
├── post_app_change_url
│   └── youpi
├── post_app_install
│   └── youpi
├── post_app_remove
│   └── youpi
└── post_app_upgrade
└── youpi
```
youpi
```
#!/bin/bash
printenv | grep YNH >> /root/yolo
```
Like that you can see in the yolo file which variable can be used
Opinion needed

Add post hooks for apps operation

---

data/helpers.d/utils

In case of usage of --verbose during upgrade, neither backup or restore will print their log.
Add --verbose to the backup and restore commands.
Tested, ready to review.
Add a `false` at the end of an upgrade script.
And add `--verbose` to your upgrade.

[enh] --verbose for backup during upgrade

---

src/yunohost/backup.py

My borg custom backup method uses the reorganize feature, it appears this feature conflict with a cron security limitation, because this feature creates hardlink on cronfile.
I have this in my /var/log/syslog
```
Jan  9 11:16:01 xxx cron[1132]: (*system*monitor) NUMBER OF HARD LINKS > 1 (/etc/cron.d/monitor)
```
I suggest to check in the reorganize function if the file begin with '/etc/cron.' before to make the hardlink. This kind of file are very small so there is no performance loss.
I have tested the fix on a yunohost with borg method, it works.
You can test by applying the remote borg tuto on the forum and with an application like nextcloud.
https://github.com/YunoHost-Apps/nextcloud_ynh/blob/testing/scripts/backup#L75

[fix] Cron issue during custom backup

---

data/hooks/conf_regen/01-yunohost
data/templates/yunohost/etckeeper.conf

c.f. https://dev.yunohost.org/issues/996
etckeeper regularly dumps a shitload of message, for instance when running `apt-get upgrade` and some new files were added to `/etc/`. Sometimes it's like hundreds of line of /etc/certificate stuff which basically nobody cares about and hide the real `apt-get` log.
Add `--quiet` to etckeeper.conf. Since it's not really a service and it's just a static file, I put that in the yunohost regen-conf hook which already handle files like the services.yml. Not sure if that's the right solution in terms of design. I guess we can also just add a 'etckeeper' hook easily if needed.
Should be working
Checkout this branch. Try to trigger the etckeeper thing, by creating a file like `/etc/foobar`, then run something like an `apt-get upgrade`.

[enh] Make etckeeper stfu

---

data/helpers.d/backend

Actually we can't use the helper `ynh_add_systemd_config` and `ynh_remove_systemd_config` with a custom service name. We have actually this problem with synapse how have two systemd service per instance.
Create an argument of these both function (as optional) wich give an argument. And create a second argument witch give the name of the service file in the conf directory because actually the service filename is hardcoded `systemd.service`.
- Checkout this branch
- Clone an app locally witch use this helper
- Run the script install and remove with --verbose
- You can try the synapse app with the testing branch (https://github.com/YunoHost-Apps/synapse_ynh/tree/testing), it use this new helper.

Add service name as arg (optionnal) in helper systemd

---

data/templates/nginx/plain/yunohost_admin.conf
data/templates/nginx/server.tpl.conf

Security problems due to unsafe header : 
- check : https://wiki.mozilla.org/Security/Guidelines/Web_Security
- Test of the header : https://observatory.mozilla.org/ ; https://securityheaders.io/ ; https://hstspreload.org
- Add preload to the HSTS header
- Add XSS protection (need CSP too)
- Add Referrer-Policy (need to be tesing for other applications) only in ADMIN conf.
- Add OCSP Stapling
- Add HPKP-pining to SSL cert.
- Add referrer to server.tpl
- Improve CSP
- Add Report-URI header with proper PHP file in .well-known/report-uri/index.php 
Need to be testing.

Fix security of nginx headers .

---

data/actionsmap/yunohost.yml
src/yunohost/ssh.py
src/yunohost/user.py

Extracted from https://github.com/YunoHost/yunohost/pull/345  to allow smoother merging since this part made consensus.
You need to avoid reading the 2 first commits since they are coming from the previous PR.

[enh] add commands to manage authorized-keys of users

---

src/yunohost/certificate.py

If an application (for instance roundcube) installed at the root of a
subdomain has the following nginx configuration:
location ~ ^/(.+/|)\. {
deny all;
}
acme-challenge matching location:
location '/.well-known/acme-challenge'
{
default_type "text/plain";
alias /tmp/acme-challenge-public/;
}
will not be used.
After acme-challenge match, prevent further matching by regular expressions.
Create a subdomain.
Install roundcube on the subdomain.
Try to generate a lets encrypt certificate.

[Fix] Stronger match for acme-challenge nginx location

---

debian/control

It seems wget is not in dependency but we use it with ynh_setup_source ... 
Add wget in the dependency.
Untested but very simple
I think it's a micro decision so I will just wait if someone want to say something and next merge

Add wget as dependency

---

data/helpers.d/nodejs

N shouldn't be used to manage directly the version of node to use. Because it doesn't allow multiple version at the same time.
Here, change $PATH to set the path in the directory of the version of node to use.
And by the way, get rid of useless variables.
Tested with success on Etherpad
Try etherpad testing.

Fix n usage

---

data/templates/nginx/plain/yunohost_admin.conf
data/templates/nginx/server.tpl.conf

- http/1 deprecated with the nginx on stretch
- upgrade to http/2 protocol
Need test / Finished.
big question :P
Requirements : Stretch

[enh] Enable HTTP2 protocol in nginx conf

---

src/yunohost/app.py
src/yunohost/certificate.py
src/yunohost/domain.py
src/yunohost/dyndns.py
src/yunohost/tools.py

*Sorry this is a clone of the [previous PR](https://github.com/YunoHost/yunohost/pull/450) that I closed accidentally*
On some hardware python imports can be very slow.
For example importing module *requests* can take up to 5 seconds:
python -m timeit -n 1 -r 1 'import requests'
1 loops, best of 1: 5.53 sec per loop
This PR moves some of these slow imports where they are really needed (this is sometimes called lazy module import).
After that these commands became way faster:
- yunohost app setting ...
- yunohost app list
- yunohost domain list
- yunohost domain dns-conf
- yunohost dyndns installcron/removecron
- ... and maybe others
...
...

[enh] Lazy-load some module for perf improvements

---

data/templates/nginx/server.tpl.conf

- Problem with the CSP
- Add CSP by the packagers in their app conf
- More permissive CSP
Not tested / Reviews needed (3)
- Install Yunohost and add this line in /etc/nginx/conf.d/domain.conf

Tweak the CSP config in nginx template for domains

---

data/actionsmap/yunohost.yml
src/yunohost/ssh.py
src/yunohost/user.py

Currently the commands to manipulate ssh keys and allow/disallow are split into two separate things, which imho doesn't make sense in terms of UX...
(Also found a few bugs related to SSH in the process...)
Move all SSH operations into a sucategory of 'user', such that we get : 
```
usage: yunohost user ssh {allow,disallow,list-keys,add-key,remove-key} ...
[-h]
Manage ssh access
optional arguments:
-h, --help            show this help message and exit
actions:
{allow,disallow,list-keys,add-key,remove-key}
allow               Allow the user to uses ssh
disallow            Disallow the user to uses ssh
list-keys           Show user's authorized ssh keys
add-key             Add a new authorized ssh key for this user
remove-key          Remove an authorized ssh key for this user
```
Tested, …

Move ssh commands into a subcategory of 'user' + fix a few bugs

---

data/templates/nginx/plain/yunohost_admin.conf
data/templates/nginx/server.tpl.conf

- Security problem which affect Diffie-Hellman (DH) key exchange parameters
- Add ECDH Curves
- Work Finished/Review needed
- Install Yunohost :P

[enh] ECDH Curves

---

data/templates/nginx/server.tpl.conf

- Error typo in the nginx conf
Descriptif de l'errreur : 
Je rappelle que le ; est le signe qui permet de revenir à la ligne dans les configuration de nginx (comme dans bcp de langage). Ici, il croit que la ligne ne s'arrête pas, donc il nous dit : 
`nginx: [emerg] invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/domain.tld.conf:50`
Le ; à l'intérieur des guillement ne compte pas, car son élément parent c'est le header lui-même(l'argument de Content-Security-Policy), et pas la fonction add_header elle-même.
- Solve the typo problem
Work Finished/Review Needed
Must be merged quickly. Nginx doesn't work
Install Yunohost / + Nginx

[fix] Nginx Regression typo

---

src/yunohost/service.py

Fix this problem probably created by a very old change of mine to cleanup services.yml https://dev.yunohost.org/issues/1082
Ready to be merged.
Put "stuff: null" in /etc/yunohost/services.yml
Micro decision, just waiting some days in case of.

[fix] some services are marked as None

---

src/yunohost/tools.py
src/yunohost/vendor/spectre-meltdown-checker/README.md
src/yunohost/vendor/spectre-meltdown-checker/spectre-meltdown-checker.sh

Seems like there was a lot of activity on the spectre/meltdown checker repo so this needs update
Ran : `git subtree pull --prefix src/yunohost/vendor/spectre-meltdown-checker https://github.com/speed47/spectre-meltdown-checker/ v0.37 --squash`
Not tested at all, we should at least check that the API hasn't changed :sweat_smile: 
Run the diagnostic in CLI, and we should also verify that the check when arriving on the webadmin home page still works

Update spectre meltdown checker

---

data/helpers.d/utils

Actually we don't have a helper to just download the source and check the checksum. By example we need that while we want to install a specific debian package or a python wheel.
Add a option `SOURCE_EXTRACT` in the actual helper `ynh_setup_source`.
Ready for a review. Tested on a specific branch of [synapse](https://github.com/YunoHost-Apps/synapse_ynh/tree/new_setup_source_helper). Might be also implemented in [monitorix](https://github.com/YunoHost-Apps/monitorix_ynh).
Try a synapse install from this specific branch. You could also try an implementation on an other app.

[enh] Add SOURCE_EXTRACT (true/false) in ynh_setup_source

---

data/templates/postfix/main.cf

In mail log we can found some "Untrusted TLS connection established" message
Indicate where are certs
Tested
Apply this patch, reload postfix, and try to send a mail, you should see in log this message:
"Trusted TLS connection established to"

[fix] Untrusted TLS connection established to

---

data/helpers.d/backend

- Actually the helper `ynh_add_nginx_config` is not really useful if we have an other variable witch need to replaced.
- After the issue `alias_transversal` we always need uncomment the redirection while we install the app in subdir.
Add 2 new features :
- Permit to replace some others variables in the template
- Manage automatically the redirection (alias_transversal issue fix) as we do in each apps.
Tested on two apps (seafile and riot).
Test the last version of seafile and riot, or implement this new helper in your app.

[enh] Improve ynh_add_nginx_config

---

data/helpers.d/package

equivs-build prints 3 warnings:
```
dh_install: Compatibility levels before 9 are deprecated (level 7 in use)
dh_installdocs: Compatibility levels before 9 are deprecated (level 7 in use)                       
dh_installdeb: Compatibility levels before 9 are deprecated (level 7 in use)
```
Fix the compatibility level at 10 in the compat file used by equivs-build
Tested on stretch and jessie.
Install an app, like piwigo or nextcloud.

[fix] Remove warning from equivs

---

data/templates/yunohost/services.yml

Following #469, we need to add status: null for "pseudo-services" in services.yml. There's a pseudo-service "yunohost" which was forgotten
Add `status: null` for the yunohost key in services.yml
Microdecision / waiting for Bram's feedback
If you're on the latest unstable, `yunohost service status` should be broken because it can't fetch the status of the "yunohost" service.

We need to set status:null for yunohost pseudo-service

---

data/actionsmap/yunohost.yml

Apparently 30 chars is too short https://github.com/YunoHost/issues/issues/962
Move to 50 as requested (shouldn't we put more actually? I don't see the point of the limit)
Gud

backup filename limit set to 50

---

data/templates/yunohost/services.yml
src/yunohost/service.py

Fixes https://github.com/YunoHost/issues/issues/1134
Offers a list of alternates names, doesn't fail on failed to grab a service.
Do a regen-conf.
Have a situations where you have mariadb instead of mysql or hack `/etc/yunohost/services.yml` to replace "mysql" by "mariadb" then put "mysql" as an alternates on "mariadb" and do a `yunohost service status mariadb`.
Since it's a fix to an already accepted PR I'm really tempted to put that as a microdecision. Let's way a bit in case of.

Mysql mariadb get status

---

src/yunohost/service.py

Due to more display of errors and removing of yolo logics, users get those errors in logs oh a `yunohost service log`:
```
2018-05-30 23:56:24,043 INFO     moulinette.actionsmap process - processing action [9018.1]: yunohost.service.log
2018-05-30 23:56:24,061 WARNING  yunohost.service _tail - [9018.1] Error while tailing file '/var/log/mysql.log': [Errno 2] No such file or directory: '/var/log/mysql.log'
File "/usr/lib/moulinette/yunohost/service.py", line 671, in _tail
with open(file, 'r') as f:
IOError: [Errno 2] No such file or directory: '/var/log/mysql.log'
2018-05-30 23:56:24,062 WARNING  yunohost.service _tail - [9018.1] Error while tailing file '/var/log/mysql.err': [Errno 2] No such file or directory: '/var/log/mysql.err'
Traceback (most recent …
```

[fix] check if log exists before tailing to avoid errors

---

bin/yunohost
src/yunohost/app.py
src/yunohost/backup.py
src/yunohost/certificate.py
src/yunohost/data_migrations/0002_migrate_to_tsig_sha256.py
src/yunohost/data_migrations/0003_migrate_to_stretch.py
src/yunohost/domain.py
src/yunohost/dyndns.py
src/yunohost/firewall.py
src/yunohost/hook.py
src/yunohost/service.py
src/yunohost/tools.py

c.f. https://github.com/YunoHost/issues/issues/971
Set verbose by default and remove the corresponding option (`--verbose`). This also implies to reflag some `INFO` message as `DEBUG`, and some `WARNING` as `INFO`.
Should be okay, but this goes with https://github.com/YunoHost/yunohost/pull/383 and https://github.com/YunoHost/moulinette/pull/155
Pull the branch in and run some command which will display some INFO messages ... Note that you need https://github.com/YunoHost/moulinette/pull/155 (the locales/en.json part) to have the nice Info: prefix.

[enh] Verbose by default

---

debian/control
src/yunohost/backup.py
src/yunohost/tests/test_backuprestore.py

We hoped that archivemount would be great for backup restoring and intended to use it as the default solution, but turns out that it suboptimal and leads to various issues.
Also currently, restoring an archive on a system where archivemount is not installed leads to a warning like "Failed to mount the archive", which makes it looks like the restore is failing where it falls back to "untaring" the archive which is fine.
Remove all code related to archivemount, and just use the untar-ing as default method, which in fact is better than archivemount on several aspects.
Not tested :|
Pull the branch and try to restore some backup archives (full restore and partial restores)

Remove archivemount stuff

---

locales/en.json
src/yunohost/backup.py

I tried to restore a backup of nextcloud made in jessie on my new stretch instance.
Was not working due to bad php5/php7 management.
https://github.com/YunoHost/issues/issues/1140
I use here the backup.csv fileto redirect correctly the file in the good place.
I also delete a _common.sh file, because it's a bad pactice of packaging, that stores accidentally this file in /backup dir.
Untested, I just test the methodology, but i have done a sed manually and delete the _common.sh with pdb.
Try to restore a nextcloud from jessie on a stretch version. Other php app are concerned too.

[fix] Redirect corectly php5 to php7 file during restore

---

data/actionsmap/yunohost.yml
src/yunohost/backup.py

c.f. https://github.com/YunoHost/issues/issues/1102
Currently there are some counter-intuitive behaviors with `backup create` and `backup restore`.
Typically, `yunohost backup create --apps wordpress` will backup wordpress *and the whole system*. You need to explicitly add `--ignore-system` at the end. Similarly, `yunohost backup create --system ldap` will backup the ldap base *and all the apps*. This kind of stuff also apply for the restore, so  `yunohost backup restore --apps wordpress` will restore wordpress *and all the system* ...
This would be nice to have this fix for stretch as we can expect several people to be willing to use the backup/restore instead of the straight migration.
- (Remove old deprecated `--hooks` options)
- Remove `--ignore-system` and `--ignore-apps`
- Only …

Fix counter-intuitive backup API

---

data/actionsmap/yunohost.yml
locales/en.json
src/yunohost/app.py
src/yunohost/hook.py

After spreading information about my POC on applications actions (see #486) someone asked me if YunoHost though about doing configuration panels for applications like in open media vault. Unaware of this feature I've asked more information and he provide me with some screenshots, here are 2 of those:
He told me that this allows to manage the configuration of the applications, something than you can normally only do on CLI. After talking with @maniackcrudelis about that it appears that it look like a good and useful thing to have in YunoHost and we start thinking about how to do that.
Thinking more about it, I realise that this would have make the writting of https://github.com/labriqueinternet/vpnclient_ynh and https://github.com/labriqueinternet/hotspot_ynh since they basically only ship …

[enh] POC to allow applications to ship configurations panels for the software they bundle

---

data/hooks/restore/23-data_mail

https://forum.yunohost.org/t/mail-services-dovecot-slapd-postfix-bug-after-reinstall-from-backup-without-postinstall/5047/2
Be sure to put the good permissions
Ready

[fix] Mail permission issue after restore

---

data/actionsmap/yunohost.yml
src/yunohost/app.py
src/yunohost/hook.py

A lot of actions can or needs to be run on the CLI level for a lot of apps (like all owncloud commands, same for wallabag) and more actions could be interesting for applications (import/export/upgrade/fixs/set admin/enable or disable stuff/etc...).
In general that increase the power of app developpers that are already doing a lot of cool things.
CLI api:
```
yunohost app action list $app_id
yunohost app action run $app_id $action -a $arguments --verbose
```
All the app installation arguments mechanism as been reused to be coherent and because that's already working well.
The application must ship a file named `actions.json` stored at the same level than its `manifest.json`.
Here is an example:
```
[{
"id": "restart_service",
"name": "Restart service",
"command": "echo pouet …
```

[enh] POC for app actions

---

src/yunohost/certificate.py

Due to the files hierarchy in YunoHost we end up having a recursive import in `certificate.py` (between this file and `domain.py`) which slow down things a lot.
On my vagrant this makes importing `domain.py` take up to 24(!) secondes(!!).
Ironically this is probably my fault.
Remove this crap.
Ready to merge, would be more confident with more test but yeah...
I've runt pyflake that told me that everything was fine.
Uses "time yunohost domain list" with and without the patch I guess, or anything that imports `domain.py` or `certificate.py`.
Adding some debug prints, here is an importation session of `domain.py` before my patch:
```
system imports: 6.99999999998e-06
moulinette imports: 1.9e-05
system imports: 0.012668
moulinette imports: 0.00262
system imports: 0.019746
moulinette imports: …
```

[fix] fix recursive super slow import in certificate.py

---

data/hooks/conf_regen/15-nginx

Sometime (for example at the first time of a vagrant or because the user has decided to), nginx is not running.
That breaks the regen-conf with this error:
Warning: nginx.service is not active, cannot reload.
Error: Script execution failed: /usr/share/yunohost/hooks/conf_regen/15-nginx
Check if nginx is running before trying to reload it.
I'm not 100% sure if we want to do that :/
Ready to merge
yunohost service regen-conf nginx
With nginx stopped.

[fix] sometime nginx is not running

---

src/yunohost/utils/network.py

`get_public_ip` is used by `dyndns_update`. In some networking configuration (because network) ipv6 is up but goes nowhere, therefor the request never finish.
Currently, we use urllib (yes, urllib1) which never timeout, therefor `dyndns_update` never complet, get stuck and the cron keep spawning more and more which ends up eating all the RAM of the server and making it unusable, which is a pretty serious problem.
Since this is quite server and pretty easy to fix I think we should also release a fix for jessie.
Add modern code that times out.
Run dyndns_update.
Microdecision.

[fix] timeout on get_public_ip otherwish dyndns update is stucked

---

src/yunohost/app.py

Right now, the CLI help to chose a value for a boolean type during an app installation is horrible from a UX point of view, it looks like this:
Is it a public Zerobin site ? [1 | 0] (default: 0):
Good luck guessing what is true and what is false.
It's a long know problem and it happen to have pissed me off once too often and I was working on that part of the code.
Do something that regular non nerdy humans can understand, like this:
Is it a public Zerobin site ? [yes | no] (default: no): 
It also now accept: "yes", "y", "no", "n", "1", "0" as valid answers and ignore the case.
Tested for me and ready to merge.
Install zerobin.

[ux] display human understandable choice for boolean type on installation

---

data/helpers.d/nodejs

A few minor things forgotten when actually removing nodejs via the helper ?
c.f. https://github.com/YunoHost-Apps/wekan_ynh/issues/6
and https://github.com/YunoHost-Apps/wekan_ynh/blob/master/scripts/_future.sh#L162
Add missing lines
To be validated / reviewed by actual nodejs / helper experts :P I have no idea if this is the right thing to do
Uh idk :s

Fix nodejs removal in ynh_remove_nodejs

---

locales/en.json
src/yunohost/app.py

On app installation it can happen that a user is required. On CLI interface we don't have a drop down menu to select the user so we need to remember from memory the username of the right user. That sucks.
Solves https://github.com/YunoHost/issues/issues/1149
Display available users. Code is based on domain listing just above.

[enh] list available users on app installation user argument

---

src/yunohost/app.py
src/yunohost/user.py

Fixes https://github.com/YunoHost/issues/issues/1163
Allow an application to optout of ssowat if the key 'no_sso' is defined (I don't think checking for a value makes that much sens here).
The only interesting commit of this PR is https://github.com/YunoHost/yunohost/commit/2bf327970b9f9270d6d5453a68b31fa835d22392
Tested and ready to merge, except if we want to bikesheed on the key name but I really don't care about that, just don't block the PR too long for that plz :/
yunohost app setting app_that_should_appear_in_sso no_sso -v true
yunohost app ssowatconf
cat /etc/ssowat/conf.json  # ← here you shouldn't see the app in the conf in the users section

App without sso

---

src/yunohost/tools.py

As documented [here in section "Support for daemonized app containers"](https://linuxcontainers.org/fr/lxc/news/#major-changes) since LXC 3.0 the init process ID is 1. So it's not possible to detect if we are in a container by just getting the init process ID.
Use an other solution which might be more strong which is using the `systemd-detect-virt` command.
- Tested with lxc 3.0 (which need to return true).
- Tested with virtualbox (which need to return false).
- I just wrote 'lxd', 'docker' but I didn't test it, so it could be false. If somebody use docker, lxd, or an other container manager it could be interesting to know what return the command `systemd-detect-virt`.
- Testing what return `systemd-detect-virt` in some different architecture could be useful to improve this PR.
- Get …

Fix container detection

---

data/hooks/conf_regen/15-nginx
data/templates/nginx/autoconfig.tpl.xml
data/templates/nginx/server.tpl.conf
src/yunohost/app.py

Configuring Thunderbird can be tedious.
You have to select the proper protocols and ports for both incoming and outgoing emails.
Fortunately there is a mechanism called [Autoconfiguration](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration ) we can use to make life easier for users of Thunderbird.
TL;DR, the yunohost server only needs to publish a specific XML file on http://domain.tld/.well-known/autoconfig/mail/config-v1.1.xml, Thunderbird will find it and then automatically configure the proper ports and protocols.
Create a new domain like *example.net* and create a user account like john@example.net.
Don't forget to update the DNS configuration for this new domain.
Then open Thunderbird, add a new mail account.
In the popup, fill the 3 fields (name, email …

[enh] Add MUA autoconfig.

---

src/yunohost/certificate.py
src/yunohost/vendor/acme_tiny/acme_tiny.py

The "no-check" logic is not propagated to acme-tiny, this can cause a bug in the following situation:
- domain DNS is correctly configured and is accessible from outside
- but locally the IP to this domain is wrong for some reason
- acme-tiny will attempt to get the certificate through http to make a check
- this check will fail
It's also important to note that this is pretty hard to debug, the error message is bad and in english and is confusing because it doesn't tell that it's a LOCAL attempt to download the file.
If we agree on modifying acme-tiny I will also modify this error message if I don't forgot to do it.
Have no respect and modify acme-tiny code.

[mod] propagate the no_checks logic to acme-tiny code

---

locales/en.json
src/yunohost/app.py

`app checkurl` and `app initdb` are deprecated but still used in some ~maintained apps.
Propose to put a more agressive message (error instead of warning) so that hopefully one day we can decide to get rid of this legacy code :| ...
Also : 
- I pointed to the helper instead of "use app register-url" since it's probably more relevant
- I moved the entire message to app.py because it doesn't make much sense to bother translators with that message. The message is aimed to app packagers which should understand english ? :s 
Ready to merge if people agree
Run `app checkurl` and `app initdb`

More agressive deprecation messages for app checkurl and initdb

---

locales/en.json
src/yunohost/app.py
src/yunohost/domain.py

Right now when we try to install an application but it conflicts with an already installed application at the path level we get a kinda "fuck you" error that just says that there is a conflict.
It sucks for the users and doesn't give any hint on how to fix that.
Display all conflicting applications.
Example:
Test in "yunohost tools shell" and should be good.
Like on the screenshot.

Better error path conflict

---

data/helpers.d/package
debian/control

The `equivs` package is necessary to build the dependences package. Installing this package at package build is not really efficient.
Set it as dependence.
Not tested because it's look like really a small change.
- Build the debian package
- Try to install an app which use a dependence

Set equiv as base dependance

---

debian/control

Sometimes there is no Real Time Clock Battery (arm board, old battery ...). The time is needed to be able to make TLS/openvpn authentication securely.
Set fake-hwclock as dependency of yunohost.
Fake-hwclock save the clock each hours and at shutdown. On boot, it will check if the current date is under the registered date and if it's the case load the registered date. This is needed 
Ready, Micro decision
I think it's ok

[enh] Add fake-hwclock

---

debian/control

We often need to query json (and maybe modify) files in shell scripts. Right now we uses python or grep/other to do that, that's both not practical (and slow for python) and not very reliable.
Add jq as a dependancy so scripts can rely on that, it's a tool meant for that: https://stedolan.github.io/jq/

[enh] add jq as a dependancy

---

src/yunohost/app.py
src/yunohost/backup.py
src/yunohost/hook.py

Historically `hook_exec` was run with admin, nowadays almost all call set `user="root"` so we can simplify the code
Simplify the code
Microdecision, ready to merge
Does it need testing /o\

Run hook_exec as root by default

---

locales/en.json
src/yunohost/certificate.py

We have this piece of legacy code. Today, because app.yunohost.org was down, people could not install a certificate. c.f. this stacktrace from @e-lie : 
```
File "/usr/bin/yunohost", line 213, in <module>
timeout=opts.timeout,
File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 136, in cli
moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 390, in run
File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 498, in process
File "/usr/lib/moulinette/yunohost/domain.py", line 215, in domain_cert_install
return …
```

Remove old legacy code about letsencrypt_ynh

---

data/helpers.d/backend

If the owner of a log file is not root we could receive this message from logrotate : 
```
/etc/cron.daily/logrotate:
error: skipping "/var/www/horde/horde/log.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/www/horde/horde/services/log.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/www/horde/horde/services/portal/log.log" because parent directory has insecure permissions (It's world writable or writable by group …
```

Add su directive as option for logroate

---

doc/generate_helper_doc.py
doc/helper_doc_template.html

I created https://github.com/YunoHost/helpersdoc and http://helpers.yunohost.org/ and it was in fact quite stupid to do that on a separated repo + a separate dedicated page just to use Bootstrap 4 cards
I reworked the script and CSS to make it compatible with current Simone so that we can integrate it directly in the existing documentation :+1: 
Working
Run `python2 generate_helper_doc.py`  and copypasta helpers.html in the doc editor to see how it renders.

Add script to automatically generate helpers documentation

---

src/yunohost/certificate.py

```
09:39 | <yunobridge> | <lasnico> Bonjour, j'ai un "problème" avec Yunohost. Tous les jours, je reçois un e-mail contenant ceci : /etc/cron.daily/yunohost-certificate-renew:
-- | -- | --
09:39 | <yunobridge> | <lasnico> No certificate needs to be renewed.
09:40 | <yunobridge> | <lasnico> Il essaie chaque jour de renouveler le certificat, ok, mais pourquoi envoi-t-il un e-mail pour dire qu'il n'a pas été renouvelé ?
09:43 | <yunobridge> | <lasnico> Le certificat est encore valide pour pas mal de temps
```
Avoid outputing this message if we are running the command from the cron task.
Ready
...

[enh] Don't send email if no certificate need to be renewed

---

data/helpers.d/getopts

As said here, https://github.com/YunoHost/yunohost/pull/455, using positional arguments could be a problem when we're adding new options to a helper.
Use a helper to allow to use easily getopts to manage arguments.
Have a look to [experimental helpers](https://github.com/YunoHost-Apps/Experimental_helpers), which already use getopts.

Add the internal helper ynh_handle_getopts_args

---

bin/yunoprompt

Some fingerprints are display but can't be used because SSH conf don't allow to use those fingerprint.
Just display fingerprint used by SSH
Ready, this PR is derivated from an other one which change SSH config...
...

[enh] Display only used fingerprint in bootprompt

---

lib/metronome/modules/mod_auth_ldap2.lua

Users traces with 3.10.13+
The session state should always be passed in the profile as util.sasl functioning now relies on it
...
...

mod_auth_ldap: reflect SASL API changes in latest Metronome.

---

data/helpers.d/utils

When we use ynh_setup_source there is a strange noisy warning like this. This noise is displayed to the user...
`2018-09-19 16:11:29 URL:https://github-production-release-asset-2e65be.s3.amazonaws.com/271714/6b136718-52da-11e7-93f3-2b4ee2eccece?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20180919%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180919T141124Z&X-Amz-Expires=300&X-Amz-Signature=15c6db1dc3ca633a3e4ba8e903500976d38a5100dcd1ea022deaa72cd15b5c34&X-Amz-SignedHeaders=host&actor_id=0&response-content-disposition=attachment%3B%20filename%3Dwkhtmltox-0.12.4_linux-generic-amd64.tar.xz&response-content-type=application%2Foctet-stream [14541904/14541904] -> "app.tar.xz" [1]`
Display only error but not output. wget has no option for that, so we need to make like …

[fix] Silent output/warning but display errors

---

data/helpers.d/filesystem

During a change_url script, the checksum of the nginx conf file has to be removed.
Provide a simple helper to remove a checksum corresponding to a file.

Add ynh_delete_file_checksum

---

data/helpers.d/utils

- Curl fail with http2 with wordpress app.
- Add a sleep after nginx is reloaded.
By example if we have a code like that it fail : 
```bash
systemctl reload nginx
ynh_local_curl "/wp-admin/install.php?step=2" "&weblog_title=YunoBlog" "user_name=$admin_wordpress" "admin_password=$db_pwd" "admin_password2=$db_pwd" "admin_email=$admin_wordpress@$domain" "Submit=Install+WordPress"
```
But this code won't fail : 
```bash
systemctl reload nginx
sleep 2
ynh_local_curl "/wp-admin/install.php?step=2" "&weblog_title=YunoBlog" "user_name=$admin_wordpress" "admin_password=$db_pwd" "admin_password2=$db_pwd" "admin_email=$admin_wordpress@$domain" "Submit=Install+WordPress"
```
Tested with the CI, but need more test.
- Checkout the branch
- Enable http2 in the nginx config
- Try to install wordpress

Fix http2 with curl

---

data/actionsmap/yunohost.yml

- https://github.com/YunoHost/issues/issues/1226
- change regex to allow "-" in lastname.
Tested. Work finished.
Micro-decision.
...

[fix] Allow - between two name

---

data/templates/metronome/metronome.cfg.lua

Some now wanted features aren't loaded because Metronome uses a very old file
Conform configuration file to latest v3.11 release file, Metronome v3.11.x is best package or Metronome might throw a few (non-fatal) errors on startup

Update Metronome configuration file to v3.11 standard

---

data/templates/slapd/ldap.conf

- fixes https://github.com/YunoHost/issues/issues/1218
- Complete conf
Work finished. Tested in production. As it's not really setup configuration.
...

[fix] Add a proper conf for LDAP (Issue 1218)

---

data/templates/ssl/openssl.cnf
src/yunohost/tools.py

When a user reinstall a yunohost with the same domain, an error ssl is displayed on the browser:
An error occurred during a connection to 192.168.0.12. You have received
an invalid certificate. Please contact the server administrator or email
correspondent and give them the following information: Your certificate
contains the same serial number as another certificate issued by the
certificate authority. Please get a new certificate containing a unique
serial number. Error code: SEC_ERROR_REUSED_ISSUER_AND_SERIAL
Put a random serial number into the CA certificate.
Ready BUT i have just test by applying manually the change on a yunohost instance.
...

[fix] Use random serial number for CA

---

data/templates/nginx/plain/yunohost_api.conf.inc

This is useful to validate Origin/Referer headers in order to prevent CSRF.
We might want to validate `Referer`/`Origin` headers to prevent CSRF but the `Host` header passed to the application is `localhost:$port` instead of the original one.
Let nginx pass the original `Host` header.
...
...

Pass Host header to YunoHost API

---

src/yunohost/backup.py

Issue https://github.com/YunoHost/issues/issues/1001
When sorting the list of backups, instead of sorting them by name (default) use a lambda function that sort them by creation date of the file.
I'm sorry, I was not able to test it... I can't have the testing VM to work on my computer :(
Create some backups by giving them different names. See how the backups are sorted.

Add a sorting lambda function when sorting the backups list

---

data/hooks/conf_regen/15-nginx
data/templates/nginx/server.tpl.conf

- Every time, the browser needs to send a request to LE to check if the SSL Cert is not revoked.
- Add OCSP Stapling
Not tested.
Review required.
Install Yunohost + nginx

OCSP Stapling

---

src/yunohost/dyndns.py

fix https://github.com/YunoHost/issues/issues/1063

[fix] 'dyndns update' should check the upstream dns record

---

locales/en.json
locales/fr.json
src/yunohost/user.py

- Error message is not useful to inform user that email adress will be created by default ( fixes https://github.com/YunoHost/issues/issues/1216)
- Add a custom Message.
Finished. Not tested.
- Install Yunohost (ynh-dev)
- Modify app.py
- Try to create a user and add an already-used alias for this email

[fix] Improve the message w.a. when admins tries to create users with a reserved Email Address (Issue 1216)

---

data/helpers.d/backend

As reported here https://github.com/YunoHost/issues/issues/1213, here https://blog.genma.fr/?Yunohost-Soucis-a-la-suppression-d-une-webapp and in several posts on the forum, we currently have an important bug with PHP apps where a file is not removed and makes php7.0-fpm crashes.
Turns out `ynh_remove_fpm_config` still assumed we were in jessie with Php5 :|
Tested and ready
Follow Genma's instructions with and without the PR : https://blog.genma.fr/?Yunohost-Soucis-a-la-suppression-d-une-webapp

[fix] php conf files not properly removed when an app is uninstalled

---

data/helpers.d/string

200 are not enough if you try to generate a 64 characters string.
Use 1000 blocks instead
Ready to be reviewed

[enh] Use more blocks for dd in ynh_string_random

---

src/yunohost/app.py

In `yunohost/app.py`, `app_removeaccess` calls `allowed_users.append` which doesn't exist for the `set` `allowed_users`.
Call `allowed_users.add`.
Trivial change. Tested in production. Ready to be reviewed.

[fix] app_removeaccess call set.add

---

data/helpers.d/package
debian/control

We have a lot of failed upgrade because of apt couldn't get its lock file because of another apt running in background.
Add an internal helper to check before any apt helper if the lock is free. Or wait to run apt.
Tested on a VM
Run an apt command that will hang, waiting for an answer from the user. Like an install or an upgrade.
Then try to use an apt helper.

[enh] Wait for dpkg lock to be free

---

src/yunohost/app.py

When the setting `allowed_users` exists but is empty, `app_addaccess` produces a "ghost" user.
The problem lies on line [969](https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/app.py#L969). If `app_settings['allowed_users']` is an empty string, `set(app_settings['allowed_users'].split(','))` evaluates to `set([''])` which represents an unnamed user. Since the initial value for the `allowed_users` set is not checked by the call to `user_info` on line [974](https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/app.py#L974), this prepends an empty string to the result.
Take a test app `my_app`.
```bash
yunohost app clearaccess my_app
yunohost app addaccess my_app -u user1
yunohost app removeaccess my_app
yunohost app addaccess my_app -u user1
yunohost …
```

Fix app_addaccess behaviour when 'allowed_users' is initially empty

---

data/helpers.d/filesystem

Especially with the migration to stretch, it happens quite often that a file is missing in an app for php or fail2ban.
But, if a fail2ban config is missing, the app will still be working.
The current behavior can break an upgrade without any restoration of the backup, because a file is missing during the backup.
Print a warning but do not fail if a file is missing, except if this file is really important for the app.
Tested on a VM.
Can be reviewed.
Replace the helper, and remove a file used during the backup.

Do not fail on missing fail2ban config during the backup

---

data/templates/nginx/server.tpl.conf

Better security is option is not recommended.
...
...
...
...

Update ECDH curves recommended by Mozilla, now that we are on stretch

---

src/yunohost/tools.py
src/yunohost/utils/password.py

`--force-password` not working during postinstall, because there's a call to `tools_adminpw` which also performs a check of the strength. 
Pass a new `check_strength` argument to `tools_adminpw` so that we can disable the check if `--force-password` is used.
Yolocomitted, not tested :s 
Run a postinstall with a dummy password and `--force-install`

[fix] Password constrains and checks not behaving properly

---

data/helpers.d/backend

Have a look to https://github.com/YunoHost-Apps/nextcloud_ynh/issues/138 for more information.
Do not use separate ini file anymore.

Do not use a separate ini file for php pools

---

src/yunohost/firewall.py

https://forum.yunohost.org/t/work-around-router-upnp-shortcomming-implementations-netgear-cbvg834g/5730
teajay-fr suggest to increase discover time and listen on 1900 to support some router that doesn't respond to discover query
Note: i don't know if it's solution increase the postinstall time ?
Need Feedback, i don't know if it's a good idea
...

[enh] Improve upnp support

---

data/helpers.d/package

In `ynh_wait_dpkg_free`, there's a `break` if the lock is free. But right after the function, a warning is displayed (in all cases) saying the lock ain't free.
Use `return` because we don't wanna show a warning if the lock is free
Microdecision / waiting for confirmation from @maniackcrudelis  ;)
...

Return instead of break, otherwise warning is shown

---

bin/yunoprompt
data/hooks/conf_regen/03-ssh
data/templates/ssh/sshd_config

There are various settings which can be improved in the sshd configuration to increase security.
I used the Mozilla recommendation which I found here : https://infosec.mozilla.org/guidelines/openssh
I also cleaned a few things : many weird commented settings which are unlikely to be used, or settings which corresponds to the default setting and therefore unnecessary to state them.
Of course, the best security gain in here would be to disable password authentication... To quote a guy from Stack Overflow : « The authentication and negotiation ciphers are far more important than the symmetric algorithm for the overall security »
Tested in a dev environnement ... but we should be careful and test this in various setups. (e.g. does this break putty ? etc...)
This is built on top of …

[enh] Clean + harden sshd config using Mozilla recommendation

---

src/yunohost/domain.py

See https://github.com/YunoHost/issues/issues/1247
Change quotes around `letsencrypt.org`
For review
Print recommended DNS configuration from YunoHost admin

[fix] Quotes around CAA value for letsencrypt.org

---

locales/en.json
src/yunohost/tools.py

There are a few issues in the way migrations currently works : 
- if for instance 2 auto migrations are pending followed by 1 manual migration, none will be ran during a `dist-upgrade`. This currently partially breaks migration to stretch because migration 6 is manual. Hence migrations 3, 4 and 5 are not ran and therefore migration to php 7 does not happen entirely ...!
- if there are several migrations pending, one cannot skip one migration and run the others
- if several migrations with disclaimers are pending, using `--accept-disclaimer` will accept all disclaimer and not just the first one
- (minor/cosmetic) Postinstall shows weird Warnings about skipped migrations
Fix the behavior of `--auto`, `--accept-disclaimer` and `--skip` such that all migrations that can be ran are ran until a …

[fix] Manual migration and disclaimer behaviors

---

locales/en.json
src/yunohost/service.py

During postinstall, there are quite a few messages being displayed such as : 
```
Info: The configuration file '/etc/metronome/metronome.cfg.lua' is now managed by the service metronome.
Success! The configuration has been updated for service 'metronome'
Info: The configuration file '/etc/postfix/master.cf' is now managed by the service postfix.
Info: The configuration file '/etc/postfix/main.cf' is now managed by the service postfix.
Info: The configuration file '/etc/default/postsrsd' is now managed by the service postfix.
Success! The configuration has been updated for service 'postfix'
```
While the wording "is now managed by the service postfix" is "right", it's probably a bit weird for external people because e.g. `master.cf` is anyway a conf file used by the service postfix ... …

Change message about conf now being managed by service -> yunohost

---

.gitignore
locales/en.json
src/yunohost/settings.py
src/yunohost/tests/test_backuprestore.py
src/yunohost/tests/test_changeurl.py

Many tests are broken
Fix it
Note that a fix is solved in moulinette in [#185](https://github.com/YunoHost/moulinette/pull/185)
All test should be fixed
In the moulinette repos, use the branch `fix_ldap_authenticator`.
run `./ynh-dev test yunohost`

[fix] Repair tests

---

src/yunohost/app.py
src/yunohost/backup.py
src/yunohost/certificate.py
src/yunohost/data_migrations/0002_migrate_to_tsig_sha256.py
src/yunohost/data_migrations/0003_migrate_to_stretch.py
src/yunohost/data_migrations/0005_postgresql_9p4_to_9p6.py
src/yunohost/data_migrations/0006_sync_admin_and_root_passwords.py
src/yunohost/data_migrations/0007_ssh_conf_managed_by_yunohost_step1.py
src/yunohost/data_migrations/0008_ssh_conf_managed_by_yunohost_step2.py
src/yunohost/domain.py
src/yunohost/dyndns.py
src/yunohost/firewall.py
src/yunohost/hook.py
src/yunohost/log.py
src/yunohost/monitor.py
src/yunohost/service.py
src/yunohost/settings.py
src/yunohost/ssh.py
src/yunohost/tests/test_appslist.py
src/yunohost/tests/test_appurl.py
src/yunohost/tests/test_backuprestore.py
src/yunohost/tests/test_changeurl.py
src/yunohost/tests/test_settings.py
src/yunohost/tools.py
src/yunohost/user.py
src/yunohost/utils/error.py
src/yunohost/utils/password.py
src/yunohost/utils/yunopaste.py

Utilisation trop complexe. Fait perdre du temps de dev.
Supression des code d'erreur "errno et de l'internationalisation "m18n.n"

[enh] Simplify error management

---

data/actionsmap/yunohost.yml
locales/en.json
src/yunohost/app.py

Similar to https://github.com/YunoHost/yunohost-admin/pull/218 : currently there is no warning shown when installing experimental or low quality apps. We should add some to discourage users installing apps likely to break their system ...
- Ask for confirmation when installing low quality, broken/experimental, and third party apps
- A "good quality" app is defined as working + level >= 3
- A "low-quality app is defined as working + level = 1 or 2
- A third-party app is when you install from an URL or local folder
- A broken / experimental app is all other apps
- `--force` can be used to not ask confirmation
Tested and ready for feedback / discussions
Try to install an app with level 1~2, or level 0 / notworking / inprogress, from local folder and from explicit URL

[enh] Ask confirmation before installing low-quality, experimental or third party apps

---

bin/yunohost-api

c.f. https://github.com/YunoHost/issues/issues/1251 : this is annoying as fuck that people show logs from failed app install without the DEBUG-level messages, which defeats the purpose of log feature from 3.2 x_x ...
Fix the loggers/handlers log level such that it's consistent with what was expected ...
Launch an app install that will fail (or any action that shall add DEBUG stuff in the logs) and check the produced logs in /var/log/yunohost/categories/operations with and without this.

[fix] DEBUG-level messages not appearing in actions performed via the API

---

src/yunohost/tools.py

c.f. https://github.com/YunoHost/issues/issues/1232
Bram digged into the madness of `python-apt` and its (lack of) documentation to find that we could use some magic stuff to change the configuration supposedly being used during the actual upgrade...
This is not tested yet tho.
Ready ? But not tested ...
Launch a `yunohost tools upgrade` and somehow try to detect if the option is correctly being used :/

Enforce --force-confold during apt upgrade

---

data/actionsmap/yunohost.yml
locales/en.json
src/yunohost/app.py
src/yunohost/domain.py
src/yunohost/tests/test_changeurl.py

- In the `change-url` function we use a old function `check_url`.
- The change-url function call the change-url script with variable with empty value (`$YNH_APP_OLD_PATH`, `$YNH_APP_NEW_PATH
`) when the path is the root path. By this we need write a code like that : https://github.com/YunoHost-Apps/wordpress_ynh/blob/master/scripts/change_url#L41-L44 . In the same time we have in the core a function which do that : `_normalize_domain_path`.
- Replace the `check_url` by `_get_conflicting_apps`.
- Give the argument about the url as same as in the install.
Tested. Work on my side.
Note that this PR should also fix https://github.com/YunoHost/yunohost/pull/376
Test with an app which has a change-url script.

[fix] Fix the way change_url updates the domain/path

---

src/yunohost/backup.py
src/yunohost/data_migrations/0008_ssh_conf_managed_by_yunohost_step2.py

c.f. this issue https://github.com/YunoHost/issues/issues/1266
Currently, `admin` cannot access files in the archive folder, `/home/yunohost.backup/archives`. This is not such a big deal for now because I guess most people still log as root. But with 3.4 coming where we really discourage root login and encourage admin login, this prevent people from scp-ing backup archives out of their server.
When creating the folder, set `admin` as the owner of the folder. + Add a thing in migration n°8 to change the permission for already existing instances 
Not tested x_x
Test on a fresh instance, and on a migrated instance that admin can indeed access those files

[fix] Set owner of archives folder to 'admin'

---

src/yunohost/service.py

Not sure why we did not notice this before, but `_run_service_command` which is a low-level function behind `yunohost service start|stop|...` will show a Success even if the command failed ...
This is because `subprocess.Popen` won't raise a `subprocess.CalledProcessError` like the code expects ... `check_call` should be used instead.
Make a dummy breaking change to nginx conf file and try to stop/start it.

[fix] `_run_service_command` not properly returning False if command fails

---

src/yunohost/app.py
src/yunohost/domain.py

As reported by @maniackcrudelis, apps might conflict with themselves when change_url is used : 
```
Change the url from sous.domain.tld/path to sous.domain.tld/...
[...]
yunohost cli - This url is not available or conflicts with the already installed app(s):
* sous.domain.tld/path → WordPress (wordpress)
```
Add an optional `ignore_app` argument to `_get_conflicting_apps` for the change_url usecase.
Not tested :s 
Pull the branch and test to change the url of an app from `/path` to `/` for instance ... or `/path` to `/path2`

[fix] app conflicting with itself during change_url

---

data/actionsmap/yunohost.yml
src/yunohost/service.py

Some apps don't provide log files.
I have added the possibility to use systemd log (with journalctl)
I either have to create a migration file to update the file `/etc/yunohost/services.yml` or check if `log_type` is defined, and if not, I'm considering that the log is a file (as old method)
- `yunohost service log service_name --log /var/log/service_name/service_name.log`
- `yunohost service log service_name --log /var/log/service_name/service_name.log /var/log/service_name/service_name2.log`
1. The old one is still compatible:
- `yunohost service log service_name --log /var/log/service_name/service_name.log`
- `yunohost service log service_name --log /var/log/service_name/service_name.log /var/log/service_name/service_name2.log`
2. The new:
- for a file: `yunohost service log …

[enh] add systemd logs

---

data/helpers.d/user

Some packages need to create system users with a valid login shell, but the user creation helper only allows nologin shell.
Allow this helper to create users using the system default login shell.
Finished and tested.
You can possibly test the [Discourse package](https://github.com/YunoHost-Apps/discourse_ynh).

[enh] Control the login shell when creating users in ynh_system_user_create

---

data/helpers.d/user

ynh_system_user_create is failing with the error `home_dir: unbound variable`
Set `home_dir` if not used.

[fix] Fix home_dir unset in ynh_system_user_create

---

src/yunohost/data_migrations/0003_migrate_to_stretch.py

Log file will be erased at reboot. Sometimes the dist-upgrade process goes bad, and the server need a manual (and forced) reboot. 
Use the /var/log/yunohost folder, which already exists.
Take a jessie server, install yunohost 2.x, launch the migration, crash your machine during migration, hard-reboot and see if a log file exists in /var/log/yunohost.

[fix] Do not log migration to stretch in /tmp/. Issue #1280

---

data/templates/fail2ban/jail.conf

[fix] Remove old SMTP port (465) from Fail2ban jail.conf

---

data/helpers.d/utils

Sometimes, you have to remove more than one sub-directory into an archive to get the app itself.
That's what's happens with dotclear2.
Allow to dig deeper than only one sub-directory with SOURCE_IN_SUBDIR
Tested with dotclear2 with SOURCE_IN_SUBDIR as true, false, 1 and 2.

[enh] Allow to dig deeper into an archive with ynh_setup_source

---

data/helpers.d/filesystem

#635 has added a regression by using $2 directly, which fails if there's only one argument.
`/usr/share/yunohost/helpers.d/filesystem: line 351: $2: unbound variable`
Use the number of args instead of testing $2
Anyway, by using getopts, we will already have a message like: `Attention : [WARN] Too many arguments ! /my/path will be ignored.`
Tested with my new "personal" ynh-dev ;)
...
@YunoHost/apps

Fix #635 on ynh_secure_remove

---

bin/yunohost-api

c.f. https://github.com/YunoHost/issues/issues/1289
Have a custom log level setting for gnupg
Pull the branch, restart yunohost-api.
Check if 'gnupg' lines appear in `/var/log/yunohost/yunohost-api.log` while login into the admin interface

[fix] Admin password appearing in logs

---

data/helpers.d/print

I know that this helper is brand new, 2 days only, but there's no real danger with it and I really would like to see it widely used by all apps. Especially official ones.
Add the wonderful new helper ynh_script_progression :D

Add ynh_script_progression

---

data/helpers.d/getopts

Transmission fails on this [line](https://github.com/YunoHost-Apps/transmission_ynh/blob/master/scripts/install#L138) while using getopts.
Escape double quotes before the eval to prevent an interpretation.

[fix] Escape double quote before eval in getopts

---

src/yunohost/firewall.py

Restarting fail2ban is really slow on ARM architecture.
Reload should be enough.
Reload fail2ban when we reload the firewall
Tested that when we reload fail2ban all iptables rules are created a new time.
Checkout the branch.
Reload the firewall and check that the fail2ban rules are restored.

Reload fail2ban instead of restart

---

data/helpers.d/utils

In some conditions, ynh_local_curl doesn't curl the right url
I'm ensure that the url is well formatted
Tested
```
path_url=/test
ynh_local_curl index.php
```
```
path_url=/
ynh_local_curl index.php
```
```
path_url=/
ynh_local_curl /index.php
```

[fix] ynh_local_curl

---

data/hooks/backup/05-conf_ldap
data/hooks/backup/08-conf_ssh
data/hooks/backup/11-conf_ynh_mysql
data/hooks/backup/14-conf_ssowat
data/hooks/backup/17-data_home
data/hooks/backup/20-conf_ynh_firewall
data/hooks/backup/21-conf_ynh_certs
data/hooks/backup/23-data_mail
data/hooks/backup/26-conf_xmpp
data/hooks/backup/29-conf_nginx
data/hooks/backup/32-conf_cron
data/hooks/backup/40-conf_ynh_currenthost
data/hooks/conf_regen/03-ssh
data/hooks/conf_regen/15-nginx
data/hooks/conf_regen/34-mysql
data/hooks/conf_regen/43-dnsmasq
data/hooks/restore/11-conf_ynh_mysql

Ran a postinstall on unstable and realized that some regenconf hooks were broken because they use a helper, and getopts wasn't sourced...
Well that's a solution where I just load all helpers instead as in apps. Dunno that's what we want, maybe there's a significant overhead compared to sourcing getopts in each file ?
Not tested
Run a postinstall with and without this branch

[fix] Loading only one helper file leads to errors because missing getopts

---

data/helpers.d/system

During the upgrade of an app, the app itself and the package are always upgraded, even if no upgrade is really needed.
- Add the new helper ynh_check_app_version_changed to check the version before an upgrade
- Add also the helpers ynh_read_manifest, ynh_app_upstream_version and ynh_app_package_version.
- These previous helper have been modified (from the experimental version) to support getopts
- ynh_check_app_version_changed has been modified to use ynh_app_upstream_version
Ready to be reviewed
Use `ynh_check_app_version_changed` in a package.

Add ynh_check_app_version_changed

---

data/helpers.d/backend

To enhance applications protection against hackers/spammers, etc., we can propose helpers to ease the creating of fail2ban jails.
Add `ynh_add_fail2ban_config` and `ynh_remove_fail2ban_config` helpers.
A successful implementation example is the [piwigo app](https://github.com/YunoHost-Apps/piwigo_ynh).
Working, but opinion welcome!
And should be implemented in other applications to validate its principle.

[enh] Add fail2ban helpers

---

data/templates/nginx/plain/yunohost_admin.conf

- $http_user_agent ne permet pas bloquer totalement tout, et sûrement ne bloque pas tous les robot.
-  Ajouter une directive plus générale permettant de bloquer l'ensemble des contenu
- Code plus propre qu'une fonction nginx
- Évite de lister l'ensemble des User-Agent des robots d'indexation (ce qui est possible si c'est nécessaire)
Tested, but need test (I don't know how to test the effect of the header)
...
Sources (because it's needed) : 
- https://developers.google.com/search/reference/robots_meta_tag
- http://robots-txt.com/x-robots-tag/

Improve protection against indexation from the robots.

---

data/helpers.d/package

Fix https://github.com/YunoHost/issues/issues/1284
Use the way apt check that dpkg is available to know if `dpkg --configure -a` is needed.
As Aleks told me, update metronome or any other package that will ask you to replace a config file. And kill the process without answering the question.
Then, remove the lock file and you'll have a broken dpkg

[enh] Check if dpkg is not broken when calling ynh_wait_dpkg_free

---

data/helpers.d/debug

Just wrote this helper to help me debugging [getopts](https://github.com/YunoHost/yunohost/pull/646). Figured it would be really useful for every packager while trying to debug an app.
This helper can simply print a message or a variable, marked as debug. But also trace a defined part of a script instead of simply using --debug while running an install.
As this helper isn't meant to be used permanently in app packages, I think we can't merge it quickly, so it will be easily available for debugging.
Try this helper in any app.
@YunoHost/apps

Add app debugger helper

---

locales/en.json
src/yunohost/backup.py

In some conditions during a backup, the tar file is not closed.
Ensure the tar file is closed
...
...

[enh] Ensure the tar file is closed during the backup

---

bin/yunohost-api

Related to: https://dev.yunohost.org/issues/703
It's for security.

[fix] Remove version from api

---

data/helpers.d/package

In some situation, e.g. installing an app from the webadmin, the install dump some warnings : 
```text
dpkg-preconfigure: unable to re-open stdin:
debconf: falling back to frontend: Teletype
debconf: (This frontend requires a controlling tty.)
debconf: unable to initialize frontend: Readline
debconf: falling back to frontend: Readline
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: unable to initialize frontend: Dialog
```
Those are pretty annoying and technical, would be nice to get rid of them ...
My guess is that it's related to the use of dpkg inside `ynh_package_install_from_equivs` but I'm not that sure ... So tried to add `DEBIAN_FRONTEND=noninteractive` but not sure that's the issue / fix :wink: Mainly …

[fix] Get rid of annoying 'unable to initialize frontend' messages

---

debian/control

c.f. https://github.com/YunoHost/issues/issues/1242
apt-transport-https is installed in many setups because it's installed via the install-script, but it's not in the yunohost dependencies so not installed on x86 ISO. Therefore, packagers don't realize this and this later breaks install for some user who don't have apt-transport-https installed.
From what I understand, this is related to the whole question of wether or not to add additional repo. Not sure what to do exactly but it sounds to me that sometimes it can't really be avoided ... Anyway this is kinda independent, and I think for the "additional repo" thing we could add a warning in package linter or something. (My opinion is that we should have helpers / core stuff to help integrating additional repos in a clean way)
Add …

Add apt-transport-https to dependencies

---

src/yunohost/tools.py

c.f. https://github.com/YunoHost/issues/issues/1304
Cache the results from meltdown checker instead of re-running the script everytime a diagnosis is done...
The cache is stored in `/tmp/` with the idea that it shall be cleared upon a reboot (which might change the result from the script). Also since we might want to change what we do with this diagnosis, I check the modification time of the cached file against `/var/log/dpkg.log` such that the diagnosis is re-ran if there was an upgrade (of yunohost for example)
Run `yunohost tools diagnosis --debug` a few time, you should see a message indicating the result is write to / read from the cached file

Cache results from meltdown checker

---

data/helpers.d/filesystem

When `ynh_backup_if_checksum_is_different` backup a file because it was modified, an admin can't know easily what are the differences.
Print a diff of the differences between the previous file and the new one.
Change a config file, then upgrade the app.
@YunoHost/apps

[enh] Print diff of files when backup by ynh_backup_if_checksum_is_different

---

locales/en.json
src/yunohost/app.py
src/yunohost/tools.py
src/yunohost/utils/packages.py

Follow-up of https://github.com/YunoHost/issues/issues/1284 and https://github.com/YunoHost/yunohost/pull/638.
Make sure that dpkg/apt ain't broken before starting to install an app. This could also be done for other scripts which are quite likely to rely on apt : upgrade, remove and restore. I don't know if that's relevant though ... e.g. maybe we want people (or yunohost) to trigger removals even if dpkg/apt is broken ? I dunno ...
Note that the plan is anyway to add this check in ynh_apt though https://github.com/YunoHost/yunohost/pull/638 but the plan is to, where relevant, avoid starting to run a whole script if we can know it's gonna fail anyway.
c.f. https://github.com/YunoHost/issues/issues/1284#issuecomment-459375469

[enh] Assert dpkg is not broken before app install

---

src/yunohost/settings.py

c.f. https://github.com/YunoHost/yunohost/pull/640 and other similar use case : we need to be able to trigger specific code when updating a setting value. For instance, to trigger a regenconf of nginx or ssh or whatever.
Introduce a decorator `@post_change_hook("your.setting.name")` to define what code to trigger after the setting is changed. A dummy example is : 
```python
@post_change_hook("example.int")
def myfunc(old_value, new_value):
print("In hook")
print(old_value)
print(new_value) 
```
Tested, ready for review
Uncomment the example at the end and try to run for instance `yunohost settings set example.int -v 1664`

[enh] Be able to define hook to trigger when changing a setting

---

data/templates/nginx/server.tpl.conf

c.f. https://github.com/YunoHost/issues/issues/1310 , Firefox and probably all decent browser ignore this header anyway
Don't add the header if using a self-signed cert
Tested on my machine™
Pull the branch, have a domain with self-signed certificate, regen nginx conf. Check a javascript console before and after on the SSO portal.

[enh] Don't add Strict-Transport-Security header in nginx conf if using a selfsigned cert

---

data/helpers.d/nodejs

When installing nodejs on arm64 and arch64, [N - Node.js version management](https://github.com/tj/n) handle the architecture as [AMD64](https://github.com/tj/n/pull/448) and the nodejs installation failed
Use the N - Node.js version management argument --arch to specify an architecture
Done
There is a package with the functionality setuped: `yunohost app install https://github.com/YunoHost-Apps/wikijs_ynh/tree/arm --debug`

[enh] Add the arch argument to ynh_install_nodejs

---

data/templates/dnsmasq/plain/dnsmasq.conf
data/templates/dnsmasq/plain/resolv.dnsmasq.conf

No DNS query to IPv6 servers available.
Add IPv6 nameserver from http://diyisp.org/dokuwiki/doku.php?id=technical:dnsresolver
Manually changed list tested on a server.
Update the list, regen dnsmasq conf, check if domain name resolution

[enh] Add IPv6 nameserver to resolv.dnsmasq.conf from diyisp.org

---

src/yunohost/dyndns.py

c.f. https://github.com/YunoHost/issues/issues/1300 - unecessary madness which makes everything slower (dyndns update taking the lock every 2 minutes to do a full HTTPS request for nothing and therefore dynette is bombarded with those and sometimes aint able to answer)
Don't make all those crazy request, not really necessary ... Also add some constrains to try to remove ambiguities
Yolocommited, not tested :|
Try this on a server with a registered nohost.me/noho.st/... Try to subscribe multiple time. Try a case where subscribing failed to see if keys are indeed removed.

[fix] Optimize dyndns requests

---

src/yunohost/app.py

A very simple idea I had since quite some time: allow to add a way in the argument list of an app to have an argument that simply display text and fetch no value as way to allow app packagers to display information for the user.
The usage is very simple, simply had this kind of argument in your manifest:
```json
{
"name": "some_text",
"type": "display_text",
"text": "This is some text that is going to be displayed.\n\nAnother line."
},
```
Working. Need the equivalent for the admin UI once it's agreed on principle.
Create an empty app and had this kind of argument to the manifest and had an empty shell script and run the installation.
Example:

[enh] allow 'display_text' ~fake~ argument in manifest.json

---

data/helpers.d/setting

https://github.com/YunoHost/issues/issues/1299
On an ARM board like RPi2, `yunohost app setting` takes 6\~7 second to complete... Considering that an app usually interacts with 5\~10 settings during an install, you may loose a whole damn minute just getting or setting settings... 
Instead, doing this with a "small" python snippet can divide this time by ~10.
Have a small helper to manipulate the setting yaml files. Turns out it's not straightforward as there are some special cases (c.f. `redirected_urls` and `redirected_regex`) to handle to truly reproduce the `yunohost app setting` behavior.
Partially tested on my machine
Load and use the `ynh_app_setting_{get,set,delete}` in various case ;)

[enh] Optimize app setting helpers

---

data/helpers.d/psql

...
Update psql helper
Tested in local. ~~I spotted a silent error when restore a database from a file `ynh_psql_connect_as $db_name $db_pwd $db_name < ./db.sql` but already present with the old version:
"ERROR:  must be owner of extension plpgsql"~~
I think I've fixed that
...

[enh] Update psql helper

---

src/yunohost/backup.py
src/yunohost/tests/test_backuprestore.py

Backup tests failed for two different reason ...
- a weird edge case about link creation during the backup ... files were actually on different device but there seem to be no way to detect this ... I suspect this is because of running on a weird LXC setup with encrypted hard drive inside some /dev/mapper stuff such that the real "logical" (?) devices are hidden ...
- some changes in the pytest version or idk, such that the way to access function / tests markers broke
Fix those
Tested on my machine
Run the backup/restore tests

Fix backup tests

---

data/templates/nginx/plain/global.conf

c.f. https://github.com/YunoHost/issues/issues/1315
And in particular : 
The reason is that, currently, **text/html is always included in the
gzipped MIME types whatever you do** [1, 2]:
Syntax: gzip_types mime-type ...;
[...]
Enables gzipping of responses for the specified MIME types
in addition to “text/html”.
Disable gzip entirely to protect against BREACH
Not tested but this is a simple change, should be working ...
Uh I guess go on a webpage and check the headers or something

[fix] Disable gzip entirely

---

src/yunohost/backup.py
src/yunohost/tests/test_backuprestore.py

c.f. https://github.com/YunoHost/issues/issues/1308 which sometime breaks upgrade for silly reasons
Implement the 'FIXME' by attempting to unmount / clean the directory.
While fixing this, I realized that the function `_recursive_umount` probably had a buggy behavior / return value ... Dunno if that explains why the original issue happened in the first place, but could be related.
Tested and works okay
```bash
mkdir /var/toto
echo "toto" > /var/toto/toto
cd /home/yunohost.backup/tmp
mkdir yoloswag; cd yoloswag
mkdir toto
mount -o ro,bind /var/toto ./toto
cd
yunohost backup create -n yoloswag --debug
```
Should see in the debug output (at the beginning) that it complains the directory ain't empty and attempts to clean it

[fix] Backup fails because output directory not empty

---

locales/en.json
src/yunohost/app.py

c.f. https://github.com/YunoHost/issues/issues/1319
Reject app passwords that contain { or } ...
Try to install for example lstu_ynh and put { or } in password

[fix] Reject app password if they contains { or }

---

data/helpers.d/user

https://github.com/YunoHost-Apps/wordpress_ynh/issues/57
That's not the first time we have this problem, a group isn't deleted because there's other users in that group.
`delgroup` will remove a group, even if not empty. Also, having it's own condition, running the helper will remove the group even if the user doesn't exist anymore.
~Need to be tested...~ Tested.
...
@YunoHost/apps

[fix] Delete properly group as well as user

---

data/helpers.d/system

https://github.com/YunoHost-Apps/wordpress_ynh/issues/57
For unknown reasons, php7 can be sometime stopped, the reload fails then because the service is not active.
Use reload-or-restart instead of reload, so it would try to reload, and if the service isn't running, it will restart instead.
Not tested, is it really needed ?
...
@YunoHost/apps

[enh] reload-or-restart instead of reload

---

data/helpers.d/getopts

As found by JimboJoe here, https://github.com/YunoHost/yunohost/pull/646#issuecomment-473448470, $ have to be escaped as well as double quotes.
Ready to be review
...
@YunoHost/apps

Escape $ in getopts

---

data/templates/nginx/plain/yunohost_panel.conf.inc

Currently, only ynhpanel.js is injected in app pages which integrate the yunohost portal button / overlay. This JS currently injects the CSS in the page. This is fine but for theme, we now want to inject two more files (the custom CSS and custom JS) ... and thisis a whole mess because those are then loaded ~after~ the inital "DOM loaded" event which makes some stuff harder to implement.
Inject all those file directly, like ynhpanel.js was.
Try to set a custom theme with https://github.com/YunoHost/SSOwat/pull/122

[enh] Nginx conf tweaks for theme

---

data/helpers.d/getopts

Shell characters are not all escaped in `eval` call.
Escape shell metacharacters with a dedicated function.
Alternative to #683.
...
```sh
#!/bin/sh
. ./getopts
function my_helper()
{
declare -Ar args_array=( [a]=arg1= [b]=arg2= [c]=arg3 )
local arg1
local arg2
local arg3
ynh_handle_getopts_args "$@"
echo "Inner"
echo arg1=$arg1
echo arg2=$arg2
echo arg2=$arg3
echo
}
my_helper --arg1 '$toto`ls`' -b "'" -c
```

Avoid having to shell-escape arguments in ynh_handle_getopts_args

---

src/yunohost/app.py

While working on the admin integration I realized that uniformizing the behavior with other key and using "ask" instead of "text" was way simpler for the whole code (despite not making that much sens for "display_text" field) and annex tool (i18n integration for example).
I also added i18n support.
Use this app and try to install it https://github.com/Psycojoker/display_text_ynh

[mod] use ask key for display_text instead and support i18n

---

src/yunohost/service.py

c.f. https://github.com/YunoHost/issues/issues/1316
Very intuitive™, one should use LoadUnit and not GetUnit ...
Tested and working ... though still need to check that this doesnt break webadmin
Try to run `yunohost service status` with a disabled service. Also you can try to add in /etc/yunohost/services.yml a service that doesn't exist at all

[fix] Fix the dbus interface to get info for services

---

data/helpers.d/nodejs

f you install two time the same application, when removing one of them, nodejs is uninstalled
YNH_APP_INSTANCE_NAME instead of YNH_APP_ID
...
...

[fix] Nodejs helpers : use YNH_APP_INSTANCE_NAME instead of YNH_APP_ID

---

data/helpers.d/print

The weight value will take everything after --weight=, especially --time or --last
Fix the regex
...
@YunoHost/apps

[fix] Fix extraction of weight value for ynh_script_progression

---

src/yunohost/app.py

[hook_exec](https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/hook.py#L414) return the code + a json, that was not well handled
Fix this issue
...
...

[FIX] Config Panel

---

src/yunohost/tools.py

Follow the decision about merging community and official into one list.
Use apps.json as the default list.
...
...
**This PR should be merged after https://github.com/YunoHost/apps/pull/694**

Use apps.json as default list

---

data/helpers.d/utils

Actually the path to the app.src file in the helper ynh_setup_source work only in install and upgrade script.
Add the support for restore script by adding a specific path if the general path is not available.
Tested work on monitorix.
Use the helper in a restore script of an app.

Add support in restore script of ynh_setup_source

---

debian/control

Users might remove YunoHost inadvertenly ... c.f. some cases on the forum
I randomly came accross this option in debian packages which allow to mark some package as essential - which is different from "held" package in that you can upgrade the package but not remove it.
For example, try to remove `bash` and it will complain : 
```
The following packages will be REMOVED:
bash bash-completion
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
bash
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 7,186 kB disk space will be freed.
You are about to do something potentially harmful.
To continue type in the phrase 'Yes, do as I say!'
?]
```
Not tested, just doing this quick PR before …

[enh] Mark YunoHost as essential to avoid removing it inadvertenly

---

data/helpers.d/print

I'd like to find a way to announce a long step during an app script, without having to say for all steps (it's going to be long !)
Also, watching the progression bar filling up, I thought it was too bad to know only after the job's done that it was actually a quick or a long step.
Split the progression bar in 3 parts, work done, ongoing work, work not yet done.
A example with leed (which was my testing app).
```
Info: [+...................] > Validating installation parameters...
Info: [#+..................] > Storing installation settings...
Info: [##..................] > Creating a MySQL database...
Info: [##++................] > Setting up source files...
Info: [####+...............] > Configuring nginx web server...
Info: [#####+..............] > Configuring system user...
Info: …
```

[enh] Add the current work to the progression bar

---

data/helpers.d/psql

Sometimes, when dropping a PostgreSQL database, there is still some connections to the database and the database refuses to drop
Force disconnection of all clients to the database
Ready
Don't know

Force disconnection of all clients connected to the database

---

data/helpers.d/filesystem
data/helpers.d/mysql
data/helpers.d/nodejs
data/helpers.d/package
data/helpers.d/psql
data/helpers.d/system
data/helpers.d/user
data/helpers.d/utils

Use printers instead of echo in helpers.
...
...
...
@YunoHost/apps

Use printers in helpers

---

data/templates/postfix/plain/master.cf

If you want to use Sieve filter with subaddress it doesn't work unless you change postfix lda configuration.
This change in /etc/postfix/master.cf will fix the problem
```
-# Dovecot LDA
-dovecot    unix  -       n       n       -       -       pipe
-    flags=DRhu user=vmail:mail argv=/usr/lib/dovecot/deliver -f ${sender} -d ${user}@${nexthop} -m ${extension}
+# Dovecot LDA
+dovecot    unix  -       n       n       -       -       pipe
+    flags=DRhu user=vmail:mail argv=/usr/lib/dovecot/deliver -f ${sender} -d ${user}@${nexthop} -m ${extension} -a ${recipient}
```
Update file /etc/postfix/master.cf to mirrot this line
```
dovecot    unix  -       n       n       -       -       pipe
flags=DRhu user=vmail:mail argv=/usr/lib/dovecot/deliver -f ${sender} -d ${user}@${nexthop} -m …
```

[enh] Specify -a parameter on dovecot lda for Sieve

---

data/templates/slapd/slapd.default

OpenLDAP service open its socket on every network interfaces. This is not usefull as services are only connected to localhost.
Change default OpenLDAP configuration to only bind on localhost.
This command 
```
lsof -i :389 | grep LISTEN
```
should display binding on localhost only
```
slapd    3559 openldap    8u  IPv4 34292432      0t0  TCP localhost:ldap (LISTEN)
slapd    3559 openldap    9u  IPv6 34292433      0t0  TCP localhost:ldap (LISTEN)
```

[enh] Bind OpenLDAP socket on localhost

---

data/hooks/backup/32-conf_cron

`Warning: yunohost.hook <lambda> - [965.1] ls: cannot access '/etc/cron.d/yunohost*': No such file or directory`
Redirect stderr into /dev/null
Do a backup
...

[FIX] Hook backup warning message

---

data/templates/nginx/server.tpl.conf

Unable to use these lines in nginx conf:
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
```
for WebSocket proxying.
I'm not an expert in Nginx but you can find doc here:
http://nginx.org/en/docs/http/websocket.html
What I've done inside the file `server.tpl.conf`
...
Add these lines in nginx conf of an app that use websocket
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
```

[enh] WebSocket proxying

---

data/actionsmap/yunohost.yml
src/yunohost/log.py

Needed for https://github.com/YunoHost/yunohost-admin/pull/241
Add a --with-details option for `yunohost log list`
Run `yunohost log list` and see if there's a `success` key

Add a --with-details option for log list

---

data/hooks/conf_regen/19-postfix
data/templates/postfix/main.cf
locales/en.json
src/yunohost/settings.py

TLSv1 and TLSV1.1 are unsecure protocols.
Remove support for TLSv1 and TLSv1.1 from postfix config
````
yunohost settings set security.postfix.compatibility -v modern
````

[enh] Propose a setting to remove support for TLSv1 and TLSv1.1 in Postfix

---

data/templates/postfix/main.cf

Some server scan on internet each mail server and try to detect the email adress. After the email adress is found some spam are send.
The result is by example this : https://forum.yunohost.org/t/usage-frauduleux-de-ma-boite-mail/7540/4
Block the VRFY command in Postfix wich give the possibility to do that on the server.
Tested and it work. But need to be tested more deeply. By example if it break something.
Enable the option `disable_vrfy_command` in the main postfix config.
Launch this: 
```
220 domain.tld Service ready
VRFY email@domain.tld
502 5.5.1 VRFY command is disabled
```

Disable VRFY command in Postfix command

---

data/helpers.d/fail2ban
data/helpers.d/logging
data/helpers.d/postgresql
data/helpers.d/utils

We forgot to set the minimum version required for helper during the last release.
Set the last version to 3.5.0 for those helpers.

Set min version to 3.5.0 for helpers

---

data/helpers.d/setting

We have lost the documentation about sso config keys
Add helpers to add directly such config keys.
And bring documentation back with those helpers.
...
@YunoHost/apps

Add helpers for sso config

---

data/templates/dnsmasq/plain/resolv.dnsmasq.conf

Previous Unicast IPV6 for censurfridns,dk was out of date
One of the ip listed in the resolv.dnsmasq.conf was dead
I've replaced the IP by the right one taken from https://blog.uncensoreddns.org/
Tested the IP on my yunohost instance and it respond properly
Ping the old IP, it's dead, ping the new one, it answer.

[fix] Update censurfridns ipv6

---

bin/yunohost

> on failed postinstall, yunohost suggest to uses "yunohost log" but it's can't be used since postinstall hasn't run
See https://github.com/YunoHost/issues/issues/1345.
Make a special case inside `bin/yunohost` to allow `log display` command to run.
Closes https://github.com/YunoHost/issues/issues/1345.
Ready for review.
```
root@yunohostdev:/ynh-dev/yunohost# yunohost
Error: YunoHost is not or not correctly installed. Please execute 'yunohost tools postinstall'
root@yunohostdev:/ynh-dev/yunohost# yunohost log display
usage: yunohost log display path [-h] [-n NUMBER] [--share]
yunohost log display: error: too few arguments
root@yunohostdev:/ynh-dev/yunohost# git diff
diff --git a/bin/yunohost b/bin/yunohost
index fd9c2dbf..10a21a9d 100755
--- a/bin/yunohost
+++ b/bin/yunohost
@@ -195,7 …
```

Allow to display logs when postinstall fails

---

data/templates/slapd/slapd.conf

I get lots of suggestion of indexes by slapd in my logs:
<= mdb_equality_candidates: (cn) not indexed
<= mdb_equality_candidates: (gidNumber) not indexed
<= mdb_equality_candidates: (mail) not indexed
<= mdb_equality_candidates: (member) not indexed
<= mdb_equality_candidates: (memberUid) not indexed
<= mdb_equality_candidates: (sudoUser) not indexed
<= mdb_equality_candidates: (uidNumber) not indexed
<= mdb_equality_candidates: (uniqueMember) not indexed
<= mdb_equality_candidates: (virtualdomain) not indexed
<= mdb_substring_candidates: (sudoUser) not indexed
Since Yunohost makes it hard to edit LDAP server configuration (see https://github.com/YunoHost/issues/issues/1350), the default configuration should contain indexes for the fields used by Yunohost a lot.
...
...
...
...

Add indexes for fields listed by slapd in the logs

---

data/helpers.d/mysql
data/helpers.d/postgresql
data/helpers.d/systemd
data/helpers.d/user

`ynh_script_progression` is awesome, but the info logging channel (what the regular user sees) is often kinda polluted with low-level technical messages, typically saying that `service X` is being reloaded...
E.g. :  
```text
$ yunohost app remove wordpress
Info: Removing application wordpress…
Info: [+...................] > Load settings
Info: [#+++++++............] > Remove dependencies
Info: [########+...........] > Remove the mysql database
Info: Removing database wordpress
Info: [#########+..........] > Remove app main directory
Info: [##########..........] > Remove nginx configuration
Info: Reload the service nginx
Info: [##########++........] > Remove php-fpm configuration
Info: /etc/php/7.0/fpm/conf.d/20-wordpress.ini wasn't deleted because it doesn't exist.
Info: Reload the …
```

Remove unecessary log messages

---

src/yunohost/backup.py

https://forum.yunohost.org/t/restore-from-folder-rather-then-tar-gz/7885
https://cybre.space/@aleks/102117385695119433
https://serverfault.com/questions/457480/tar-leading-period-slash
Check for both `info.json` and `./info.json` ... and similarly each time we try to extract a file.
Tested on my side and working
You can reproduce the issue by untaring an archive and retaring it with : 
```
cd thearchive/
tar -zcvf ../buggyarchive.tar.gz ./
```
Then using `yunohost backup info buggyarchive` or trying to restore it.

[fix] Stupid issue with files inside tar : foo is not the same as ./foo

---

data/helpers.d/logging

As reported by @Josue-T, ynh_print_OFF doesn't work when used before a helper using getopts, because the helper getopts use set -x.
Redirect BASH_XTRACEFD, the file descriptor for xtrace, to /dev/null to get rid of the trace.
Then redirect back to stdout.
Tested on leed.
...
@YunoHost/apps

Fix ynh_print_OFF when set -x is used in other helpers

---

src/yunohost/tools.py

The update/upgrade view in yunohost-admin doesn't show what's the current app version and next version
Add current and next version of the apps in `tools_update` output. This is kind of a follow-up of https://github.com/YunoHost/yunohost/pull/730
Install an app (make it so that it's not up to date) and run `yunohost tools update --apps`

[enh] Add current and new version for apps in tools_update output

---

data/helpers.d/backup

Some users were using the setting `backup_only_core` to not backup data during their backup.
As this setting wasn't meant to be used this way, I didn't care when changing the way it was handled.
https://forum.yunohost.org/t/yunohost-backup-create-ko/7688
Implement a new setting `do_not_backup_data` to add to an app setting to avoid data backup.
This setting, as it's not part of the upgrade process, will not be removed by any script. So it could be used by an user to avoid to backup data for all backup script.
Set the setting for an app, `ynh_app_setting_set $app do_not_backup_data 1`
@YunoHost/apps

Add exception for data backup

---

src/yunohost/backup.py

Today a user on the chat pointed out that, when creating backups in a custom output directory (e.g. `/tmp/backups/`) then deleting the backup using `yunohost backup delete`, the .tar.gz file is still in `/tmp/backups/`
That's because `backup_delete()` naively deletes `/home/yunohost.backup/archives/thebackup.tar.gz`, which turns out to exist and is a symlink to the actual archive in `/tmp/backups/`. So the solution is to also delete the target of the symlink (if the path is a symlink).
Tested on my machine and working
```
yunohost backup create foo -o /tmp/backups/
ls /tmp/backups/  # Should display an archive for foo
yunohost backup delete foo
ls /tmp/backups/  # foo shouldn't be there anymore with this fix
```

[fix] Backup delete should delete symlink target

---

debian/control
src/yunohost/app.py

Writting a config_panel in json turns out to be unecessary complicated and error prone.
After looking at a lot of different formats, toml turns out to be the most intuitive one and less error prone to use for not super-turbo-nerdy people which most app devs are (and even for turbo-nerdy writting json by hand sucks). App group people confirmed that it really looks like an improvement other json.
The solution to limit the modification of the code is to transform this new toml format in the current json format internally on load (which is easier to use for code)
Sidenode: I'm considering introducing support for `manifest.toml` and will certainly do `actions.toml` as it also really looks like an improvment: https://gist.github.com/Psycojoker/71aca1767738c4b254b6cd74e09c28e1#file-manifest-toml …

[enh] support config_panel in TOML format

---

data/helpers.d/logging

`ynh_script_progression` is awesome, but it fills the output log with a huge bunch of boring lines related to the computation of the progress bar :[ 
Add some set +x / -x to hide this computation
Tested and working on my machine
Run an app install like wordpress and compare the full output

Use set +x / -x to hide the whole ynh_script_progression computation

---

src/yunohost/data_migrations/0010_migrate_to_apps_json.py

With 3.6.2 my internetcube list was not removed. My internetcube is one of the first installed (installed by kload himself...).
Add the missing list
Ready

[fix] Missing internetcube list

---

debian/control
src/yunohost/app.py

WIP work on this weekend, it depends on the #732 toml PR.
THIS REQUIRES A LITTLE BIT OF CHANGES FOR THE FORMAT OF THE CONFIG PANEL since now it's the manifest/actions format that is used.
The modifications are to this format in the [options] section, so, from head:
- bool -> boolean
- name -> ask
Here is a working (format) config https://gist.github.com/Psycojoker/c9ea335e596c4684b042812b7b0804c3
...
...
...

use manifest.json/actions.json args format for the config_panel.toml

---

src/yunohost/app.py

json is boring to write and we've discovered toml as a better replacement for humans so after doing this for config panel, allow this for actions.
Manifest is next to come.
ALTOUGH.
There is a problem charly.
Debian being debian, python-toml is version 0.9 here, this mean that this kind of super handy shorthand isn't parsed with the version 0.9 (but is with the version 0.10 which is available on pypi):
```toml
description.en = "le anglish"
description.fr = "the frounce"
```
And there is not python-toml version 0.10 in testing or unstable.
This is really annoying.
Ideally I guess we need to ship it ourselves but I really wasn't expecting this additional work.
We can still write things like although:
```toml
[description]
en = "le anglish"
fr = "the frounce"
```
But in subcategories it's a …

[enh] allows actions.toml

---

data/helpers.d/logging
src/yunohost/app.py
src/yunohost/hook.py

That's a pretty technical thing, but the interface between apps and the core for config panel was a bit hackish due to the lack of easy way to transmit data from the app script to the core.
https://github.com/YunoHost/yunohost/pull/526 introduced a new $YNH_STDRETURN pipe (?) which can then be parsed for json. This PR adds a new data type "plain_dict" which is more suited for the usecase of app config scripts and removes the need for the hackish solution :wink: 
Tested and working on my machine
I tested it using leed, replacing the `echo YNH_CONFIG_MAIN_IS_PUBLIC_IS_PUBLIC=false` with `ynh_return YNH_CONFIG_MAIN_IS_PUBLIC_IS_PUBLIC=false` (`ynh_return` being a new helper which simply echoes stuff in $YNH_STDRETURN)

[mod] Proper return interface for app config

---

data/helpers.d/postgresql
src/yunohost/app.py
src/yunohost/log.py

c.f. https://github.com/YunoHost/issues/issues/1363
Note when working on this, I realized that the "python argument" case is already covered, c.f. these : 
https://github.com/YunoHost/yunohost/blob/stretch-testing/src/yunohost/log.py#L224
https://github.com/YunoHost/yunohost/blob/stretch-testing/src/yunohost/user.py#L274
So here's an attempt to redact at least *most* of the sensitive / secret data in the logs. So far I was able to cover : 
- "static" secrets like `/etc/yunohost/mysql`
- secrets provided through the install form (password-type args)
- secrets generated or fetched(!) during the script execution, like mysql db password.
The last item is the least easiest and least "clean" one. It's all built on the way bash logs or not information ... So for example, we are somewhat lucky …

[enh] Redact secrets from logs

---

src/yunohost/log.py

Having seen several situations of users working with logs the fact that logs are truncated by default is absolutely not obvious at all and very confusing, they just don't get it and I got trap myself several times.
Remove the truncating by default as it actually really doesn't served that much purpose.
Test and works.
...

[mod] don't truncate 'yunohost log display' log by default

---

data/other/dpkg-origins
debian/install
debian/postinst
debian/postrm

`dpkg-vendor --query Vendor` returns "debian"
see https://wiki.debian.org/Derivatives/Guidelines#Vendor
Create /etc/dpkg/origins/yunohost and add a symlink on /etc/dpkg/origins/default
Ready (tested by putting file and symlink by hand on a yunohost instance)
...

[enh] Dpkg vendor set to YunoHost

---

src/yunohost/app.py

Following https://github.com/YunoHost/issues/issues/1384#event-2490152235 we stop considering that an app that only has a domain but not (http) path is having an HTTP api.
That might breaks some app (but I'm really expecting not, that looks too much like a bad practice.)
Tested and working for me.
Have some apps, edit the settings of one (`/etc/yunohost/$app/settings.yml`) to remove the path and launch `yunohost app map`.

[mod] BREAKING (but should be fine) apps without path aren't considering using the domain anymore

---

src/yunohost/backup.py

Follow https://github.com/YunoHost/yunohost/pull/585#discussion_r307891952
Tested and it work
- Install an app
- Make a backup of this app
- Remove manually the app (juste leave the data in LDAP)
- Try to restore the backup

Fix variable definition for permission in backup

---

data/hooks/conf_regen/06-slapd
data/templates/slapd/slapd.conf

https://github.com/YunoHost/issues/issues/1379
Implement TLS Certificate : https://www.openldap.org/doc/admin24/tls.html
...
- Apply the patch
- Execute `yunohost tools regen-conf`
- Test using `openssl s_client -connect localhost:636 -showcerts`
Tested with Mastodon LDAP authentication: https://github.com/YunoHost-Apps/mastodon_ynh/pull/165

[enh] Add OpenLDAP TLS support

---

locales/en.json
src/yunohost/log.py

An error is displayed without md_file var
"Le fichier yaml de metadata associé aux logs est corrompu : '{md_file}'"
Use read_yaml moulinette helper to let us know on which file and error of yaml loading is triggered
Ready
...

[fix] Path not displayed in log_corrupted_md_file

---

data/helpers.d/getopts

Getopts fails to parse a value if it's start by -. It's misread as another option in the argument list.
https://github.com/YunoHost-Apps/rainloop_ynh/issues/58
Escape - if it's a value of an option.
Tested on rainloop.
Try an value starting by -.
@YunoHost/apps

[fix] Fix values starting by - in getopts

---

src/yunohost/app.py

Like every other PR, json sucks at writing, toml is better, allow to use toml instead, this time for manifest.
Tested what I could test but that's used a bit everywhere so ... meh :/
Would be really great in a test, bugs will be easy to fix if present.
Also, should we consider this feature to be experimental too?
Here is a `manifest.toml` for reference:
```toml
license = "free"
url = "https://example.com"
multi_instance = true
version = "1.0~ynh1"
packaging_format = 1
services = ["nginx", "php7.0-fpm", "mysql"]
id = "ynhexample"
name = "YunoHost example app"
[requirements]
yunohost = ">= 3.5"
[maintainer]
url = "http://example.com"
name = "John doe"
email = "john.doe@example.com"
[description]
fr = "Exemple de package d'application pour YunoHost."
en = "Example package for YunoHost …
```

Manifest in toml

---

locales/en.json
src/yunohost/app.py

Error message was bad and could provide more information.
List all installed applications.
From:
To:
`yunohost app info doesnt_exists`

[ux] better error message for not installed app

---

src/yunohost/app.py

TypeError: not enough arguments for format string
Add the argument
Ready to merge
Upgrade an app

[Fix] Upgrade: Not enough arguments for format string

---

data/helpers.d/nodejs

1. When installing node js using ynh_install_nodejs on aarch64, it's the x86-64 version of nodejs that is installed
2. N - Node.js version management included in YunoHost is version 2.1.7, one year old
Updating N - Node.js version management version
since N version 3.0.0 aarch64 and arm64 are detected
Done
Have and aarch64 or arm64 YunoHost, install a package that request nodejs like wekan: yunohost app install https://github.com/yalh76/wekan_ynh/tree/2.98 --debug
After the installation, just test someting like: `/opt/node_n/bin/node --version`

[enh] Upgrade n version (also for compatibility with arm64)

---

data/helpers.d/postgresql
locales/en.json
src/yunohost/data_migrations/0011_postgresql_password_to_md5_authentication.py
src/yunohost/data_migrations/0012_postgresql_password_to_md5_authentication.py

PostgreSQL authentication are done using clear text password.
Use an authentication using md-5 hashed password.
This should be transparent for all applications.
...
...

[enh] PostgreSQL password security

---

data/helpers.d/mysql

`ynh_mysql_user_exists` returns 1 or 0 as error code ...  but is used with `if $(ynh_mysql_user_exists)` instead of `if ynh_mysql_user_exists` ... Dunno if that's really troublesome since apparently that never caused any issue, but at least that's unconsistent and confusing ...
Fix it eh
Done, but untested :/ 
...

Fix wrong usage of ynh_mysql_user_exists

---

src/yunohost/hook.py

This is a rewrite of https://github.com/YunoHost/yunohost/pull/535 because there were too many changes ... : 
Python hooks are required for the new diagnosis system modularity / extendability, and more generally if we want to implement some hooks in python for some reason. This could be the case for example of the famous `app ssowatconf` command which should be a classical regen-conf thing but can't be so far because it has too many python calls and json stuff to be implemented in bash.
Split the behavior of the `hook_exec` function depending on the nature of the hook. Python hooks are to be modules loaded by yunohost and expected to have a `main` function.
Create some hook with a main function (e.g. just displaying `hello world`) and call `yunohost hook list …

Python hooks reloaded

---

data/actionsmap/yunohost.yml
src/yunohost/dyndns.py

Some you need to force the update of dyndns to check if the DKIM key is sent and you generally want to be able to have those feature for debugging (--dry-run).
Add:
* `--force` the force update
* `--dry-run` that display the generated dns config that will be send but isn't
Tested and working, quite minor.
Just do a "dyndns update" with the options, simple.

"yunohost dyndns update" "--force" and "--dry-run"

---

data/actionsmap/yunohost.yml

Groups, users api are in plural, but permission no.
rename the route to be coherent
Ready
...

[enh] Rename permission http api route in plural

---

src/yunohost/permission.py

https://github.com/YunoHost/issues/issues/1427
Just consider that if the key `groupPermission` it's equivalent to en empty list. It avoid to do anything when we remove the last permission.
Tested and it work
Just 
```
yunohost user permission clear mail
yunohost user permission add mail -u test toto
yunohost user permission remove mail -u test
yunohost user permission remove mail -u toto
```

Fix permission sychronization

---

.travis.yml
README.md
pytest.ini
setup.cfg
tox.ini

The Travis Ci configuration should match our work on Moulinette.
We copy/pasta it to match here.
Ready to review and merge if we agree that the 1,0000+ flake8 errors can be fixed another time (put in "allowed failures" on Travis for now). I would recommend that we just run [Black](https://github.com/ambv/black) over the source at some point and that will resolve it. For another day, I guess. 
```
$ pip install tox
$ tox
```

Add basic Travis CI configuration

---

locales/en.json
src/yunohost/app.py

Currently we now do some checks that services requested by an app are up and running (and other anomaly checks) before some operations like install and upgrade ...Which is cool, but we can do better : 
- checking *before* and *after* the operations
- check nginx and fail2ban all the time even if not explicitly required by the app, because those are related to regular issues
- combine this with the dpkg check (and in the future we can add other basic sanity checks in that vein)
Rework a few things to implement this
Tested and working using the PR about app unit tests ... Though maybe still need some work because not all tests are implemented and there are still weird issues in the test
Eeeeh using the app unit test, or manually run stuff like app install with nginx down. Or try to install …

[enh] Iteration on sanity / anomaly checks for app operations

---

src/yunohost/app.py
src/yunohost/tests/conftest.py
src/yunohost/tests/test_apps.py

We don't have tests for apps '-'
Implement some ...
Tested on my machine, but still need to implement at least 3 of them
I think I spotted an important issue related to LDAP group permissions related to failed remove, gotta investigate
Run the tests using ynh-dev or pytest manually

[enh] Add unit/functional tests for apps

---

data/helpers.d/backup

If we try to use the helper `ynh_add_fail2ban_config` in the restore script we have a problem with the helper `ynh_backup_if_checksum_is_different` because we have the checksum in the settings but the file is not installed.
Check that the file exist before to calculate the checksum
Tested and it work
- Checkout the branch.
- Try to use the helper `ynh_add_fail2ban_config` in a restore script

Check that  exist before the calculate the checksum

---

data/templates/fail2ban/yunohost-jails.conf

Fail2ban failt count is way too harsh as exposed in https://github.com/YunoHost/issues/issues/1437
Should make it at least 10 instead of 6
Open
Put 10 erroneous passwords in Ynh admin login form over HTTPS port.

change maxretry of fail2ban from 6 to 10

---

src/yunohost/user.py

See https://forum.yunohost.org/t/cant-create-a-user-after-post-intsallation/9190.
https://forum.yunohost.org/t/cant-create-a-user-after-post-intsallation/9190
Use `str`.
Untested.
Do something weird in your `/etc/ssowat/conf.json.persistent` file and see that this error is reported.

Use str instead of strerror

---

data/helpers.d/apt

c.f. [this hell](https://github.com/YunoHost/issues/issues/1407)
Lol just readd the sury repo in the middle of the `install_app_dependency` helper if we detect that sury fucked everything and we need other php deps
Yolo commited without any test, should be tested ...
Install pixelfed then try to install e.g. nextcloud

[fix] Fucking ugly workaround for the goddamn dependency nighmare from sury djeezus kraiste

---

locales/en.json
locales/fr.json
locales/pt.json

Fix https://github.com/YunoHost/issues/issues/1365.
Message more explicit.
Ready. Translated in English, French and Portuguese.
...

Better error message for invalid email domain.

---

debian/control

https://packages.debian.org/stretch/iproute
> This is a transitional dummy package to get upgrading systems to install the iproute2 package. It can safely be removed once no other package depends on it. 
Install iproute2
...
...

iproute2 instead of iproute

---

data/actionsmap/yunohost.yml
src/yunohost/app.py

Imho that's not really used, or does not display relevant information. Most of the time issues are related to installations which is handled by the log system from 3.2. And typically in other cases `app_debug` very rarely display the useful piece of log.
Remove it, kill legacy unused features @_@. This contribute to simplify `yunohost app --help` along with other PRs.
Yolo commited
TODO : remove the corresponding button in the app view in the webadmin
...

Remove app_debug, unused stuff / not really relevant

---

bin/yunohost

Needed for https://github.com/YunoHost/moulinette/pull/205
For some reason logs from core of the moulinette were never displayed at all since 4 years :man_shrugging:

[fix] moulinette logs were never displayed #lol

---

data/helpers.d/network
locales/en.json

- *The actual helper don't catch the use of udp port*
- *Use netstat instead of netcat*
The current way is to try to open this port, if it fail inc the port and try again...
My way just checks if it used, if it is inc the port and try again.
I can add arguments to this helper to force the check in ipv4 or ipv6 if needed (check both by default)
...

[FIX] find udp port

---

src/yunohost/permission.py

"All_user" was not added on the creation of new ".main" permission
- *Fix it!*
- *No need to check `permission.endswith(".main")`: https://github.com/YunoHost/yunohost/blob/67816ad18ec82fe3ffdc234bdd6536844a872582/src/yunohost/app.py#L791*
...
...

[Fix] permission create

---

data/hooks/conf_regen/12-metronome

When adding new domains to Yunohost a directory for each newly added domain is created in `/var/lib/metronome` unfortunately since the directory is created with `sudo mkdir` that means `root:root` owns the directory. Metronome will now fail to write to the directory.
After creating the directory `chown` it.
...
...

[fix] metronome domain folder permissions

---

src/yunohost/tests/test_backuprestore.py

`TypeError: _test_backup_and_restore_app() takes exactly 2 arguments (1 given)`
Add mocker in parameter (is it the right thing to do?)
...
...

[fix] test_backup_and_restore_permission_app

---

data/hooks/conf_regen/25-dovecot
data/templates/dovecot/dovecot.conf
locales/en.json
src/yunohost/app.py
src/yunohost/settings.py
src/yunohost/tests/test_settings.py

Using a non-default configuration is needed to setup pop3.
See https://github.com/YunoHost/issues/issues/1393.
Allow to configure pop3 through a setting.
Following approach in https://github.com/YunoHost/yunohost/pull/773.
```
$ yunohost settings set pop3.enabled -v True
$ yunohost settings set pop3.enabled -v False
```
Then have a look at your `/etc/dovecot/dovecot.conf` and check the "protocols = ..." line.
Also check that `dpkg -l` reports that `dovecot-pop3d` is installed.

Add pop3.enabled setting

---

src/yunohost/utils/ldap.py

c.f. changes in https://github.com/YunoHost/moulinette/pull/216
Propagate the change, use a simple dict instead of a bunch of tuples
Tested and working if you have the right moulinette PR checked out
Try to launch `yunohost tools shell` and check that the `ldap` object if working properly

Propagate change on LDAP conf / authenticator

---

data/actionsmap/yunohost.yml
src/yunohost/app.py
src/yunohost/data_migrations/0011_setup_group_permission.py
src/yunohost/tests/test_appscatalog.py
src/yunohost/tests/test_permission.py
src/yunohost/tools.py

App categoriez bruh, we need them
Also `app_list` and `app_info` are complete madness so fuck these, refactored them. (The main point being the constant confusion between local info and info from the app catalog)
The app category thing can easily be introduced thanks to https://github.com/YunoHost/yunohost/pull/778 . It is based on an evolution of the app list format, available here : https://app.yunohost.org/default/v2/apps.json (c.f. also the PR on the apps repo : https://github.com/YunoHost/apps/pull/828 )
`app_list` and `app_info` got changed a lot : 
- `app_info` returns info about a single installed app.  `--full` can be added to fetch all the info (useful for other part of the code + the admin). The info from the catalog is separated from the local info in an obvious way (there's a …

[enh] Refactor app_list and app_info, + add support for app categories

---

data/helpers.d/setting

The variable `unprotected_url` or `skipped_url` used by all our apps will be deprecated after the 3.7. We don't want kill all our apps after the 3.7 upgrade.
`add` or `remove` `visitors` to mirror what those variables did before 3.7
...
Install an app with a `config` script that can change the `is_public` variable ([leed](https://github.com/YunoHost-Apps/leed_ynh) for example), and play with the config panel/actions to change the value of `is_public`:
```bash
yunohost app action run leed public_private
```
Then check permissions with:
```bash
yunohost user permission list
```

fix legacy permission management

---

data/helpers.d/systemd

Logs speak about started even if the action was stop
using `${action}`
Done
...

adaptation for various actions

---

data/helpers.d/getopts

`echo` may interpret arguments during substitution :
https://paste.yunohost.org/inalofovev.bash
In this example, `--db_name=bar` is replaced by `-n bar` here
https://github.com/YunoHost/yunohost/blob/cd0b0c8892cdd5c25b2a2458806dd4a20dbd088d/data/helpers.d/getopts#L84
and one the next line: 
https://github.com/YunoHost/yunohost/blob/cd0b0c8892cdd5c25b2a2458806dd4a20dbd088d/data/helpers.d/getopts#L86
`echo` see the -n argument.
double quote `${arguments[arg]}`
Con:
Empty arguments is no longer detected as an issue (for example: `ynh_mysql_connect_as --user=root --password=toto --database=`, more info [here](https://github.com/YunoHost/yunohost/pull/885#issuecomment-596228521) on the previous discussion)
...
...

Fix getops again

---

data/helpers.d/utils

Some app installations require the use of multiple API calls through HTTP, keeping cookies along the way. Current `ynh_local_curl` implementation doesn't enable that behavior.
Persist cookies in an app-dedicated `/tmp/ynh_$app_cookie.txt` file, in order to keep cookies for an app, and segregate the different apps installation.
Implemented in Piwigo package [here](https://github.com/YunoHost-Apps/piwigo_ynh/pull/45).
Test manually or via the Piwigo example (the token retrieval wouldn't work without that change).

Persist cookies between multiple ynh_local_curl calls for the same app

---

src/yunohost/permission.py

I'm not sure how / why we didn't catch this earlier, but attempting to add a permission that's already existing leads to catastrophic failure : 
```
$ yunohost user permission update nextcloud.main --add visitors
Attention : Le groupe 'visitors' a déjà l'autorisation 'nextcloud.main' activée
Attention : The permission was also implicitly granted to 'all_users' because it is required to allow the special group 'visitors'
Info : L’opération 'Mise à jour des accès pour la permission 'nextcloud'' a échouée ! Pour obtenir de l’aide, merci de partager le journal de l'opération en utilisant la commande 'yunohost log display 20200315-211915-user_permission_update-nextcloud --share'
Erreur : Impossible de mettre à jour la permission 'nextcloud.main': Une erreur est survenue lors de l’opération …
```

[fix] Make sure the group permission update contains unique elements

---

data/hooks/diagnosis/14-ports.py
data/hooks/diagnosis/16-http.py

If the diagnosis.yunohost.org server crashes (omg, this NEVER happens ;-)), we're getting a strange error message like: "Impossible to parse json blablabla"
Manage whether the answer is correct or not
...
...

[FIX] Diagnosis bad response from the server

---

src/yunohost/settings.py
src/yunohost/tests/test_apps.py
src/yunohost/tests/test_appscatalog.py
src/yunohost/tests/test_permission.py

- Some unit test fail (settings and app catalog)
- It's sometime really complicated to pass all test because of bad DNS registry and dirty app cleanup
- Fix the settings implementation
- Fix the app catalog test
- Improve the app cleanup after each tests
- Force the DNS to make all request locally
Now all test pass
Note that this PR also depends on https://github.com/YunoHost/moulinette/pull/231 to fix everything.
Just launch the unit test (with `./ynh-dev test yunohost`)

Fix unit test and improve test stability

---

data/helpers.d/postgresql

Sometime postgresql can't be removed with this message:
> dropdb: database removal failed: ERROR:  database "thedb" is being accessed by other usersWarning: 
DETAIL:  There is 1 other session using the database.
https://stackoverflow.com/questions/5408156/how-to-drop-a-postgresql-database-if-there-are-active-connections-to-it
Revoke before dumb the db.
Done
You can install an app which use a psql db, install pgadmin, look the db with pgadmin and remove the app which use psql at the same time.

Revoke before drop

---

data/hooks/conf_regen/12-metronome
data/hooks/conf_regen/15-nginx
data/templates/metronome/metronome.cfg.lua
data/templates/nginx/security.conf.inc
data/templates/nginx/server.tpl.conf
data/templates/ssl/openssl.cnf
locales/en.json
src/yunohost/certificate.py
src/yunohost/domain.py

Sharing files with XMPP's http upload mechanism is currently impossible.
This PR is an attempt to address issue [#1278](https://github.com/YunoHost/issues/issues/1278 )
Metronome's configuration is ready for http upload but port 5290 is not reachable.
http upload requires a dedicated subdomain (I have chosen *jabber.thedomain.net* instead of upload.thedomain.net to avoid possible conflicts with possible other "upload" things).
This subdomain should be reachable via HTTPS so we need:
The PR ready for review.
Create 2 accounts : alice and bob
Install Dino and configure those accounts.
Happily share pictures between alice and bob.

XMPP http upload

---

data/helpers.d/network

ynh_find_port returns false positive for port already used since we changed it to use `ss`.
This is the reason why so many apps are in regression on Buster (and in fact, Stretch Unstable too) and stuck on level 6 : https://dash.yunohost.org/appci/compare/stable...buster (well, "only" seven apps in fact)
The reason is that `grep -w` wants an exact match, but there's actually a star `*` in front of the string ...
Maybe we also want to make sure the line contains LISTEN and tcp, but I don't really know much. Anyway it's better to have false-negatives than false-positives.
Should be working ... tested the `ss | grep`, but not the helper itself...
Use `ynh_find_port` on an already used port, like for example the xmpp port 5222

Fix ynh_find_port

---

src/yunohost/app.py

Error after apply config because [webadmin needs](https://github.com/YunoHost/yunohost-admin/blob/79301a80836d92d30a96eb62938fc8f3d341b77d/src/js/yunohost/controllers/apps.js#L366) `app`
Add `app` as return value
...
...

[fix] config_appy return link

---

debian/control

c.f. discussion on Yunohost apps, some app requires php-uploadprogress with has a "recommend libapache2-whatever which in turns install apache.
But we've seen many situations leading to apache or bind9 being installed which breaks critical services like nginx and dnsmasq...
Bringing this once again because we really need to do something about it on the long term.
It's been discussed that some advanced user may want to install apache2 on the side, but fuck it, if they need it they can still force it using some `dpkg --force-conflicts` somehow.
Yolocommited
Try to install apache or bind with this rule enabled..

Add conflict rule against apache2 and bind9

---

data/hooks/diagnosis/12-dnsrecords.py
src/yunohost/domain.py
src/yunohost/dyndns.py

For each domain, currently, we generate a DNS record recommendation that include basic A/AAAA records + mail-related records + xmpp-related records. This makes a lot of sense for regular "root" domain like example.com or yolo.nohost.me. But if you add many app-dedicated domains like $app.example.com, you generally expect to only be relevant for web and not have a full mail stack + xmpp stack configured for each of those ... 
The right answer to this imho is to allow admins to only enable specific features like web/mail/xmpp for each domain they add (and by default not recommending to add mail/xmpp for subdomains). But that require some work that'll only come after Buster
Currently though, the diagnosis diagnose every DNS records for every domain. A simple trick to reduce this madness is …

Dont diagnose all records for subdomains

---

src/yunohost/tools.py

Fixes https://github.com/YunoHost/issues/issues/1479: 
yunohost was using the exact same Distinguished Name for
the CA certificate and the main domain server certificate. When creating
alternate domain name, firefox thought the CA for this second domain was
the server certificate for the first domain. As the key mismatches,
Firefox raised a bad key usage error, which is not bypassable.
To fix this, we "simply" need to make sure the DN for the CA is
distinct for any other DN. I did so by adding a Organization to it, and
I decided to just remove the last part of the domain and use that as an
organization name. It is certainly possible to do something else, as
long as we end up having a distinct DN. So yolo.test gives a yolo
organization for instance.
More info here …

[fix] prevent firefox to mix CA and server certificate

---

data/helpers.d/utils

In this new change to persist cookie between curl calls, I believe we're opening a possible security issue : the cookie file is written in tmp and ends up being readable by every other on the system, which could possibly be used to steal credentials.
Enforce file permissions
Yolocommited
Try to use the helper, check if it's readable by a non-root user

Fix possible security issue with these cookie files

---

data/helpers.d/setting

c.f. the discussion [here](https://github.com/YunoHost-Apps/hextris_ynh/pull/13#discussion_r400277294)
The migration procedure is complex because of the fact that removing skipped/unprotected uri will also affect the permission (because of another hack, c.f. the diff)
Only apply the hack during unprotected/skipped deletion if is_public is not empty. This way this should not affect what we do in other contexts, and we can simplify the migration procedure to something like : 
```bash
if [ -n "$is_public" ]; then
ynh_app_setting_delete --app=$app --key=is_public
ynh_app_setting_delete --app=$app --key=skipped_uris
fi
```
Yolocommited, not tested...
c.f. what's done in hextris...

Attempt to simplify permission migration

---

src/yunohost/user.py

We randomly pick a uid for the new user and we test it this UID exist.
The problem is that the uid is a string and the list already existing uid and guid in which we test if it exists are stored in it thus the comparison will always fail.
Transform everything into strings.
...
Randomly create users to see that it won't be a problem if you really wants to.

[fix] uid will be tested as a string

---

data/templates/dovecot/dovecot.conf
data/templates/postfix/main.cf

Configurations are not up to date with Mozilla's recommendation ...
Apply recommendation
For dovecot that sounds pretty legit and okay ... For postfix, I'm less confident about what I'm doing ... in particular because there's no recommendation for the `smtp_` settings, which I believe define what happens for the interaction with other servers
Yolocommited :s 
Uh try to configure an email client and submit some mails to deliver to external servers

Update mailstack ciphers

---

data/templates/nginx/security.conf.inc
data/templates/nginx/server.tpl.conf

Nginx ciphers and other security settings not up to date with Mozilla's recommendation (in particular w.r.t. using TLSv1 and 1.1)
c.f. https://ssl-config.mozilla.org/#server=nginx&version=1.10.3&config=intermediate&openssl=1.1.1l&ocsp=false&guideline=5.4
Though we can't have any "modern" configuration with 1.10.3... (lack supports for TLS1.3 I believe) Need buster to have nginx 1.14...
Yolocommited, hopefully not breaking everything
Regen nginx conf, clear browser cache and test that it works.

Update nginx SSL conf with new Mozilla recommendation

---

data/hooks/conf_regen/15-nginx
data/templates/nginx/plain/acme-challenge.conf.inc
data/templates/nginx/server.tpl.conf
locales/en.json
src/yunohost/certificate.py

c.f. https://forum.yunohost.org/t/audit-nginx-avec-gixy/10797
The current acme-challenge location should in fact end with `/` according to the current code ... but it wasn't the case in the past. And for some reason the code didn't overwrite the file if it was already there (and it's not called during renew either)... Anyway 
The code dates back from my very early days in Yunohost where I wasn't aware of the regenconf system. Instead, we should just include a common snippet and include it in all nginx confs.
Though when doing so, we have to take care of legacy (sigh) and make sure the nginx conf is indeed really updated before getting rid of the old file.
Yolocommited, not tested
Setup a domain with letsencrypt (or maybe just manually add the old 000-acmechallenge.conf, no need to …

Get rid of domain-specific acme-challenge snippet, use a single snippet included in every conf

---

data/helpers.d/nginx
data/helpers.d/php
src/yunohost/app.py

Php version will change for buster, and so on for next debian release.
Following https://github.com/YunoHost/yunohost/pull/879, prepare the migration by not using a fixed version of php into apps, but the default version set by $YNH_DEFAULT_PHP_VERSION 
...
...

Pave the way to migration to php7.3 and following

---

data/helpers.d/hardware
data/helpers.d/php

Here's me being again obsessed with semantics ¯\\\_\(ツ)\_/¯
In particular proposing to:
- split `ynh_check_ram` into `ynh_get_ram` (to get RAM infos) and `ynh_require_ram` (which uses `ynh_get_ram` to check that a specific RAM info is larger than a requirement)
- make it explicit wether we're interested in the total amount of RAM, or the free amount of RAM ... both not to be mistaken with the "available" amount of RAM which to me is a third different info (c.f. `free -h`)

Semantic improvements for PHP helpers PR (in particular RAM helper)

---

data/hooks/conf_regen/06-slapd
data/templates/slapd/systemd-override.conf

As experience several times on our infra, slapd is likely to get killed by OOM reaper when system runs out of memory, which is catastrophic as it handles all auth requests except for root. So slapd killed = admin locked out (apart from ssh root@ on local network or direct access)
- Add some overrides to the systemd configuration such that : 
- We adjust the OOM score to decrease the likelihood of slapd getting killed (this is in fact the case for other critical services like sshd, but for some reason not for slapd...)
- Even if slapd gets killed, it should automatically restart instead of being reported as "active (exited)" by systemd as if everything was fine. This is done with `RemainAfterExit=no` and `Restart=always`
Tested on my side and working
- Pull the branch
- `cat /proc/$(pgrep …

Improve systemd settings for slapd

---

data/helpers.d/php

https://forum.yunohost.org/t/official-app-nextcloud/9223/113
It appears that `max_children / 8` create not enough `min_spare_servers` for an heavy app like nextcloud to be reactive if not currently used.
At the same time, for an app like leed, with no `min_spare_servers` when idle, it start without any trouble.
Divide by 8 for a low footprint. By 5 for a medium and 3 for a high footprint app.
That way, for heavy app, we keep more children running at any time to not slow down too much the app when solicitated.
Not tested, but not sure we really need to.
Can be reviewed.
...
@YunoHost/apps

More min_spare_servers for heavy apps

---

data/templates/nginx/plain/yunohost_panel.conf.inc

https://github.com/YunoHost-Apps/gitlab_ynh/issues/105
After login, we are redirected on https://domain.tld/ynhtheme/custom_portal.js instead of https://domain.tld/
Add `ynhtheme/custom_portal.js|ynhtheme/custom_overlay.css` inside the yunohost_panel.conf.inc file
...
...

[fix] custom_portal and custom_overlay redirect

---

data/helpers.d/php

For some use case, an admin may want to force the limit for the number of max_children for php.
For example, an instance of nextcloud alone on a server with a big load.
The only way for now to do that is to overwrite the config file manually.
Allow a config key `php_forced_max_children` into the settings.yml to overcome the limit.
This settings has as purpose to be included into a config_panel, along with other php paramaters.
I'll do it later, probably with nextcloud first.
Ready to be reviewed
...
@YunoHost/apps

Allow to overwrite pm.max_children

---

data/helpers.d/php

An app could override this variable. 
Set `YNH_DEFAULT_PHP_VERSION` to read-only. Not tested, however. Should I do it?
...
...

YNH_DEFAULT_PHP_VERSION is now readonly

---

data/helpers.d/getopts

Getopts "bugs" if you do something like `my_helper --param1="value1" `
Notice the trailing space at the end.
This will be interpreted as a another value for the first parameter. So you will have `param1="value1;"`
Not a big problem, but it can be, and actually it may fail apt with a "php7.0;-fpm"
To not add a trailing space is an obvious solution, but not enough in case of optional parameter added by a script.
So, ignore empty parameters.
Tested and working as expected.
Should be merge as soon as possible as it breaks the current php helpers with nextcloud.
...
@YunoHost/apps

Fix getopts with empty parameters

---

data/templates/postfix/main.cf

Previous change in postfix ciphers actually broke the entire TLS stuff ... 
```
$ grep "TLS library problem" mail.warn
warning: TLS library problem: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../ssl/record/rec_layer_s3.c:1407:SSL alert number 40:
```
(you gotta send emails to other servers to reproduce this)
which results in TLS handshake failing, and servers falling back to plaintext as far as I understand. 
I was able to pinpoint the issue to the custom cipher list ... I believe they assume that a DH parameter is available, which isn't the case until we fix https://github.com/YunoHost/issues/issues/93 ... (which could in fact being solved by running a 1-minute cronjob once but anyway...)
Digging [postfix's …

Fix postfix ciphers

---

src/yunohost/app.py

c.f. https://github.com/YunoHost/issues/issues/1549
The root cause of this issue is that we use logger.exception instead of logger.error in app.py (in particular during app installs). Logger.exception is meant to display the stacktrace of some unknown / unexpected exception ... But here it's some sort of "expected" exception where we have a ~clear idea of what we're catching and what to do. So we meant to use logger.error instead (it was me that refactored this code a few months ago and didn't know the difference)
The reason why it displayed that "KeyError" is, in my understanding, because it tries to fetch the latest exception. But since there's none when the app fails (because we only check the return code of the system call) it just use some completely unrelated exception. In fact, …

[fix] Stupid "KeyError: label" weird error due to improper use of logger.exception in app.py

---

bin/yunohost
bin/yunohost-api
src/yunohost/__init__.py

Continuation of https://github.com/YunoHost/yunohost/pull/922 to : 
- try to clean the mess happening in bin/yunohost and bin/yunohost-api
- have a way for people to easily write scripts that call yunohost functions (well i don't even know if that's a good idea in terms of avoiding people to break their own server...)
Factorize some stuff into src/yunohost/__init__.py ...hopefully improving the readability of bin/yunohost and bin/yunohost-api ... (well that huge wall of json to configure logging is still a pain but can't easily be simplified...)
Regarding the possibility to write scripts, for now it looks something like : 
```python
import sys
sys.path.insert(0, "/usr/lib/moulinette/")
import yunohost
yunohost.init_logging() # possibly set debug=True if needed, but when writing script …
```

[wip] YunoHost "as a python lib" ? Move moulinette initialization and other stuff to src/yunohost/__init__.py
