lib/yunohost/app.py

Fixes https://github.com/YunoHost/moulinette-yunohost/issues/68

[fix] Fix skipped_urls for each domain and #68

---

src/yunohost/dyndns.py

NOT TESTED (I don't have a dev environnement) but since the current code is not working and this looks like the code around this should in the worst case not break more things.

Unreferenced variables

---

src/yunohost/app.py

It allows me to solve https://dev.yunohost.org/issues/41 in YunoHost/yunohost-admin

[enh] Get app label for installed app in app list.

---

data/templates/nginx/yunohost_admin.conf.inc

Backported from https://github.com/YunoHost/yunohost-config-nginx/pull/5

[enh] Short cache on handlebars templates

---

data/hooks/conf_regen/34-mysql

Hi here,
Just one less pipe :)
Cheers

hooks: Use a more elegant grep command for mysql process check

---

data/actionsmap/yunohost.yml
src/yunohost/domain.py

Actually, this command being so stupidly simple, it could be backported to testing.
I have no idea on how I'm supposed to handle DKIM (it is supposed to be integrated now but I don't know where/how).

New command to generate DNS configuration for a given domain name

---

data/actionsmap/yunohost.yml
locales/en.json
src/yunohost/tools.py

Current output is documented here https://dev.yunohost.org/issues/39#note-3 (and will be updated according to futur code changes)

Diagnostic

---

src/yunohost/app.py
src/yunohost/backup.py
src/yunohost/hook.py

Rebase of https://github.com/YunoHost/yunohost/pull/133.

Set environment variables for each app script

---

src/yunohost/app.py

Hello,
Currently `app_tmp_folder` is a global variable that is modified during app related process (install, upgrade) here https://github.com/YunoHost/yunohost/compare/fix_435_340_326_maybe_311?expand=1#diff-c98834a0df97adaa917878824a06b38fL1174
This doesn't create any problem in CLI because once the command is finished, the program ends and at a new run the variable will be reseted.
But on the web interface, execpt if you restart the moulinette, this variable is still modified and you end up with those kind of errors:
CalledProcessError: Command '['wget', '-qO', '/var/cache/yunohost/from_file/opensondage_ynh-0af12d46ca521ccd0e652901e1462578bc27f9b9/zerobin_ynh-6819a3e219ad3204b75551c3debda2390b483103/zerobin_ynh-6819a3e219ad3204b75551c3debda2390b483103.zip', …

[fix] modifying a global variable was breaking apps installation on yunohost-api because the global modification was persistent

---

data/actionsmap/yunohost.yml
src/yunohost/app.py

[opening a PR for all branches that doesn't have one]
Hello,
Small decision for this small dev feature.

Install no remove on fail option

---

locales/en.json
src/yunohost/certificate.py

Fixes https://dev.yunohost.org/issues/652

[fix] Fix name of self-CA in certificate manager

---

src/yunohost/app.py

Attempt to fix https://dev.yunohost.org/issues/655
ping @maniackcrudelis could you test and confirm that this works for you plz?
I've done a minimal solution, this part of the code should be cleaned a bit more.

[fix] don't remove trailing char if it's not a slash

---

bin/yunohost

This PR is needed for https://github.com/YunoHost/moulinette/pull/129

remove timeout from cli interface

---

data/templates/fail2ban/jail.conf

We're intended to a general public, after all ;)

[enh] Increase fail2ban maxretry on user login, narrow nginx log files

---

data/templates/unattended/02periodic

( Note that this file is not used by YNH, but at least we should have a proper syntax ;p )

[fix] Unattended upgrades configuration syntax.

---

data/helpers.d/user

Helpers pour créer un utilisateur système et pour le supprimer.
La création d'user système permettra de créer des users dédiés aux applications. Cf YEP 3.4

 Nouveaux helpers ynh_system_user_create et ynh_system_user_delete

---

data/helpers.d/network

Nouveau helper pour trouver un port libre.
Déclinaison du code classique avec une vérification préalable de l'argument.

Nouveau helper ynh_find_port

---

locales/en.json
src/yunohost/tools.py

Attempt to address https://dev.yunohost.org/issues/341, based on https://github.com/labriqueinternet/doctorcube_ynh/pull/9
Still need to think about this and do some tests ... Not entirely sure what to do with /etc/hosts and implications.

[enh] Set main domain as hostname

---

data/actionsmap/yunohost.yml
src/yunohost/app.py

This need to be rebased.
This is following a ticket on redmine asking to clean this part of the code. This is a first attemp, I think we can improve it more.
I'm not calling for a decision yet.

[mod] try to clean a bit app_list code

---

data/helpers.d/system

Helpers to implemente trap and set -eu.
Simply to use, you only add `ynh_check_error` in your script.

[enh] New helper ynh_abort_if_errors

---

data/helpers.d/backend

Add and remove logrotate config

[enh] New helpers for logrotate

---

data/helpers.d/string

Sed abstraction, and a way to use something other than sed.
I added also an escape of the delimiter used by sed, to prevent a fail in this case.

New helper ynh_replace_string

---

data/helpers.d/utils

Just an abstraction around curl command.
To prevent forgot arguments and simplify this difficult command.

New helper ynh_local_curl

---

data/helpers.d/package

Related to : https://dev.yunohost.org/issues/876

[fix] Avoid to remove a apt package accidentally

---

locales/en.json

Fix: https://dev.yunohost.org/issues/895

 new text proposal "appslist_retrieve_bad_format"

---

src/yunohost/app.py

Fixes https://dev.yunohost.org/issues/892 (All yunohost instances update their appslist at midnight precisely)

[fix] Add random delay to app fetchlist cron job

---

data/helpers.d/utils

- Allow to use this helper without any POST data
- Keep curl more quiet

[enh] Fix curl helper without POST data

---

src/yunohost/hook.py

Related issue: https://dev.yunohost.org/issues/889
I am not sure about the Name of this environment variable.
This var will authorized to change current dir in hook exec (app script, hook, ...).

[enh] Add execution dir in env on hook exec

---

data/helpers.d/utils

Following this discussion: https://github.com/YunoHost/yunohost/pull/282#issuecomment-299637999
(not tested)

[fix] ynh_setup_source: use YNH_CWD instead of YNH_EXECUTION_DIR

---

data/helpers.d/mysql

Helpers pour créer une base de donnée, son utilisateur et un mot de passe.
Et son pendant pour la supprimer.

Nouveaux helpers ynh_mysql_generate_db et ynh_mysql_remove_db

---

data/templates/postfix/main.cf

https://dev.yunohost.org/issues/914

[enh] Increase message size. #914

---

data/helpers.d/package

[fix] ynh_install_app_dependencies uses grep instead of python

---

src/yunohost/app.py

Follow-up of discussions in #235, and fixes https://dev.yunohost.org/issues/909
One possible cause for app install failure is that the installation domain/path is not available. However, this could be checked before even starting the app installation to avoid half-installing the calling remove script simply because domain/path is not available. We already do this for the "domain" field (however here it's a bit complicated because this concerns two fields).
Also related : the formatting of the path argument is not standard (depends of what the user feels like this day).
I added the check at the end of the function which fetches arguments from the manifest. The check is done only if there's one manifest argument with "domain" type and only one with "path" type, to work around edge cases of …

[enh] Check that domain/path is available (and normalize path) before app install

---

data/actionsmap/yunohost.yml

This should be merged after https://github.com/YunoHost/moulinette/pull/151 :wink:

[enh] Simpler lock system

---

data/actionsmap/yunohost.yml
locales/en.json
src/yunohost/domain.py

Small list of refactoring and cleaning, should be read commit by commit has I've tried to cut the process.
I have test it, seems fine.
This is normally quite simple and small and could be merge pretty fast if not bugs arise or requests for modifications.

Clean domains.py

---

data/helpers.d/setting

Fixes https://dev.yunohost.org/issues/485

[fix] Alow dash at the beginning of app settings

---

locales/en.json

Could be merged as a micro-decision 😉

Fix #1005 (add missing 'ask_path' key)

---

data/helpers.d/string

Just a little error.
Can be merged quickly.

[fix] match_string: unbound variable

---

src/yunohost/vendor/acme_tiny/acme_tiny.py

- fix https://dev.yunohost.org/issues/1007
- Renewing a certificate is not problematic, but creating a certificate for a new domain name may failed according to recent feedbacks.
~~Import sources as a subtree to ease future cases like this one with a [simple `git subtree pull`](https://github.com/duniter/duniter/issues/466#issuecomment-243899393).~~
---
~~@Psycojoker, sorry, it remove pep8 fixes. But now, they can be done upstream and retrieved then.~~

[Fix LE] Update acme-tiny as LE updated its ToS

---

src/yunohost/app.py

This is to solve this issue https://github.com/YunoHost/yunohost-admin/pull/174/files#diff-fc7930fbd3008960d765ff06d5334e63R52
Tested.
This is really small to I'm moving this to a micro decision too and will merge in some days.

[enh] make change_url possibility available on the API for the admin

---

src/yunohost/tools.py

This will provide more information for easier debugging and it's easy to code. Solve this https://dev.yunohost.org/issues/772

[enh] display regen-conf in private diagnosis

---

data/templates/nginx/plain/yunohost_admin.conf.inc

Private issue https://dev.yunohost.org/issues/1037
Change the nginx configuration to avoid the nginx bug
Need review
See comments in the redmine ticket

Fix 1037 nginx traversal

---

data/templates/nginx/plain/global.conf

Resolves https://dev.yunohost.org/issues/960

[enh] enable gzip compression for common text mimetypes in Nginx

---

data/actionsmap/yunohost.yml
src/yunohost/user.py

Extracted from https://github.com/YunoHost/yunohost/pull/345 to allow smoother merging since this part made consensus.

Add commands to allow/disallow a yunohost user to connect in ssh

---

data/helpers.d/backend
data/helpers.d/filesystem
data/helpers.d/ip
data/helpers.d/mysql
data/helpers.d/package
data/helpers.d/print
data/helpers.d/system

Misc weird stuff in helpers.yunohost.org auto-generated doc because 
Misc adjustments here and there, this should be only comments changes
To be reviewed ... maybe we could also add some stuff to not list "internal" commands, to be discussed.
Uh, run [helpersdoc](https://github.com/YunoHost/helpersdoc) locally ¯\\\_(ツ)\_/¯

Misc fixes in the helpers to clean the autodoc

---

src/yunohost/service.py

Code is hard to read.
Refactor it.
Ready to be merged.
Run `yunohost service log $service` ("nginx" for example).
Microdecision, waiting a bit.

[mod] refactor service_log to make is readable

---

src/yunohost/service.py

Microdecision, waiting a bit in case of.
If you want to review look for a "per commit" basis, all of those are atomic.
I've added a bunch on debug logging to avoid hiding some errors, we might get reports from users due to that.

bunch of cleaning in services.py

---

data/helpers.d/package

Apt fails but does not log the reason why it fails
Die quiet ! Die !!!
Tested right now on our stretch CI.
...

[enh] We need a fucking log

---

data/helpers.d/psql

I pull request just for memo and to signal this work (it was in my _common.sh file for packaging...).
The work is unfinished. The api is similar to ynh_mysql helpers.

[enh] Add postgresql helpers

---

src/yunohost/service.py

Yolo logic as removed, code except it.
Reput it, yolo.
Micro decision.

[fix] redo yolo logic in case file doesn't exist

---

debian/changelog
debian/control

https://forum.yunohost.org/t/jessie-users-please-dont-run-upgrades-right-now/5086
Mark dns-root-data as conflicting
Ready

[fix] Mark dns-root-data as conflicting with ynh

---

debian/changelog
debian/control

https://forum.yunohost.org/t/jessie-users-please-dont-run-upgrades-right-now/5086

[fix] Conflict with a specific version of dns-root-data

---

src/yunohost/app.py

Micro decision, needed for the actions on the admin interface.

[mod] information needed for the admin UI

---

locales/en.json
src/yunohost/tools.py

We don't tell the admin to had the first user while it's needed.
Do it
Do a post-install.
Micro decision I guess? Waiting for potential feedback.

[enh] after postinstall tell admin to had its first user

---

data/hooks/backup/17-data_home

Sometimes i don't want to backup data of a user (typically user dedicated to backup data from others server).
A file in the home dir of the user
Ready
...

[enh] Don't backp user home with .nobackup file

---

data/helpers.d/print

Add many simple helper to use easily the different outputs.

Add many print helpers

---

data/hooks/backup/17-data_home

Some unwanted backslash have been introduce by me in backup hook
Remove them
Ready
...
Micro decision

[fix] Error due to unwanted backslash !

---

src/yunohost/domain.py
src/yunohost/dyndns.py

enh https://github.com/YunoHost/issues/issues/1153

[enh] integrate CAA DNS entry into "yunohost domain dns-conf"

---

data/templates/nginx/plain/yunohost_admin.conf
data/templates/nginx/server.tpl.conf

- Problem during test because of this. I got /etc/nginx/conf.d/conf.d/...
- Set a real path
Tested. Micro-decision.
- Perhaps add gixy tool in core

[enh] Set Path as full-path

---

src/yunohost/user.py

Error on missing var
Rename the var with the correct name
Ready

[fix] Unknown variable password in user_update

---

src/yunohost/user.py

Missing import

---

src/yunohost/certificate.py

Sometime, user needs to uses the option `--no-checks` while installing new LE certificates because of their configuration, but this option is not put inside the crontab file thus the renew will never work and they'll either have to modify the cronfile by hand and do a renew by hand with `--no-checks`.
Should we propagate that to the "renew" command to?
Add `--no-checks` inside the cronfile if it's used in the command line.
Done but untested (I don't have the setup for that :().
Have a instance where you can test this PR and run "cert-install" with "--no-checks" and check the cronfile.

[fix] propagate --no-checks cert-install option to renew crontab

---

src/yunohost/app.py

Ref : [https://github.com/YunoHost/yunohost/pull/605](https://github.com/YunoHost/yunohost/pull/605) -> Maybe you can close the orriginal pull request @alexAubin ?
Please check if you are no regression. It works for me with url of project : https://framagit.org/Mickael-Martin/zabbix_ynh or url of branch : https://framagit.org/Mickael-Martin/zabbix_ynh/tree/testing
Cannot import Gitlab (an other gitlab based solutions) project branch.
Use correct git syntax with correct url
Tested with Debian GNU/Linux 9
...
test with many apps repo (github/gitlab/framagit/etc.)
--

[enh] Change git clone for gitlab working with branch

---

data/helpers.d/getopts

ynh_handle_getopts_args has some bugs
Fix ynh_handle_getopts_args from https://github.com/YunoHost/yunohost/pull/561
- https://github.com/YunoHost/yunohost/commit/2094557e1e32f7b8d56406d4229fcd8e1f04f1fd
- https://github.com/YunoHost/yunohost/commit/976f160afbf34be27b04cd0bc1dc13870d642848
- https://github.com/YunoHost/yunohost/commit/50f3291ea7eebb7edc229229f45ce4a5cf66fd1c
- https://github.com/YunoHost/yunohost/commit/540291a7e072dde610d80e45ec70496d9e2e58e6
Ready to be reviewed

[fix] Update ynh_handle_getopts_args

---

data/templates/dnsmasq/plain/resolv.dnsmasq.conf

Some DNS resolvers are not working or IP changed : 
- Aquilenet IP changed
- New AS250 entry
- IP changed for Gozmail and CCC Berlin
Update the list
Not tested but meh
Update the list, regen dnsmasq conf, check if domain name resolution

[fix] Update DNS resolver list according to diyisp.org

---

locales/en.json

Unknown setting leads to erroneous message.
Fix message
...
...

Fix filename in error message

---

data/helpers.d/psql

The psql remove database helper fail with several message
Remove small error in db exist test
Ready
...

[fix] ynh_psql_remove_db fail

---

src/yunohost/backup.py

This PR is used by: https://github.com/YunoHost/yunohost-admin/pull/236
Add the size of each app
...
...

Add size of apps in backup_info result

---

src/yunohost/app.py

Fix https://github.com/YunoHost/issues/issues/1349
This PR have to be merged with: https://github.com/YunoHost/yunohost-admin/pull/246
...
...

[fix] current version in app_info

---

src/yunohost/certificate.py
src/yunohost/vendor/acme_tiny/acme_tiny.py

`acme_tiny.py`'s last update in YunoHost was from August 28th, 2017 using upstream commit 7ef9164 
Since then there seem to have been various improvement / update (ACMEv2 support, and bad nonce retries) : https://github.com/diafygi/acme-tiny/releases
Update acme_tiny.py to release 4.0.4 (+ repropagate YunoHost's patch about `no_checks`)
Not tested yet
Try to install a certificate with this new version ?

[enh] Update acmetiny.py to 4.0.4

---

locales/en.json
src/yunohost/tools.py

Some silent exception removal.

[mod] remove silent exception in toos_update

---

src/yunohost/app.py

Those aren't in the operation logger because it has been written after, let's put them in it to make debugging easier.
Logs are returned but unused for now.
Should be fine and it's experimental.

[enh] integrate actions/config-panel into operation_logs

---

README.md

Also found out about this cool summary of translation which imho is better to show than the old squary widget ¯\\\_(ツ)\_/¯
https://translate.yunohost.org/widgets/yunohost/-/multi-auto.svg

Small cleaning and update of the README.md

---

src/yunohost/log.py

https://github.com/YunoHost-Apps/bitwarden_ynh/issues/3
A lot of apps use also `token` https://github.com/search?q=org%3AYunoHost-Apps+token&type=Code
Adding token in the match stuff
Done
...

adding token to not be logged

---

README.md

Language reworked

---

src/yunohost/permission.py

https://github.com/YunoHost/issues/issues/1483
Fix https://github.com/YunoHost/issues/issues/1483
...
...

Add arg in permission callback

---

data/helpers.d/setting

- No requirements
- No helper to check if a permission exists
- Add requirements
- Add `ynh_permission_exists`
...
...

[enh] Improve permission helpers

---

src/yunohost/tests/test_apps.py

fix test_failed_multiple_app_upgrade

---

data/templates/dnsmasq/plain/resolv.dnsmasq.conf

It seems this resolver is regularly (always?) unreachable
Remove it
Ready

[fix] This DNS resolver in ipv6 is unreachable

---

debian/copyright

[debian/copyright] fix URL

---

src/yunohost/app.py

...
Needed by this [PR](https://github.com/YunoHost/SSOwat/pull/153)
...
...

[FIX] Full permission url in ssowat conf

---

src/yunohost/permission.py

When an app protects his paths with regex, we can't use the current permission system.
One possible solution is to deal with hooks.
Con: We can only manage add and and remove of `visitors`.
Needed by: https://github.com/YunoHost-Apps/lutim_ynh/pull/44
...
...

more informations in hooks permission

---

data/helpers.d/getopts
data/helpers.d/mysql
data/helpers.d/postgresql

Infinite loop due to getops (if you want to dig it: https://paste.yunohost.org/acinuquleh)
Parameter Substitution magic (force the substitution at the beginning or at the end)
...
...

Fix getops

---

data/helpers.d/apt

When a dependency cannot be installed, we currently get something like : 
```
Info: DEBUG - The following packages will be REMOVED:
Info: WARNING - E: Packages need to be removed but remove is disabled.
Info: DEBUG -   appname-ynh-deps
Info: WARNING - Unable to install dependencies
```
which usually corresponds to a dependency of appname-ynh-deps that cannot be installed ... but doesn't tell us what / why ...
Instead, we can use `apt-get check` to tell us what's the issue with some output like : 
```
WARNING - E: Packages need to be removed but remove is disabled.
DEBUG - + apt-get check
DEBUG - Reading package lists...
DEBUG - Building dependency tree...
DEBUG - Reading state information...
DEBUG - You might want to run 'apt --fix-broken install' to correct these.
DEBUG - The following …
```

[enh] Tell apt to explain what's wrong when there are unmet dependencies

---

src/yunohost/tools.py
src/yunohost/user.py

Remove redirected_urls after postinstall

---

data/actionsmap/yunohost_completion.py

Subcategories was not autocompleted 
Yes it is \o/
...
...

[enh] Bash completion: add subcategories

---

data/actionsmap/yunohost.yml
data/helpers.d/setting
src/yunohost/permission.py
src/yunohost/user.py

https://github.com/YunoHost/example_ynh/pull/111#discussion_r400354745
...
...
...

add ynh_permission_has_user

---

data/helpers.d/php
src/yunohost/app.py
src/yunohost/backup.py

`YNH_DEFAULT_PHP_VERSION` is not defined
Add `YNH_DEFAULT_PHP_VERSION` env in backup.
...
...

Add default php in backup

---

data/helpers.d/postgresql

I found a bug in odoo 9 where the bug is due to the fact the psql user don't own the db.
I think it should.
Change the db owner
Ready
...

[fix] Psql user should own the database

---

.gitlab-ci.yml

...
Add linter
Not tested lul
...

Add linter

---

.gitlab-ci.yml
pytest.ini
src/yunohost/tests/conftest.py
src/yunohost/tests/test_apps.py

Some clean ups on test running.
Minor modifications.
Just look at the tests output on gitlab-ci or run them yourself.

Test apps cleanup and automation

---

locales/en.json
src/yunohost/domain.py

...
Add small check to avoid a crash
...
...

[fix] domain remove if an app without a domain is installed

---

src/yunohost/backup.py
src/yunohost/tests/test_backuprestore.py

...
Add `manager` argument in `BackupMethod.create`, rework `set_system_targets`
...
...

[fix] Restoration of custom hooks / missing restore hooks

---

src/yunohost/utils/ldap.py

Needed for https://github.com/YunoHost/moulinette/pull/247 because ldap is annoying as hell.
Not the prettiest implementation but gosh ldap.
Tested locally.
Update moulinette and yunohost with the 2 branches, then:
* systemctl stop slapd
* yunohost user list

[fix] handle new auto restart of ldap in moulinette

---

src/yunohost/app.py
src/yunohost/tests/test_apps_arguments_parsing.py

I want to rewrite all arguments parsing because it sucks but there is not tests.
Also variables names were shit.
Write some tests and do some angry renaming.
Locally test are happy for me, idk on CI yet.
Also I want to write moar tests but we can already merge if we want, that won't change much things.
Wait for CI

Test for args parsing

---

src/yunohost/tests/test_apps_arguments_parsing.py

Then end of: https://github.com/YunoHost/yunohost/pull/989
idk if anyone really wants to review, it's boring as hell and was super boring to write.

Test for args parsing 2

---

data/helpers.d/apt
data/helpers.d/php

Sury, again (the current solution seems to work, but it's not really conventional)
Apply Pin recommended by @taziden 
I don't know if it's better this way, tell me
Tested with:
- Install nextcloud
- Install Weblate ([buster](https://github.com/YunoHost-Apps/weblate_ynh/tree/buster) branch)
- Install Snipeit ([fix-buster](https://github.com/YunoHost-Apps/snipeit_ynh/tree/fix-buster) branch)
- Install Synapse
No problems so far
...

Fix sury v99999

---

data/helpers.d/postgresql

description not consistent with mysql helper
make it consistent
...
...

Change to be consistent with mysql helper

---

data/helpers.d/nodejs

- N not up to date
- May not fix this issue [#77](https://github.com/YunoHost/package_check/issues/77)
- Bring N up to date with upstream
...
...

Update n to 6.5.1

---

.github/PULL_REQUEST_TEMPLATE.md

We tried to be super formal about validation process for PR but in the end we don't really use it for many reasons, and the PR review system is more suited for this and everything kind of depends on the size / nature / impact of the PR discussed
Remove the checkboxes from the PR template
...
...

We don't really use / need these super bureaucratic validation checkboxes

---

src/yunohost/tools.py

After post install the folder `/home/admin` doesn't exist.
Create it as we do for a regular user: https://github.com/YunoHost/yunohost/blob/6c2163589fd684002bd9f2724b500ffd2dd30d19/src/yunohost/user.py#L209-L215
...
...

create admin home folder

---

data/helpers.d/php

-*Missing capitalization*
-*php -> PHP*
 -*php-fpm -> PHP-FPM*
 -*40Mb -> 40 MB*
...

Add capitalization to PHP

---

.gitlab/ci/lint.gitlab-ci.yml
tox.ini

imove tox and add python3 linter

---

.gitlab/ci/test.gitlab-ci.yml

trying to fix the ci

---

src/yunohost/vendor/acme_tiny/acme_tiny.py

acme_tiny is not up to date
Update acme_tiny to the [latest version](https://github.com/diafygi/acme-tiny/releases)
Not tested, but we should keep this lib up to date, right?
...

Update acme_tiny to 4.1.0

---

data/helpers.d/backup

--is_big seems not clear.
https://forum.yunohost.org/t/how-is-working-ynh-backup-is-big/11179/2
We actually did change that behavior many times already...
Explain how to use that argument, which is not trivial.
...
...

Add doc about is_big

---

.gitlab/ci/build.gitlab-ci.yml

Try to clone moulinette and ssowat with the version in the debian/control

---

src/yunohost/app.py

Specific process is used for github, but it's not anymore relevant. 
Repo listed in apps.json from an other forge download all the commit of the branch instead of just the revision needed.
Refactor a bit and use git init and git fetch to download only what we want.
Ready
Try to do a yunohost app install with appname or app repo

[enh] Refactoring of package download process

---

data/helpers.d/utils

Too much madness about ynh_replace_string all over the place, lack of consistent/simple template format/helpers
Add yalh's experimental helper ynh_add_config into the core
Yolocomitted, but done I guess ? 
Uuuh idk

Add ynh_add_config helper

---

.gitlab/ci/doc.gitlab-ci.yml

Related to:
https://github.com/YunoHost/doc/pull/1448
https://gitlab.com/yunohost/yunohost/-/jobs/872132228
https://gitlab.com/yunohost/yunohost/-/blob/9af3873a1f83a1c242d0b534e0a8111bd3d80b88/.gitlab/ci/doc.gitlab-ci.yml
I use a token which has only access to `public_repo` on yunohost-bot, registered on [this page](https://gitlab.com/yunohost/yunohost/-/settings/ci_cd) (accessible only by admin members)
...
...

Create a PR on new tags (for new YNH version)

---

data/helpers.d/nodejs

- New version upstream
...
- Upgrade to version 6.7.0
...
...
...

Upgrade n version to upstream

---

data/hooks/backup/22-conf_mail
data/hooks/restore/22-conf_mail

Dkim keys are not backuped
Backup and restore it
Untested (and written in 2 minutes before a meeting...)
...

[fix] Backup/restore dkim keys

---

data/hooks/backup/42-conf_ynh_dyndns
data/hooks/restore/42-conf_ynh_dyndns

Dyndns keys are not backup, so people are obliged to ask for removing their domain on forum when they restore
Save this damned keys !
Tested Ready
...

[fix] Add Dyndns domains keys to backup

---

src/yunohost/app.py

fix the fixme

---

data/actionsmap/yunohost.yml

[Credic O](https://en.wikipedia.org/wiki/C%C3%A9dric_O) can't use YunoHost.
Accept his last name and same for the first name.
Test
> yunohost user create testeu
Answer "a" and "b" to first and last name.

[mod](user_create) only ask for one letter for first/last name

---

data/actionsmap/yunohost.yml

[doc] tell users how to get all permissions

---

data/actionsmap/yunohost.yml

https://github.com/YunoHost/yunohost/pull/1075/commits/aefdd424d8dcb3209dc51c381af62debf9914039
...
...
Requires https://github.com/YunoHost/moulinette/pull/266
...

readd comment of #1075

---

src/yunohost/utils/legacy.py

Fix https://github.com/YunoHost/issues/issues/1701
https://stackoverflow.com/a/63555547
...

use read_yaml for json because lol

---

data/hooks/backup/42-conf_ynh_dyndns

https://github.com/YunoHost/issues/issues/1711
Fix https://github.com/YunoHost/issues/issues/1711
Not tested
...

ynh_exec_warn_less dyndns backup

---

data/helpers.d/utils

https://github.com/YunoHost/issues/issues/1710
Update the doc and set the `ynh_check_app_version_changed` helper as deprecated
...
...

set ynh_check_app_version_changed as deprecated

---

data/helpers.d/php

Adding composer experimental helper
Ready and tested on several apps

[enh] Adding composer helper

---

.gitlab/ci/lint.gitlab-ci.yml
tox.ini

Look at the CI (half tested)
...
...

add auto-format-code

---

data/helpers.d/nodejs

...
Upgrade to new version upstream 7.0.0
...
...
...

Upgrade n to v7.0.0

---

tests/test_i18n_keys.py

test i18n is broken after ci-format
Fix regex by adding `\n*`
...
...

fix i18n test after format

---

data/templates/nginx/plain/yunohost_admin.conf.inc

We don't have `.ms` file anymone
Add cache to files `.js|css|png|jpg|jpeg|gif|ico|json|woff|woff2|ttf|eot`
...
...

fix cache ynh-admin vuejs

---

data/helpers.d/logging
data/helpers.d/user

- Add `ynh_exec_as` to the core

Add ynh_exec_as to official

---

data/templates/yunohost/firewall.yml
src/yunohost/firewall.py

We don't close upnp port
To fix this issue I can either refactor firewall and make it easy to read or add more mess because I'm too lazy for the previous solution. I let you discover which solution I choose.
Create a new list with of `UDP_TO_CLOSE` and `TCP_TO_CLOSE` port.
...
...

fix upnp closing port

---

src/yunohost/service.py

The description of services is replaced by True
Use m18n.n
Untested
...

[fix] True instead of description

---

data/helpers.d/apt
data/helpers.d/backup
data/helpers.d/fail2ban
data/helpers.d/hardware
data/helpers.d/logging
data/helpers.d/logrotate
data/helpers.d/multimedia
data/helpers.d/mysql
data/helpers.d/network
data/helpers.d/nginx
data/helpers.d/nodejs
data/helpers.d/permission
data/helpers.d/php
data/helpers.d/postgresql
data/helpers.d/setting
data/helpers.d/string
data/helpers.d/systemd
data/helpers.d/user
data/helpers.d/utils

The helper doc was not adapted to the new templates. This is mostly fixed (not 100%, but that's a huge edit already).
```
cd doc
./generate_helper_doc.py
```

helper doc : Fix all doc (mostly)

---

debian/changelog

https://github.com/YunoHost/yunohost-admin/pull/337
https://github.com/YunoHost/moulinette/pull/272

Update changelog for 4.2

---

data/hooks/conf_regen/03-ssh
data/templates/ssh/sshd_config
locales/en.json
src/yunohost/settings.py

...
Close https://github.com/YunoHost/issues/issues/1740
We probably want a migration to handle the current port, IDK if we need to do something for https://github.com/YunoHost/yunohost/blob/ce64a6380abfe0c8b9892172fd72c901c2685d36/data/templates/yunohost/services.yml#L46
...
...

add ssh port setting

---

src/yunohost/app.py
src/yunohost/backup.py

Sooo while starting to work on https://github.com/YunoHost/yunohost/pull/1213 I got fed up of seeing so many different ways to handle the fact that we want to have a tmp directory to run app scripts in during install/remove/upgrade/backup/restore/changeurl/actions/configpanel/...
Also some super old code was still putting some weird "admin" ownership all over the place ..
Introduce a small internal helper `_make_tmp_workdir_for_app` that will create a proper tmp directory
Tested on my side, also tests are passing too it seems...
Eeeh run every possible app actions :|

More uniform tmp dir for apps, remove some weird 'admin' ownership

---

src/yunohost/certificate.py

https://github.com/YunoHost/issues/issues/1803
This fix only the tail not the reason why the renewing failed
use subprocess to call tail command.
Note we could instead use tail function from services.py
Just tested with a python3 interpreter
...

[fix] Email on certificate renewing failed

---

.gitlab-ci.yml
.gitlab/ci/test.gitlab-ci.yml

Duplicated pipeline
Create a new pipeline if changes are made on the default branch or if it's a PR
...
...

ci triggered only for default branch or PR

---

data/templates/dnsmasq/plain/resolv.dnsmasq.conf

LDN has voted to stop their activities
Remove their DNS resolver from the list
Ready
...

[enh] Remove LDN from resolver list

---

src/yunohost/hook.py

Actions are broken in 4.2 because of this: https://github.com/YunoHost/yunohost/commit/e0ac7de432c7e565fef3c07b319bffa7d8cf7945#diff-4e3fc54f4d9df45c5e6f581ce328c89c89142033813a623f0d495e1750b245c6
In some cases, we want to run actions as a non root user
...
...

add user in hook exec again

---

src/yunohost/settings.py
src/yunohost/tests/test_settings.py

just trying to clean/avoid an if just for tests

monkey patch get_setting_description

---

data/actionsmap/yunohost.yml
src/yunohost/app.py

- Add --purge option to "yunohost app remove" (https://github.com/YunoHost/issues/issues/1854)
- (no webadmin part)

Add --purge option to "yunohost app remove"

---

data/helpers.d/utils
src/yunohost/app.py

`YNH_APP_BASEDIR` is incorrect during the execution of the action
Actions are not executed in a tmp directory
...
...
...

Fix action

---

locales/en.json

Set more meaningful time format

time format

---

data/helpers.d/utils
src/yunohost/app.py
src/yunohost/backup.py

Half tested on my side
Done, waiting for the ci
Run all possibles actions for an app and see

add YNH_APP_BASEDIR in the env var

---

locales/en.json
src/yunohost/app.py
src/yunohost/tests/test_app_config.py
src/yunohost/tests/test_appurl.py
src/yunohost/tests/test_questions.py
src/yunohost/user.py
src/yunohost/utils/config.py

c.f. https://github.com/YunoHost/moulinette/pull/303
c.f. https://github.com/YunoHost/moulinette/pull/303
...
...

Rework prompt() again

---

data/helpers.d/nodejs

helpers: Update n to 8.0.0

---

data/hooks/conf_regen/43-dnsmasq

https://forum.yunohost.org/t/latest-yunohost-update-broke-dnsmasq-on-my-server/17962/18
...
...
...

[fix] Try to fix the return line bug in dnsmasq conf

---

data/helpers.d/nodejs

Update n to 8.0.1

---

src/yunohost/app.py

Addresses https://github.com/YunoHost/issues/issues/1950
Fix typo
Done, seems straightforward and tested by @jacen05
...

Fix typo in deleting superfluous question keys

---

.lgtm.yml
README.md

...
To be discussed, this gives us interesting feedback
...
...

add lgtm/code quality badge

---

data/hooks/diagnosis/12-dnsrecords.py
src/yunohost/app.py
src/yunohost/certificate.py
src/yunohost/data_migrations/0016_php70_to_php73_pools.py
src/yunohost/data_migrations/0018_xtable_to_nftable.py
src/yunohost/dns.py
src/yunohost/domain.py
src/yunohost/regenconf.py
src/yunohost/service.py
src/yunohost/tools.py
src/yunohost/user.py
src/yunohost/utils/config.py

https://lgtm.com/projects/g/YunoHost/yunohost/alerts/?mode=list
...
...
...

Lgtm warnings

---

src/yunohost/domain.py

Fix https://github.com/YunoHost/issues/issues/1281
...
...
...

[fix] Force install certificate on yunohost domain add

---

.codeclimate.yml
.gitlab-ci.yml
.gitlab/ci/test.gitlab-ci.yml

Add two new jobs that run in parallel, to display a report on the quality of the code.
[Example](https://gitlab.com/yunohost/yunohost/-/pipelines/441287856/codequality_report) and [here](https://yunohost.gitlab.io/-/yunohost/-/jobs/1940532682/artifacts/gl-code-quality-report.html)
[Doc](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html)
...
...

Add codequality

---

helpers/nodejs

Update n to 8.0.2

---

.github/workflows/n_updater.sh
.github/workflows/n_updater.yml

@ericgaspar works too much.
Preventing @ericgaspar from exhaustion, one auto-updater at a time.
`sh` script tested, Action yet to be tested.
Yolomerge?

Add n auto-updater

---

helpers/utils

Not really a problem, just simplify the explanation of how to use `ynh_add_config`
Ready
Nothing to test

ynh_add_config template

---

helpers/user

better example

---

src/utils/legacy.py

Just a minor typo/grammar problem.
Drop indefinite article ("a").

Fix typo (indefinite article in plural)

---

share/config_domain.toml
src/dns.py
src/domain.py

also set default `return_self` to `False` since only one call needs this

call _get_parent_domain_of to ensure getting any level parent

---

README.md

Final result https://github.com/YunoHost/yunohost/blob/doc-sponsors/README.md#they-support-us-3
(Please squash and merge)

Add sponsors to the README

---

conf/nginx/yunohost_admin.conf.inc
src/app.py
src/app_catalog.py

https://github.com/YunoHost/issues/issues/383
this and cf also https://github.com/YunoHost/apps/pull/1557
Still need work to be integrated in the webadmin tho, and decide watdo with apps with no logos
Yolo
...

Yoloimplementation of app logo support (require change in app catalog build)

---

share/actionsmap.yml

Don't take lock for read/GET operations

---

debian/postinst

https://forum.yunohost.org/t/drole-de-fichier-testalex-dans-var-log/23083/2
Remove the file
Opinion Needed @alexAubin (is there a good reason to keep it ?)
...

[fix] Remove some debug test

---

src/utils/resources.py

set `w` as default permission on `install_dir` folder

set `w` as default permission on `install_dir` folder

---

src/utils/config.py

fix https://github.com/YunoHost/issues/issues/2165

fix i18n panel+section names

---

src/dns.py

https://forum.yunohost.org/t/failed-to-create-record-a-domain-list-indices-must-be-integers-or-slices-not-str/23883
> Failed to create record A/<domain> : list indices must be integers or slices, not str
...
Tested on my side
...

Fix autodns for gandi root domain

---

share/registrar_list.toml

Add support for Porkbun through Lexicon

---

src/ssh.py

Closes https://github.com/YunoHost/issues/issues/2187
Might need a fix/migration for existing directories.
...

User .ssh directory should be executable

---

src/utils/resources.py

We use Toml and Python. Let's use the types they provide.
Use a list instead of a string. You can split it into lines, add comments etc.
The code is expected to retain compatibility with current manifests with strings.
Untested
...

Allow passing a list in the manifest.toml for the apt resource packages

---

src/__init__.py
src/app.py
src/app_catalog.py
src/backup.py
src/certificate.py
src/diagnosis.py
src/dns.py
src/domain.py
src/dyndns.py
src/firewall.py
src/hook.py
src/log.py
src/migrations/0021_migrate_to_bullseye.py
src/migrations/0022_php73_to_php74_pools.py
src/migrations/0023_postgresql_11_to_13.py
src/migrations/0024_rebuild_python_venv.py
src/migrations/0025_global_settings_to_configpanel.py
src/migrations/0026_new_admins_group.py
src/permission.py
src/regenconf.py
src/service.py
src/settings.py
src/tools.py
src/user.py
src/utils/configpanel.py
src/utils/form.py
src/utils/legacy.py
src/utils/resources.py

Unecessary messages + obscure concept of "action id" which never really got used but leading to bloat

Moulinette logging is an unecessarily complex mess, episode 57682

---

debian/control
doc/generate_json_schema.py
src/app.py
src/dns.py
src/domain.py
src/log.py
src/settings.py
src/tests/test_app_config.py
src/tests/test_dns.py
src/tests/test_questions.py
src/utils/configpanel.py
src/utils/form.py

TLDR:
Use pydantic for config panel and app install form parsing/validation.
Tried to stick to what is was before.
Ready ?
try to install apps, and play with config panels
<details><summary>Check the ConfiPanel JSON schema generated by pydantic</summary>
```json
{
"title": "ConfigPanelModel",
"type": "object",
"properties": {
"version": {
"title": "Version",
"default": 1.0,
"type": "number"
},
"i18n": {
"title": "I18N",
"type": "string"
}
},
"additionalProperties": {
"$ref": "#/definitions/PanelModel"
},
"definitions": {
"DisplayTextOption": {
"title": "DisplayTextOption",
"type": "object",
"properties": {
"type": {
"title": "Type",
"default": "display_text",
"enum": [
"display_text"
],
"type": "string"
},
"ask": {
"title": "Ask",
"anyOf": [
{
"type": "object",
"additionalProperties": { …
```

ConfigPanel: switch to pydantic 3/3

---

src/utils/resources.py

Might address https://github.com/YunoHost-Apps/hotspot_ynh/pull/113
...
...
...

Support packages_from_raw_bash in extra packages

---

locales/en.json
locales/fr.json

https://github.com/YunoHost/issues/issues/2320
mention CIDR notation for webadmin allowed IPs config
...
...

mention cidr notation

---

src/utils/resources.py

gitlab, gitea and forgejo are now supported by the autoupdater
add docs for gitlab, gitea and forgejo forges for the autoupdater
DRAFT
...

Autoupdate: update docs

---

hooks/conf_regen/10-apt

- https://forum.yunohost.org/t/something-went-wrong-while-updating-the-cache-of-apt-due-to-sury/15024
- https://github.com/oerdnj/deb.sury.org/issues/2074
probably wrong since apt-key is depreciated or something
yolocommit
...

Update sury apt key

---

src/utils/resources.py

original commit by @Salamandar: https://github.com/YunoHost/doc/pull/2408/commits/93793fef44044ec7e5592c8bc8ad825ef32b7aaa
code was edited in the wrong place: https://github.com/YunoHost/doc/pull/2408

Docs: Add autoupdate.version_regex to the doc

---

maintenance/make_changelog.sh

We made a new release and we had some problems, here are some fixes
...
...
...

change REPO_URL so we can use it for all YNH projects, logc doesn't exist

---

locales/en.json

- reflect?
- lack of conditionnal
- changed `to reflect this change` to `to take this change into account`
- changed `and update the app manifest` to `and perhaps update the app manifest`
done

Locales: Change some app_corrupt_source words to be more explicit

---

src/authenticators/ldap_ynhuser.py

Fix for #2384
Removed some indentation levels and added some comments for clarity.
EDIT: tested

Allow users to access their own domain portal without app permission

---

helpers/utils

Document ynh_add_source --full_replace=1

---

helpers/mongodb

Follow-up of https://github.com/YunoHost/yunohost/pull/1838
@orhtej2 was pointing to https://github.com/orhtej2/wekan_ynh/tree/no_keep_version that might be relevant to include in the core

Add mongodb helpers

---

.github/workflows/autoblack.yml
.github/workflows/n_updater.yml

peter-evans/create-pull-request@v6 already checks if diff exists, and and already creates commits.

Simplify github workflows

---

share/actionsmap.yml

the previous help message was confusing
help message disambiguation
done
...

cli: better help message for 'diagnosis unignore'

---

src/diagnosis.py

i'd like commit amend but it was already merged thanks to our serial merger 🚀

fix a dumb typo

---

src/log.py

`yunohost log list` takes way too long. In particular this is due to the fact that even when we're only asking to the "main" operations (without the suboperations), it's necessary to parse the .yml and read the "parent" key. But parsing yamls is not free
- Ignore files older than a year
- Add a mecanism creating a "cache" hidden symlink for every log file pointing to the parent, or /dev/null if there's no parent
Tested on my side, should be working
Run `yunohost log list`, compare time before / after the change

log: optimize log list perf by creating a 'cache' symlink pointing to the log's parent

---

src/log.py

https://github.com/YunoHost/issues/issues/2421
...
...
...

Fix "log list" : use root_dir for iglob / make sure we use absolute paths

---

helpers/helpers.v2.1.d/apt

Helper was apparently renamed without editing the docs...

docs: ynh_install_app_dependencies -> ynh_apt_install_dependencies

---

helpers/helpers.v2.1.d/systemd

awawa undocumented stuff
awawa document stuff
done
...

document the 'systemd' option for 'ynh_systemctl --line_match'

---

src/utils/resources.py

Add instructions to https://yunohost.org/en/packaging_apps_resources to check locally whether autoupdate strategy is working

Add instructions to check locally whether autoupdate strategy is working

---

src/backup.py

#1959 broke copy/tar backups, preventing apps upgrades :(
Verify that a property exists before using it.
Worked once on my machine (TM)
Backup any app from WebUI.

Fix formatting error.

---

share/actionsmap.yml
src/tools.py

This is required for automated install / image build.

Allow bypassing the terms of services at postinstall time

---

doc/generate_helper_doc.py
src/authenticators/ldap_ynhuser.py
src/domain.py
src/log.py
src/migrations/0027_migrate_to_bookworm.py
src/user.py
src/utils/resources.py

<https://gitlab.com/YunoHost/yunohost/-/jobs/8151103840>

Fix py311-lint

---

src/authenticators/ldap_ynhuser.py

Fix ldap_ynhuser: missing is_dev variable

---

src/authenticators/ldap_ynhuser.py
src/user.py

Fix tox linting (whitespace)

---

helpers/helpers.v2.1.d/fail2ban

helpersv2.1/fail2ban: Fix reload-or-restart match line

---

src/app.py

Fix Ihatemoney : it needs the basic auth workaround

---

src/app.py

Fix owncloud API that needs basic auth workaround

---

share/config_domain.toml
src/domain.py
src/portal.py

Add 3 tiling theme for the user portal:
- 'descriptive': display logo + label + description
- 'simple': display logo + label
- 'periodic': legacy

Enh portal tiling

---

helpers/helpers.v1.d/go
helpers/helpers.v2.1.d/go

helpers: Pass HOME to goenv init

---

helpers/helpers.v2.1.d/templating

ynh_config_add examples where using v1 helper syntax

Fix ynh_config_add helpers.v.2.1 example

---

src/authenticators/ldap_ynhuser.py

Some user tried to log with a mail, it seems previously it was possible ???
https://github.com/YunoHost/issues/issues/2475
Search the username binded to a mail
Tested manually
Try to log with username or with email

[enh] Allow to login with a mail

---

conf/yunohost/services.yml
src/firewall.py
src/migrations/0032_firewall_config.py

":" was used for port ranges, "-" should be used now

Fix firewall

---

conf/dnsmasq/plain/resolv.dnsmasq.conf

Only FFDN subnet are authorized now...
https://www.fdn.fr/attaque-serveurs-dns-2025/
Remove FDN resolver
Ready
...

[fix] FDN dns resolver are not available for all AS

---

src/log.py

It's easier and safer to use process.parents()

Refactor _guess_who_started_process

---

conf/nginx/server.tpl.conf
conf/nginx/tls_passthrough.conf

Yeah, just some whitespace / empty lines fixes.
do not merge yet, it conflicts with the tls passthrough fix, and i want to investigate the missing endline on the last line of the file.

Fix whitespace in nginx template files

---

src/utils/udisks2_interfaces.py

Fixing my mess introduce in the CI

Fix a lambda typo + MyPy error in src/utils/udisks2_interfaces.py

---

src/tools.py

spwd was deprecated in python 3.11, removed in 3.13 (trixie).
Call directly passwd, that uses the PAM config.
ready to test
...

tools_rootpw: Replace spwd with direct call to passwd.

---

.github/workflows/lint.yml

Add python linting like on gitlab but on github actions

---

src/__init__.py
src/app_catalog.py
src/permission.py
src/utils/configpanel.py
src/utils/error.py
src/utils/i18n.py
src/utils/udisks2_interfaces.py

Fix typing

---

helpers/helpers.v2.1.d/redis

The documentation for `ynh_redis_remove_db` is not accurate
Document it.
N/A.

Fix documentation for ynh_redis_remove_db

---

src/app.py
src/settings.py

Email settings seem not to be applied.
...
Please check, my brain is sunday-fried.
...

fix: portal domain conf not properly updated with the portal_allow_mail_edit settings

---

share/actionsmap.yml
src/tools.py

Addresses https://github.com/YunoHost/issues/issues/2329
I'm unsure what are all the `.YYYY-MM-DD...` symlinks for.
Ready?
...

Make basic-space-cleanup delete YunoHost logs too
