data/hooks/diagnosis/12-dnsrecords.py, data/hooks/diagnosis/24-mail.py, src/yunohost/utils/network.py
https://forum.yunohost.org/t/yunohost-3-8-testing-call-for-feedback/10870/34?u=ljf
Don't use the default resolver, create one configure on dnsmasq ip (127.0.0.1) and avoid like this the case where an infamous "search" is hide inside /etc/resolv.conf.
Ready
...
=> [fix] Add a new dig() helper to fix misc diagnosis issues that rely on dns queries

locales/en.json, src/yunohost/certificate.py
Follow up of https://github.com/YunoHost/yunohost/pull/917 ... Did not realize we had this check that explicitly depends on the name of the old legacy file ... But now that it changed, renew is gonna be broken and we gotta fix it.
Fix the code to detect the new code snippet is there... + update error message accordingly
```
$ yunohost tools shell
> from yunohost.certificate import _check_acme_challenge_configuration
> _check_acme_challenge_configuration("your.test.domain.tld")
-> without the fix, probably False
-> with the fix : True (if your nginx conf is up to date)
```
=> Fix acme snippet detection

data/helpers.d/network
Duplicate the code. `ynh_port_available` may not work on ipv6
Apply the patch to `ynh_port_available` and use it in `ynh_find_port`
...
...
=> use ynh_port_available in ynh_find_port

.gitlab-ci.yml, data/hooks/conf_regen/15-nginx, src/yunohost/domain.py, src/yunohost/regenconf.py, src/yunohost/tests/test_regenconf.py
c.f. https://github.com/YunoHost/issues/issues/1568 and other situations reported on the forum where a manually-modified conf file (either by an app or because of weird other subtle bug that are still to be identified) results in catastrophic situations : the conf file is not removed, but certs are, resulting in nginx not being able to load the configuration because it can't find the certs.
During domain_remove(), we should enforce this conf file to be removed. This is kind of a adhoc fix as it doesnt fix the root cause of the issue but still better than instances exploding.
I added some tests to cover this (@kay0u : dunno if anything specific is needed on the CI if we add a new test file) 
Also increased the robustness of the nginx regen-conf for cases where the conf is broken or nginx …
=> [fix] Be more robust against manually modified domain conf

src/yunohost/app.py, src/yunohost/tests/test_apps.py
This is a small regression introduced in 3.7 when refactoring app_ssowatconf and app_map : when an app is installed on the root of a domain, `app_map` should return something like 
`domain.tld/: foo`
and not : 
`domain.tld: foo`
(notice the trailing /)
The lack of `/` break some checks like here https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/app.py#L1109 which in turns trigger https://github.com/YunoHost/issues/issues/1572 (it should not be possible to make default app an app that's already on the root ...)
(Note that the makedefault system is still heavily buggy but can't be fixed until we properly implement domain settings, which is also needed to enable/disable mail/xmpp per-domain, and we also have to think about how to handle nasty backup/restore or …
=> [fix] Make sure to return '/' and not empty string for stuff on domain root

data/helpers.d/fail2ban, data/helpers.d/systemd
https://forum.yunohost.org/t/echec-installation-wordpress-yunohost-sur-raspberry-pi-3/10987/19
We often see fail2ban failing to reload or to restart.
That is because, if fail2ban have too many IP banned, it will need a long time to reload. So if we ask fail2ban to reload to many times, it may not have fully reload yet when we ask it to reload again. And so the service appears as inactive, because not fully started nor stopped.
As for many other services, wait for the service to be ready.
Tested.
Can be reviewed.
...
@YunoHost/apps
=> Wait for fail2ban to reload

src/yunohost/app.py
1. There's currently a bug that if you install an app that uses old non-patchable helpers (e.g. 243), an exception will be triggered *after* the setting folder of the app is created ... but this app setting won't be removed and will stay there, as if the app was installed (but lacks a manifest.json ...)
2. Many apps use the old 'yunohost tools diagnosis' which will then display an ugly warning/error during app install...
1. Patch the legacy helpers *before* we create all the setting folder etc.
2. Remove usage of 'yunohost tools diagnosis' using a similar technique than for other old helpers
1. Try to install 243. Without this patch, the folder in /etc/yunohost/apps still exists after the install failure
2. Try to install an app that uses 'yunohost tools …
=> Fix helper patching + patch usage of old 'yunohost tools diagnosis'

data/hooks/diagnosis/24-mail.py
If there is the domain configure in /etc/host the method with socket does not work.
Replace the socket request with a dig PTR request on reverse IP
Ready (tested with an ip with a bad PTR.
Run diagnosis and see reverse dns
=> [fix] Reverse DNS check

data/actionsmap/yunohost.yml, data/helpers.d/utils, src/yunohost/app.py, src/yunohost/log.py, src/yunohost/service.py
This is again me procrastinating instead of fixing bugs for 3.8 lol
Anyway, just stumbled on some debug logs that was showing a lot of "set +x" or "Helper used in legacy mode" or "local foo" which ain't so helpful (c.f. also the screenshot in https://github.com/YunoHost/yunohost-admin/pull/294 ) . It's not unusual to see half the lines of the 20ish last lines of some debug log filled with these
So in the same vein as [this PR](https://github.com/YunoHost/yunohost-admin/pull/294), this is an attempt to increase the likelyhood that users would be able to identify the issue themselves by removing some lines which we know aren't gonna be relevant. This is also meant to help more advanced users / app packagers because this hack is also applied to debug info show during app script failures.
The …
=> Try to show smarter / more useful logs by filtering irrelevant lines like set +x etc

data/helpers.d/apt
> Warning: /usr/share/yunohost/helpers.d/apt: line 267: php${$YNH_DEFAULT_PHP_VERSION}*: bad substitution
...
...
...
=> [Epic Fix] ynh_install_app_dependencies

data/helpers.d/hardware
If we use `--free` and `--total` the result will be the one of `--free` arbitrarily 
Force a choice between one of them.
Move `total_ram`, `total_swap`, `total_ram_swap`, `free_ram`, `free_swap`, `free_ram_swap` when used
...
Not tested yet
=> [enh] Enforce choose --total or --free for ynh_get_ram

data/helpers.d/apt, data/helpers.d/utils
c.f. https://forum.yunohost.org/t/yunohost-command-not-ending/11177/7
Upgrading an app resulted in a never-ending command blocking all other yunohost commands
`wget` was hanging indefinitely .. not sure exactly why but it's pretty clear that the issue is a lack of timeout. `wget` only has a read-timeout of 900 seconds enabled (meaning : if nothing received during 900 sec once downloaded started, command times out) but no timeout on dns queries and opening TCP connection except what system libs implement. (c.f. `man wget`)
We can add `--timeout 900` to set 900 sec timeout to all these operations.
N.B. : this doesn't mean that the overall operation can't take more than 900 secs, just that if absolutely nothing happens during 900 secs, the command exits.
Yolocommited, not tested ...
Well I …
=> Add a timeout to wget in helpers

src/yunohost/app.py
Unable to upgrade a multi instance app
Use the real name of the app for the catalog
Use `_parse_app_instance_name` to parse the app name
Done
Install wordpress twice, remove the first one, try to update wordpress__2 with
`yunohost tools upgrade --apps wordress__2`
=> [fix] multi instance upgrade

lib/metronome/modules/mod_storage_ldap.lua
That reflects changes to storagemanager API in 3.14.0.
users() method has been replaced with nodes()
Final.
Wait for 3.14.0, although there's no code in Metronome which currently makes use of the users storagemanager method so it could be safely used until releases. That would just avoid an eventual traceback on future releases.
=> mod_storage_ldap: change :users() to :nodes().

data/templates/nginx/plain/yunohost_admin.conf.inc, data/templates/nginx/security.conf.inc, data/templates/nginx/yunohost_admin.conf
Angry red CSP errors in JS console on the webadmin (when accessed via a domain) because of websocket
~~Add websocket to default-src~~
~~Dunno the implication but considering we're in Report-Only anyway, that just removes the error ...~~
Well, I ended up digging into implementing an actual CSP ... Though I might have forgotten something ... c.f. https://github.com/YunoHost/yunohost/pull/961#issuecomment-620903303
Go to the webadmin and open JS console
=> [enh] Real CSP headers for the webadmin

.gitlab-ci.yml, src/yunohost/app.py, src/yunohost/domain.py, src/yunohost/service.py, tox.ini
Realized we had again code with undefined var...
Add a check with tox that shall fail, but only catches really fatal stuff like undefined vars / redefining vars etc ... Ignore stuff like "import not at the top" or "unused var" ... should make wider tests in the future, but c.f. previous work from Kayou, we need a lot of cleaning to make tox/flake8 really happy.
Tested on my side
Run the test o/
=> Check for fatal code errors

.gitlab-ci.yml, src/yunohost/service.py, src/yunohost/tests/test_service.py
I was about to implement `service_update` without realizing that apps already updated service by just calling `service_add` again which just overwrite currently existing services and that's fine
Nevertheless found a few things to clean
Clean stuff, depecate log_type, and ended up writing a few tests :| 
Run the tests and zblerg
=> [enh] service.py cleanup  + add tests for services

data/hooks/conf_regen/01-yunohost, data/hooks/conf_regen/06-slapd, data/hooks/conf_regen/12-metronome
We realized there are some permission issues in /etc/yunohost ... Some happens in some edgy cases (like some /etc/yunohost/apps/$appname folder with permission for others enabled...)
Enforce permissions for stuff in /etc/yunohost/ through the regenconf ... Also that covers the case where a user might have tweaked permissions manually (or system is from an old era) ...
One could wonder "why not just chmod o-rwx /etc/yunohost" ? And the reason is that i'm not 100% sure that there aren't edge cases where a non-root user needs some access ... Though in the end that'd be pretty equivalent to what I did so I don't know ... But should at least check with for example vpnclient_ynh ...
Kindof tested on my side but kind of touchy...
Run the regenconf, check permissions in /etc/yunohost
=> [fix] Enforce permissions for stuff in /etc/yunohost/

data/actionsmap/yunohost.yml, src/yunohost/service.py
When invoking:
```
yunohost service add postgresql --log /var/log/postgresql/postgresql-9.6-main.log --description "PostgreSQL RDBMS"
```
(I'm not sure I'm supposed to do that in app script, but that's another story), it fails with:
```
Warning: /!\ Packagers! --log_type is deprecated. You do not need to specify --log_type systemd anymore ... Yunohost now automatically fetch the journalctl of the systemd service by default.
Warning: Traceback (most recent call last):
Warning:   File "/usr/bin/yunohost", line 218, in <module>
Warning:     timeout=opts.timeout,
Warning:   File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 150, in cli
Warning:     moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
Warning:   File …
```
=> Fix service add log type default value

debian/control
This is a follow-up of https://github.com/YunoHost/issues/issues/1563
We regularly see funky dependency issues because (not always) of backports or chain reactions because of extra apt remove ...
One way to mitigate catastrophic consequences can be to add hard conflicts with backports versions for critical dependencies ... (For example we recently saw [multiples users having issues because slapd / dovecot / ... got upgraded to backport somehow](https://forum.yunohost.org/t/can-not-grab-the-user-info-and-login-to-the-mail-account-doveadm-returned-non-zero-exit-status/10684/6))
The versions number used in the diff are taken from example [from here](https://packages.debian.org/bullseye/nginx) each time comparing the buster-packport version (or when not available, the bullseye version) vs. …
=> Add conflicts with versions from backports for critical dependencies

data/helpers.d/postgresql
Had a story today about a user that for some reason had postgresql already installed but cluster service was down ...
psql first time helper should make sure the service is started ... In fact the current code of the helper is pretty weird and can be simplified and made more explicit
Done
Install an app that uses postgresql
=> [fix] Rework ynh_psql_test_if_first_run

data/helpers.d/apt
As discussed [here](https://github.com/YunoHost/issues/issues/1563#issuecomment-623406509) or [here](https://github.com/YunoHost/issues/issues/1563#issuecomment-623406509) or [here](https://paste.yunohost.org/raw/logudeyuji) ... : we currently have some stupid issues because of sury that leads to situation where "Application Foo cannot be installed after application Bar is installed".
The explanation is : 
- One application (for example: nextcloud) will install php7.3-zip (or other sury deps combination will trigger similar issues)
- php7.3-zip depends on libzip4
- Both php7.3-zip and libzip4 are installed from sury and live happily. In particular, libzip4 is now version 1.5-whatever
- Then you try to install another app. For example: framaforms
- Framaforms depends on libzip-dev
- …
=> Ugly hack to workaround sury pinning issues when installing dependencies

doc/helper_doc_template.html
The helpers doc doesn't point to the stable branch, so links are broken as soon as we have an unstable version.
Change this link \o/
...
...
=> Change url to the stable branch

data/hooks/diagnosis/10-ip.py, src/yunohost/utils/network.py
When using wg-quick to setup a wireguard remote endpoint as a default gateway, the default route doesn't appear in the output of `ip -6 route`.
Display all routes, from all routing tables.
=> fix v6 detection when using wg-quick

data/helpers.d/postgresql
If the user exists, we don't need to create a new password, but use the current one.
Create a new password only if the user doesn't exist, and force the usage of the option db_pwd if the user exists
...
...
=> Do not create a new password if the user already exists

locales/en.json, src/yunohost/hook.py
There are typos in error messages when a wrong value has been detected. The string talks about 'excepted' whereas this should be 'expected' (as this is about expectations, not exceptions we are talking about).
Use 'Expected'
None
Look at the new diagnosis/diagnostics feature when there is an error. Mine was about the DNS values which reported:
```
Name: @
Current value: [u'50 one_server.', u'10 another_server.']
Excepted value: 10 my_own_domain.
```
=> Typo fix for error or diagnostics messages

src/yunohost/app.py
Fix https://github.com/YunoHost/issues/issues/1615
`os.path.join(app_folder, '/settings.yml')` result is `/settings.yml`
`os.path.join(app_folder, 'settings.yml')` result is `/home/yunohost.backup/tmp/mybackup/apps/myapp/settings/settings.yml`
done
Make a restore on buster-unstable
=> Fix https://github.com/YunoHost/issues/issues/1615

data/templates/metronome/domain.tpl.cfg.lua
https://github.com/YunoHost/issues/issues/1609
To sum up, with the XMPP android client conversations, some message can be lost in some circumstances, because conversations does not set "logging" and "persistent" options which are waited by metronome
...
The solution is to set room_default_config in the MUC component configuration
(This is all thanks to the latest ommit of maranda https://github.com/maranda/metronome/commit/3bd36d3b88bf9508ba7cf71cbd4fff65c3497bdd which is in the metronome version 3.14.1)
...
The change in the commit should work
...
- Create a new private group in conversations
- invite several users. Let's say Tarzan, Jane and Mannie
- discuss and then disconnect Tarzan
- Jane keep talking
- Tarzan connect again
With the modification all three people should have the same …
=> Add logging and persistent as default config for new muc room

data/helpers.d/php
`ynh_add_fpm_config` doesn't work with a template in restoration context due to different path to `php-fpm.conf` file (as raised here: 
https://github.com/YunoHost/yunohost/pull/881/files#r429565721)
Test the 2 possibles paths (as already done here https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/helpers.d/apt#L247-L250)
Tested in the frame of cachet package here: https://github.com/YunoHost-Apps/cachet_ynh/pull/13/commits/12680d1be3ec21c3cca975ab850841738d768b15
Test the cachet package, or use the helper with a template in restoration context.
=> Fix ynh_add_fpm_config with template in restore

src/yunohost/regenconf.py, src/yunohost/tests/test_regenconf.py
So ugh this only took me like 4 hours to implement ... 
When you add then remove a domain, regenconf.yml will still contain dummy empty hash entries about the fact that "the file should be removed" - even if the file already got removed.
This is not a huge problem per se, but still weird that yunohost has some entries about stuff that happened years ago. (On a prod server I have a few entries about a few stupid domain names I added just for tests)
This one is a bit trickier.
The scenario is the following: 
- the admin adds a domain foo.bar
- therefore: the regen-conf creates file /etc/dnsmasq.d/foo.bar
- the admin manually *deletes* /etc/dnsmasq.d/foo.bar
- therefore: the file is now understood as manually deleted because there's the old file hash in regenconf.yml
... so far so good, …
=> Clean stale file/hashes in regen-conf

data/templates/postfix/main.cf
Postfix has this very peculiar behavior where the behavior of some config items changes depending on the value. 
Here, if `smtp_destination_concurrency_limit` is set to 1, then according to http://www.postfix.org/postconf.5.html#default_destination_concurrency_limit it doesn't mean "1 concurrent mail per domain, but per recipient address".
So, if set to 1, it means we can send any volume of e-mails concurrently (with a 5s delay) if all recipient addresses are different.
In order to avoid this, we should increase the value to restore the expected behavior (concurrency per domain, not per recipient).
...
Send datalove <3
=> [fix] postfix per-domain destination concurrency

src/yunohost/regenconf.py
[Sometimes, new_file is set to `None`](https://github.com/YunoHost/yunohost/blob/7c2990ff9867fb027eb231baea590ee925eabc0d/src/yunohost/regenconf.py#L226-L239)
...
...
...
=> fix get_files_diff if {orig,new}_file is None

data/helpers.d/apt
When installing an application requiring an `ynh_install_extra_app_dependencies`, a `.gpg` or `.asc` key is installed. After the successful install of the dependency, the repository and the key are removed. We get then one of two info below:
- If a `.asc` key is remove we get this info:
`Info:  '/etc/apt/trusted.gpg.d/appName.gpg' wasn't deleted because it doesn't exist.`
- if a `.gpg` key is remove we get this info:
`Info:  '/etc/apt/trusted.gpg.d/appName.asc' wasn't deleted because it doesn't exist.`
Silence output info for keys removal
=> Silence info: wasn't deleted because it doesn't exist.

data/templates/nginx/yunohost_admin.conf
So I thought this piece of code was somewhat useful but never took the time to carefully think about it ... And for some reason I did and realized that it's pretty much useless, yet it gives a false sense of protection ...
Because of the way nginx handle request and because of other location block, this rules only apply to : 
- `httpS://1.2.3.4/yunohost`
- `httpS://1.2.3.4/yunohost/foobar` (with foobar != admin)
And in particular it doesn't apply to : 
- `http://1.2.3.4/*` (nor the https redirection because you get redirected to https://1.2.3.4/yunohost/admin
- `https://1.2.3.4/yunohost/admin`
- `http(s)://any.domain/*`
And I can't think why a robot would end up querying exactly `httpS://1.2.3.4/yunohost` rather than `https://1.2.3.4` or `https://domain.tld/`
Remove the code snippet …
=> Remove useless robot protection code

src/yunohost/data_migrations/0015_migrate_to_buster.py
After the migration I got this message during `apt update`
> Hit:7 https://apt.armbian.com buster InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Skipping acquire of configured file 'stretch-utils/binary-armhf/Packages' as repository 'http://apt.armbian.com buster InRelease' doesn't have the component 'stretch-utils' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'stretch-utils/Contents-armhf' as repository 'http://apt.armbian.com buster InRelease' doesn't have the component 'stretch-utils' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'stretch-desktop/binary-armhf/Packages' as repository 'http://apt.armbian.com buster InRelease' doesn't …
=> [FIX] patch sources list for armbian

bin/yunohost, bin/yunohost-api, src/yunohost/__init__.py, src/yunohost/tests/conftest.py
Hmf dunno why I'm working on this as it's clearly not a priority.
Just discussed with a user today that wanted to manage 300+ user using a python script ... Ended up willing to write a script that would simply do something like 
```
from yunohost.user import create_user
for user in some_list:
create_user(...)
```
Ended up looking at the mess in usr/bin/yunohost which hasn't been cleaned in a while ... Many options do not make sense anymore and there's a dozen of variables created to define logging levels, all with the-same-value-but-slightly-different-in-some-case ...
Simplify this mess ... 
Regarding the possibility to write scripts, for now it looks something like : 
```python
import sys
sys.path.insert(0, "/usr/lib/moulinette/")
import yunohost
yunohost.init() # possibly set debug=True …
```
=> YunoHost "as a python lib" ? Clean usr/bin/yunohost and yunohost-api ... Move moulinette initialization and other stuff to src/yunohost/__init__.py 

data/helpers.d/apt, data/helpers.d/php, data/hooks/conf_regen/10-apt
There are some weird inconsistencies related to the sury pinning policy and php package installs ... that's complicated to explain and i'm half drunk but basically it makes everything simpler and consistent to just manage the sury pinning policy from a regen-conf hook (even if sury isn't enabled ... it doesn't hurt to set the pinning policy anyway)
That way we can make sure that in the future, if we have to update the pinning policy, there's no weird stuff required about "having to re-run an install or upgrade of an app that uses sury for the pinning policy to get upgraded". It just gets upgraded because it's handled by the regenconf hook no matter what.
Implement a regenconf hook for apt, more specifically to handle the apt pinning policy
Done, tested and working on my side
Run the …
=> Add apt conf regen hook

data/templates/nginx/plain/yunohost_sso.conf.inc, data/templates/nginx/server.tpl.conf
It seems rewrite rules are interpreted before access_by_lua_file script, this create some problem to access SSO with app installed on root domain...
https://forum.yunohost.org/t/acces-interface-utilisateur-cms/12553
Create a location nginx to isolate /yunohost/sso from this kind of rules defined by apps.
Another solution as been explored in ssowat by replacing uri by request-uri, but some other issues come, so this method fix quickly this issue.
Ready
Regen con and install grav on root domain adn try to access SSO
=> [fix] Make sure app nginx confs do not prevent the loading of /yunohost/sso

data/actionsmap/yunohost.yml, locales/en.json, src/yunohost/tests/test_user-group.py, src/yunohost/user.py
Users tend to create mails with other domains than yunohost domain, that was generating an error.
...
Only request a user name for email, that is assignated with a yunohost domain.
...
...
...
=> [enh] c.f. issue 1365, asking a mail address during user creation is confusing ux, people try enter their existing mail addresses

data/templates/ssh/sshd_config
...
Forbid standard user to use several ssh feature. Only admin and root are allowed to do that.
Remove 'sftpusers' unknown user
Ready
...
=> [fix] Reduce right given to ynh users with ssh

data/helpers.d/apt
We regularly have dependency issues with apt and apt is absolutely fucking stupid and lazy about explaining what the hell actually is going on... There's currently a mechanism that tries to explicitly `apt install --dry-run` all the dependencies of the app such that apt spits out some relevant info... However it fails in multiple case because : 
- it tries to install all dependencies and not just the problematic ones, which dilute the relevant info
- it doesnt properly handle cases where `bar1 | bar2` is requested ... which may generated red-herrings if bar2 is, like, a dependency only available on stretch but you're on buster, or vice-versa
Grep what are the problematic packages from dpkg's log (lines like `foo-ynh-deps depends on bar ; however:`) and try to `apt install --dry-run` these …
=> [enh] Better problematic apt dependencies auto-investigation mechanism

data/hooks/conf_regen/10-apt, data/hooks/diagnosis/00-basesystem.py, locales/en.json
We regularly see people with failed app installs or other things, related to the fact that libssl1.1 is installed from sury, but not libssl-dev (or viceversa).
It's difficult to automatically downgrade the packages, but at least we can diagnose and recommend to people the right command to fix their setup
Tested on my side
Create a situation where libssl-dev and/or libssl1.1 is installed from sury, then run the diagnosis for "basesystem"
=> Diagnose ssl libs installed from sury

data/helpers.d/getopts
getops can enter in an infinite loop when using only one `-` when two are expected: https://github.com/YunoHost/yunohost/commit/15a7967f474be96d27381ecb739ac4ae09d243e9
Detect this case, and die!
...
...
=> [fix] detect misformated arguments in getopts

data/actionsmap/yunohost.yml, src/yunohost/backup.py
c.f. https://github.com/YunoHost/issues/issues/838
Currently backup can't be downloaded from the webadmin which is kind of "not cool" and not practical
Implement that possibility ... the tricky part is that moulinette is built such that it calls the python functions and expect to get serializable data like lists, dict ... so how exactly are you supposed to return a file ?
Solved this by adding the possibility in the moulinette to return a raw HTTP reponse, and using `bottle.static_file` to return the requested archive file.
(Initially I was investigating the use of X-Accel-Redirect but so far doesn't seem to be needed ? I wouldn't be able to tell what's better from a technical point of view though)
Done
Fetch the relevant PRs (c.f. …
=> Add possibility to download backups

data/helpers.d/backup
cf. https://github.com/YunoHost-Apps/nextcloud_ynh/issues/302
When backing up an app with `BACKUP_CORE_ONLY=1 yunohost backup create --apps APP`, the line stating that BACKUP_CORE_ONLY is set is sent to stderr.
It's very annoying when backups are made via the crontab and error output is sent by email... A lot of email containing only this line... which is not an error btw ;)
...
Send this message to standard output
It seems that this was the cas before (https://github.com/YunoHost/yunohost/commit/68c30a943a9ef06c58553e3982226be19bef6c8d) but I haven't figure out why there has been this change (so maybe I'm missing something !)
...
...
Backup an app with BACKUP_CORE_ONLY
e.g. `BACKUP_CORE_ONLY=1 yunohost backup create --apps nextcloud`
...
=> move BACKUP_CORE_ONLY message to standard output

data/helpers.d/utils
This function was supposed to be able to read from the manifest (see usage and documentation), but actually was only parsing an env var, thus breaking ynh_check_app_version_changed
Restoring the capacity to read a manifest
=> Fix ynh_app_upstream_version : restore ability to read manifest

src/yunohost/domain.py
Domains are randomly displayed when running "yunohost domain list"
yunohost/issues#1355
Sort domains alphabetically, by top domains
...
Add many domains and subdomains
Run "yunohost domain list"
=> [enh] Sort alphabetically the domain list

bin/yunoprompt
We display fingerprint for ssh, but not for https. Displaying sha256 for x509 allows user to check their webadmin https before to set password during postinstall or login.
I choose to display only fingerprint for the default yunohost_admin panel (so the cert used by default in /etc/yunohost/certs/yunohost.org/crt.pem ).
User could check by doing: "display certificate" on firefox and check sha256 info.
```
__   __  __   __  __    _  _______  __   __  _______  _______  _______
|  | |  ||  | |  ||  |  | ||       ||  | |  ||       ||       ||       |
|  |_|  ||  | |  ||   |_| ||   _   ||  |_|  ||   _   ||  _____||_     _|
|       ||  |_|  ||       ||  | |  ||       ||  | |  || |_____   |   |
|_     _||       ||  _    ||  |_|  ||   _   ||  |_|  ||_____  |  |   |
|   |  |       || | |   || …
```
=> [enh] Add x509 fingerprint in /etc/issue

data/hooks/conf_regen/35-redis
The redis hook script contains an empty bash function. Bash does not support empty function.
Add a dummy instruction inside the function (equivalent to true)
Done
`yunohost tools regen-conf redis`
=> Fix redis hook (bash does not allow empty function)

debian/control
```
Info: [########++..........] > Upgrading dependencies...
Warning: debconf: delaying package configuration, since apt-utils is not installed
```
Install apt-utils to avoid this warning
Tested on lxd container
...
=> [fix] Avoid warning message during app install

data/templates/mysql/my.cnf
Nextcloud fail due to mysql queries refused with those message in log:
```
[Warning] Aborted connection 110060 to db: 'nextcloud' user: 'nextcloud' host: 'localhost' (Got a packet bigger than 'max_allowed_packet' bytes)
```
Update `max_allowed_packet` to the default value inside maraidb 10.3 (16M)
See https://mariadb.com/kb/en/server-system-variables/#max_allowed_packet
Ready
I don't know how to reproduce exactly the bug with nextcloud, i think it could be reproduced with image bigger than 1M inside user profil, but it's hypothetical.
Change max_allowed_packet has fixed the issue in my impacted ynh setup.
=> [fix] MySQL server has gone away in nextcloud

data/helpers.d/setting, src/yunohost/app.py
We can't use curl to finalize and installation during an install script ([for example](https://github.com/YunoHost-Apps/dotclear2_ynh/)
Set "/" during regitser url
...
Install [dotclear2](https://github.com/YunoHost-Apps/dotclear2_ynh/) with and without this patch
=> Set default url

src/yunohost/app.py, src/yunohost/tests/test_apps_arguments_parsing.py
For an optional password:
> Error: The password needs to be at least 8 characters long
Do not check if the password is strong enough if it's an optional parameter.
...
Install [jirafeau_ynh](https://github.com/YunoHost-Apps/jirafeau_ynh) and play with value of the optional password
=> Fix optional args

data/helpers.d/utils
In other places, we define the local variable, call `ynh_handle_getopts_args` then we assign a default value if needed
...
...
=> Keep helpers consistent

src/yunohost/app.py, src/yunohost/utils/legacy.py
c.f. https://github.com/YunoHost/issues/issues/1671
Yunohost should translate legacy rules in /etc/ssowat/conf.json.persistent into the new format
While actually looking into implementing the initial idea from last meeting, though (which was about "loading only conf.json and not .persistent anymore", I was concerned with the following : 
- this requires changing the code of ssowat (which is doable but meh)
- if you want to just change the theme or logging level, it's annoying for the user to have to run "yunohost app ssowatconf" - many people will forget about this
So for now I decided to *only* translate the legacy rules (unprotected_urls, etc...) into the new permission structure *inside* /etc/ssowat/conf.json.persistent, and to keep everything else working the way it's working now. …
=> Automatically translate legacy rules in /etc/ssowat/conf.json.persistent

src/yunohost/app.py
https://ci-apps-unstable.yunohost.org/ci/job/769
> yunohost app config show-panel wordpress
Warning: Warning: This feature is experimental and not considered stable, you should not use it unless you know what you are doing.
Info: The operation 'Show the config panel of the 'wordpress' app' could not be completed. Please share the full log of this operation using the command 'yunohost log display 20201125-164852-app_config_show_panel-wordpress --share' to get help
File "/usr/bin/yunohost", line 72, in <module>
parser=parser
File "/usr/lib/moulinette/yunohost/__init__.py", line 29, in cli
top_parser=parser
File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 120, in cli
args, output_as=output_as, timeout=timeout
File …
=> [fix] show config panel

locales/en.json, src/yunohost/app.py, src/yunohost/tests/test_apps_arguments_parsing.py
No number parser, used [here](https://github.com/YunoHost-Apps/wordpress_ynh/blob/e24fe50fccd27b403d5d51c299f72e3284dc1427/config_panel.toml#L54) for example
...
...
...
=> Add number arg parser

src/yunohost/app.py, src/yunohost/backup.py
c.f. for example : https://ci-apps-unstable.yunohost.org/ci/job/808
```
Backup of the application...
Start the LXC container.
Create witness files...
Working time: 6 seconds (08:08:01).
Working time: 6 seconds (08:08:07).
Backup successful. (0)
Info: yunohost.backup _collect_app_files - [918.1] Collecting files to be backed up for pgadmin...
Warning: yunohost.hook <lambda> - [918.1] /usr/share/yunohost/helpers.d/utils: line 587: YNH_APP_MANIFEST_VERSION: unbound variable
Error: yunohost.backup _collect_app_files - [918.1] Could not back up pgadmin
Info: yunohost.backup backup_create - [918.1] Creating a backup archive from the collected files...
```
The way we handle the env dict for app is a mess and should be unified to be consistent across all app operations. Hence I introduce a proper …
=> We need to have YNH_MANIFEST_VERSION also defined during backup/restore

data/helpers.d/php
When an app installs a bad php conf file, php-fpm gets reloaded and suddenly all php apps are down.
We can be a bit smarter than this and validate with `php-fpm7.3 --test` that the conf is alright before reloading the service
Well I ended up doing this because I broke hotspot with some related issue. You can reproduce it by installing hotspot_ynh from the commit dc7139bed4ada8bf4bc90cf163767d8cf2a63675 ... Or any other php app with a broken php config.
Without this patch, the install fails and php7.3-fpm is down after the operation finishes. With this patch, the php7.3-fpm service doesn't get reloaded and is still up (and the bad config file gets removed even if the packager forgot to remove it in the 'remove ' script)
=> [fix] ynh_add_fpm_config: Do not reload php-fpm if conf breaks it

src/yunohost/certificate.py
https://forum.yunohost.org/t/probleme-lors-renouvellement-certificat-lets-encrypt-issue-during-lets-encrypt-renewal/13478/5
Change name of certificate.
Example of a new certificate : 
```
>>> print(issuer)
{'countryName': 'US', 'organizationName': "Let's Encrypt", 'commonName': 'R3'}
```
...
...
=> [FIX] New CN for LE.

src/yunohost/domain.py
From cli, it's possible to get a DNS conf for a domain not added. In this case, the dkim dns rules are not added. A simple typo in cli and the user configure the DNS badly.
Check the domain is in the listed of domain added
Tested and ready
```
yunohost domain dns-conf unknowndomain.local
```
=> [fix] DNS conf

data/hooks/backup/22-conf_mail, data/hooks/restore/22-conf_mail
In some case, during a restore operation, it could be possible _rspamd user have not the same id on a a new server. So we are not sure permission are ok
Redefine permission on each dkim file during restore operation
Ready
...
=> [fix] Unix permission on dkim

data/templates/dnsmasq/domain.tpl
Adding a domain avoid to be able to ping a subdomain on another machine
Use host-record instead of address
Ready (tested just by changing the file in a server)
```
yunohost domain add wikipedia.org
dig +short A wikipedia.org
dig +short A fr.wikipedia.org
```
=> [fix] Avoid to define the ip on wildcard subdomains too

data/templates/postfix/main.cf
It's possible to send mail to a lot of recipient.
Limit to 150 recipients.
Ready
...
=> [fix] Avoid too many recipient

src/yunohost/app.py, src/yunohost/utils/legacy.py
The ssowat conf is aimed to be modified by a human, an inline json is not easy to edit
Use `write_to_json` function, and use some [new parameters](https://github.com/YunoHost/moulinette/pull/261)
...
...
=> indent ssow conf

data/helpers.d/php
We don't handle the change of php version of an app, and if a custom version was installed, it's never uninstalled
Remove the old phpfpm conf (and php-fpm package if not needed)
Done
Tested with nextcloud (install an old version which used php7.2, and upgrade it with this new helper)
=> handle change php version

src/yunohost/utils/legacy.py
After migration, nobody can access to a `protected_uris` in ssowat `conf.json.persistent`
Add all users in this permission.
Should we add it to `skipped_urls` and `unprotected_urls`?
...
...
=> add all_users in protected_urls

src/yunohost/certificate.py
- LE changed the CN: https://letsencrypt.org/2020/09/17/new-root-and-intermediates.html
- Staging fails
- Use the organization name instead of the commonName: https://www.pyopenssl.org/en/stable/api/crypto.html?highlight=get_issuer#OpenSSL.crypto.X509Name
- Update the stating url
...
...
=> Use organization name for le cert

data/templates/slapd/ldap.conf
https://forum.yunohost.org/t/error-ldap-size-limit-exceeded/13332
Default size limit is ~500
Increase the (client?) size limit to 10000
Not sure what i'm doing :s 
Uuuuugh gotta test adding 500 users I suppose @_@
=> Increase ldap size limit?

data/helpers.d/php
When we run `systemctl reload-or-restart php7.3-fpm` too fast, the service may end up being stopped.
(Try: `systemctl reload-or-restart php7.3-fpm && systemctl reload-or-restart php7.3-fpm && systemctl reload-or-restart php7.3-fpm && systemctl reload-or-restart php7.3-fpm` then `systemctl status php7.3-fpm`)
Avoid 2 reload for nothing (Should we reload right before the `ynh_die`?)
...
...
=> do not reload php7.3 too fast

src/yunohost/backup.py, src/yunohost/utils/legacy.py
https://github.com/YunoHost-Apps/nextcloud_ynh/pull/346#issuecomment-751996938
> YunoHost tile is still absent
Set `show_tile` to `True` 
...
...
=> fix legacy permission migration

data/helpers.d/apt
c.f. https://forum.yunohost.org/t/impossible-de-mettre-a-jour-openssl/13717
That was a while since we didn't hear of Sury issue ... This was due to installing Firefly : 
```
ERROR - Packagers /!\ This app manually modified some system configuration files! This should not happen! If you need to do so, you should implement a proper conf_regen hook. Those configuration were affected:
- /etc/apt/preferences.d/extra_php_version
```
Though in fact my understanding is that it's because Firefly requires php 7.4 which therefore triggers the sury helpers, in turn messing with ` /etc/apt/preferences.d/extra_php_version` ... so adding an ugly if should do the trick
Yolocommited
Installing Firefly I guess @_@
=> Don't mess with Sury's pinning

src/yunohost/app.py
When listing the applications with `yunohost app list` we don't show by default were the application is installed. People end up having to learn about the existence of `yunohost app map` just for that and it's a bit stupid (and it doesn't display the same information).
Add, when domain and path is available for an app, the `domain_path` key like this:
Just do a `yunohost app list`
=> [enh] display domain_path of app on app list

src/yunohost/permission.py
This creates a lot of unecessary call and creates spaguetti code which prevents us from doing other modifications to fix a bug in app_info
Uses a more specialized function.
Working
`yunohost user permission list`
=> [mod] avoid calling app_list in user_permission_list

src/yunohost/app.py
`app_info(app)["name"]` was returning the label of the app in the manifest which was the label from the app catalog, not the real label of the app that could have been changed.
Only generic labels ^
Grab the real label, fall back on the manifest one if none is here.
New custom label for last app my_webapp__3 ^
Working, need previous branch avoid_calling_app_list_in_user_permission_list
Have apps with custom labels, then "yunohost app list" or "yunohost app info the_app_id"
=> [fix] key name of app label wasn't the real label

locales/en.json, src/yunohost/domain.py
Only app idea is shown on "yunohost domain remove" on an domain with apps installed on it.
This is problematic especially in the admin because the app id isn't show but the domain is.
Before ^
Display the app label.
Also suggest to change-url instead.
Also tells which command to uses.
After ^
Working
`yunohost domain remove some_domain_with_apps.tld`
=> [mod] also display app label on remove_domain with apps

src/yunohost/app.py
In some cases, Yunohost may tell the user that some upgrade is available, which in fact introduces regressions to the app. For example libreto was level 7 but recently dropped to level 2, then breaking backup etc...
Only advertise upgrades for good-quality apps
Yolocommited but should be working
Eeeh idk try to install some bad quality apps and check if the "upgradable" key in "yunohost app info <theapp>" is "bad_quality"
=> Do not advertise upgrades for bad-quality apps

data/actionsmap/yunohost.yml, src/yunohost/user.py
To update a user password in CLI, the only way is to write the new password in clear using "yunohost user update username -p new_password". This puts the new password in clear in some logs. This is issue https://github.com/YunoHost/issues/issues/714.
This PR allows to call the "yunohost user update" command with option -p but without an argument, in which case the admin is prompted for the new password.
Ready for tests.
...
=> [enh] in order to be able to change user password in CLI without writing it in clear (issue #714)

src/yunohost/firewall.py
miniupnpc uses a random source port by default, the issue is that the
firewall rule to allow destination port 1900 incoming is unused because
the UPnP server will use the random source port as destination port in
the reply which iptables will block. Forcing the source port to be 1900
will ensure the UPnP server also uses that as destination port in the
reply and pass the firewall.
python-miniupnpc 2.0 or later is required for this change to have any
effect, it is otherwise silently ignored. A debian package upgrade is in
the works for official Yunohost repos.
Closes https://github.com/YunoHost/issues/issues/1463
=> firewall: force source port for UPnP.

src/yunohost/utils/password.py
Issue #[1534](https://github.com/YunoHost/issues/issues/1435)
Add the -F flag to the grep command.
...
...
=> Add the -F flag to prevent grep from using the user password as a regex pattern

src/yunohost/app.py, src/yunohost/tests/test_apps_arguments_parsing.py
https://github.com/YunoHost/issues/issues/1709
> We used to set values to true or false but it doesn't accept it anymore, returning "Use one of these choices 'yes, no, y, n, 1, 0' 
Add `true` and `false` string as possible answer
...
...
=> fix boolean arg parse

src/yunohost/app.py, src/yunohost/tests/test_apps_arguments_parsing.py
https://github.com/YunoHost/issues/issues/1709
> "Error while parsing password argument 'YNH_CONFIG_MAIN_ENCRYPTION_ENCRYPTION_PWD': password argument can't have a default value for security reason" while main.encryption.encryption_pwd has optional = true
If the default value is an empty string, set it to `None`. ¯\\\_(ツ)\_/¯
...
...
=> fix default arg parse for password

src/yunohost/dyndns.py
So i finally got fed up with yunohost's dyndns cron job flooding mails when ns0.yunohost.org (our bind9) is down (or just because considering the cron job runs every 2 minutes, at some point a dig command will fail for whatever reason and will result in an email being sent)
The email content is not pretty:
```
File "/usr/bin/yunohost", line 72, in <module>
parser=parser
File "/usr/lib/moulinette/yunohost/__init__.py", line 29, in cli
top_parser=parser
File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 120, in cli
args, output_as=output_as, timeout=timeout
File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 477, in run
File …
```
=> Make dyndns update more resilient to ns0.yunohost.org being down

src/yunohost/app.py
Hmpf c.f. https://github.com/YunoHost-Apps/nextcloud_ynh/issues/362
Old setups before we properly normalized domain/path may still have some `path` settings ending with a trailing `/` resulting in stupid issue unless the app uses `ynh_normalize_path` (which they did, but i recently advised they don't because i though this issue was longtime gone but it's not >_>)
Yolofix the damn setting on each _get_app_setting so that we can later remove this bullshit ...
To be backported and released as hotfix on 4.1.x...
Yolocommited
Zblerg
=> Stupid yolopatch for not-normalized app path settings >_>

src/yunohost/app.py, src/yunohost/utils/error.py
c.f. https://github.com/YunoHost/issues/issues/1575
During failed app installs, we want to be able to return the log id to the API, such that it redirects the user to the relevant page instead of the current behavior where the user has to click a link ...
[Tweak the moulinette](https://github.com/YunoHost/moulinette/pull/257) and YunohostError code such that we can return the log id to the API, which is then to be caught by the webadmin
Tested and working on my side (though not integrated in the webadmin so far)
From the webadmin, trigger an app install error, and check in the network debug of the browser that the request answers contains a proper json with the log reference
=> Support more complex errors (be able to return additional data in a json structure)

data/actionsmap/yunohost.yml, debian/postinst, locales/ca.json, locales/de.json, locales/en.json, locales/eo.json, locales/es.json, locales/fr.json, locales/it.json, locales/nb_NO.json, locales/oc.json, src/yunohost/log.py, src/yunohost/tools.py
Rename, aliases etc
Gotta adapt some stuff in webadmin too ...
Run the commands idk
=> Misc command rename and alias

data/actionsmap/yunohost.yml, src/yunohost/app.py
According to the issue https://github.com/YunoHost/issues/issues/1360 there is no such search function as one would expect before installing anything
Create a simple function to search in the YunoHost app catalog, in the app name or description
Ready to test
It defines a new command which you can use as :
yunohost app search [string]
for example :
yunohost app search caldav
yunohost app search agendav
=> Define a new "yunohost app search" command

src/yunohost/certificate.py
Can't install let's encrypt certificat, error message is
```
2375 DEBUG To view the log of the operation 'Regenerate system configurations 'dnsmasq'', use the command 'yunohost log show 20210127-094059-regen_conf-dnsmasq20210127-094059-regen_conf-dnsmasq'
2375 DEBUG + exit 0
2394 DEBUG Prepare key and certificate signing request (CSR) for domain.tld...
2625 ERROR Certificate installation for domain.tld failed !
Exception: write() argument must be str, not bytes
```
- Encode str to bytes when necessary
- Open file in binary mode to write bytes 
Tested on new install from ynh-dev
`yunohost domain cert-install domain.tld`
or
`yunohost domain cert-install domain.tld --force`
=> Fix let's encrypt certificat generation

debian/postinst, src/yunohost/tools.py
Once more today, saw this issue where /etc/yunohost/installed mysteriously disappeared following some failed stuff ... (as well as yunohost-admin getting uninstalled ... why the hell ?!). Then user reinstalled yunohost-admin, and the webadmin was like "hey let's run the postinstall" which then miserably crashed
Test at the beginning of the postinstall if /etc/yunohost/apps exists, and abort if there's at least one app folder inside ... That should be a decent indicator that the system was postinstalled in the past and something funky happened
Yolocommited
Idk try to run postinstall with non-empty /etc/yunohost/apps
=> Abort postinstall if /etc/yunohost/apps ain't empty

data/helpers.d/fail2ban, data/helpers.d/nginx, data/helpers.d/php, data/helpers.d/systemd, data/helpers.d/utils
Conf handling is a mess, we have tons of ynh_replace_string all over the place, and some ugly --othervar options to replace "other vars", lack of consistency, etc
Use the new `ynh_add_config` helper to consistently handle template hydration (and backup/save of the checksum ugh)
Yolocommited
Gotta install some apps idk
=> Normalize conf template handling for nginx, php-fpm, systemd and fail2ban using ynh_add_config

data/hooks/conf_regen/02-ssl, locales/en.json, src/yunohost/domain.py, src/yunohost/tools.py
Postinstall is a bit lengthy and complex and the local CA management is a huge mess with bits everywhere. 
This is an attempt to simplify / uniformize most aspects of the local CA management, and also one of the first pieces towargs heavy simplification of the postinstall process as a whole
Kind of tested but I'm battling with slapd which refuses to let me re-run the postinstall -_- ...
Run the postinstall and also test changing the main domain, see if that's correctly propagated on the local CA
=> Refactor local CA management for more consistency and simpler postinstall

.gitlab/ci/lint.gitlab-ci.yml, data/hooks/diagnosis/10-ip.py, data/hooks/diagnosis/21-web.py, doc/generate_helper_doc.py, src/yunohost/app.py, src/yunohost/data_migrations/0015_migrate_to_buster.py, src/yunohost/domain.py, src/yunohost/hook.py, src/yunohost/log.py, src/yunohost/permission.py, src/yunohost/tests/test_apps_arguments_parsing.py, src/yunohost/tests/test_appurl.py, src/yunohost/tests/test_permission.py, src/yunohost/tools.py, src/yunohost/utils/packages.py, src/yunohost/utils/yunopaste.py
Fix all errors in the linter
I'm not sure about what I did in the file [src/yunohost/domain.py](https://github.com/YunoHost/yunohost/blob/bfd7257a8c886081d5a54880215e2f839772b34b/src/yunohost/domain.py#L607-L624)
Do we really want to remove `allow_failure: true`?
...
...
=> fix linter, remove allow_failure for corresponding tests

src/yunohost/utils/legacy.py
Some apps have an admin part , we want this part to be protected. The current migration code could accidentally expose publicly this part.
Don't give the admin permission to the same user with main permissions
Ready
...
=> [fix] Avoid admin part of apps to be reachable from visitors

data/helpers.d/multimedia, data/hooks/post_user_create/ynh_multimedia, data/hooks/post_user_delete/ynh_multimedia, debian/control
Multimedia helpers are overly complex, downloading stuff from an external repo (why?) just to have a bunch of helper/hooks ...
Also today an user reported this https://forum.yunohost.org/t/cant-install-app-transmission-nextcloud/13826 where everything exploded because of unecessary sudos all over the place ...
Add the multimedia helpers and hooks in the core ...
This supersedes https://github.com/YunoHost/yunohost/pull/525
Note that I did not port `ynh_multimedia_movefolder` because it doesn't seem to be used in any app
Yolo commited, not tested
Try to install an app that rely on the multimedia helpers. In fact not so many of them do : airsonic, (ampache), calibreweb, couchpotato, minidlna, navidrome, nextcloud, transmission
=> Add multimedia helpers and hooks

data/helpers.d/fail2ban, data/helpers.d/nginx, data/helpers.d/php, data/helpers.d/systemd, data/helpers.d/utils, src/yunohost/backup.py
c.f. regressions mentioned in https://github.com/YunoHost/issues/issues/1732
Some conf file were not found because of the usage of the new ynh_add_config trying to use some file in ../conf in the context of backup/restore scripts
Define a new variable YNH_APP_BASEDIR which points to `..` or `../settings` depending if we're in backup/restore context or not, to simplify the handling of this issue
Had to make sure that the backup script was indeed called "backup" when we actually run it
Install/backup an app
=> Define YNH_APP_BASEDIR to be able to properly point to conf folder depending on the app script we're running

data/helpers.d/utils
c.f. the current issue in 4.2 where adding fail2ban config create weirds issue (cant compile regex)
We need to escape possible \ in the strings we replace in templates.
I guess we don't do this in ynh_replace_string because it may be used for regexes etc, but in the context of ynh_add_config we probably always have fixed strings.
Tested on my side
Try to install an app with fail2ban config, such as Nextcloud, with and without this fix
=> Gotta escape \ during ynh_replace_vars

data/helpers.d/backup, data/helpers.d/permission, data/helpers.d/user, data/helpers.d/utils
Idk while debugging stuff on ci-apps-unstable, realized we have many helpers relying on dirty scraping with grep
Use `jq` for robustness ... that's not trivial but at least json is a better interface between programs and less prone to stupid edge case like grepping stuff you weren't expecting ...
Zblerg idk i just ran commands manually
=> Use jq / output-as json to get info from yunohost commands instead of scraping with grep

data/helpers.d/systemd
- We use `ynh_systemd_action` in some helpers, which requires calling `ynh_clean_check_starting` in the exit function
- `ynh_clean_check_starting` tries to kill remains process created by `ynh_systemd_action`, but variables used to store the pid is in the local scope, idk how this ever work. https://github.com/YunoHost/yunohost/blob/1d3380415eca14ea9291d3b29fbf326111077e68/data/helpers.d/systemd#L96 https://github.com/YunoHost/yunohost/blob/1d3380415eca14ea9291d3b29fbf326111077e68/data/helpers.d/systemd#L89
https://github.com/YunoHost/yunohost/blob/1d3380415eca14ea9291d3b29fbf326111077e68/data/helpers.d/systemd#L170-L178
Call `ynh_clean_check_starting` just before returning 1
Set `ynh_clean_check_starting` as internal. Packagers shouldn't handle our mess :-)
...
...
=> [fix] Automatically call ynh_clean_check_starting when ynh_systemd_action fails

data/helpers.d/utils
When using ynh_add_config, if destination file already exist, it's not overwritten
just forcing
Ready
...
=> [enh] - Force destination to be replaced

data/helpers.d/utils
ynh_add_config is unable to manage something like `__DOMAIN____PATH_URL__`
CF [Job #502 wikijs (PR #134, example)](https://ci-apps-dev.yunohost.org/ci/job/502)
The corresponding lines of the script:
https://github.com/YunoHost-Apps/wikijs_ynh/blob/2a8db83a45f9ebdd9c03b461827f45a81b50db3b/scripts/install#L185-L191
And the file on which ynh_add_config is applyed:
https://github.com/YunoHost-Apps/wikijs_ynh/blob/example/conf/ldap_message
Make finding the `unique_vars` lazy
Tested
Actual fail with https://github.com/YunoHost-Apps/wikijs_ynh/tree/example :
https://paste.yunohost.org/savilagari.sql
the with lazy grep https://github.com/YunoHost-Apps/wikijs_ynh/pull/135:
https://paste.yunohost.org/aqukotiher.sql
=> Make grep lazy

data/helpers.d/utils
using ynh_add_config, `___APP__` is retrieved as `___APP__` instead of `__APP__`like at [Job #492 peertube (PR #204, example)](https://ci-apps-dev.yunohost.org/ci/job/492)
Making grep more accurate using [https://www.rexegg.com/regex-quantifiers.html](https://www.rexegg.com/regex-quantifiers.html)
- starting with `__`
- `[A-Z0-9]+?` lazy one or more of `[A-Z0-9]`
- `[A-Z0-9_]*?` lazy zero or more of `[A-Z0-9_]`
- `[A-Z0-9]*?` lazy zero or more of `[A-Z0-9]`
- ending with `__`
Will do a good match on :
`___APP__` => `__APP__`
`__DB_USER__` => `__DB_USER__`
`__DOMAIN____PATH_URL__` => `__DOMAIN__` and `__PATH_URL__`
`__BC__` => `__BC__`
`__A__` => `__A__`
`__YNH_NODE_LOAD_PATH__` => `__YNH_NODE_LOAD_PATH__`
`__APP_____DOMAIN__` => `__APP__` and `__DOMAIN__`
Ready
Create a text file named …
=> Fixing ___APP__

data/helpers.d/mysql, data/hooks/conf_regen/34-mysql, data/hooks/restore/11-conf_ynh_mysql, src/yunohost/tests/test_apps.py
Another change on top of the removal of the backup/restore of mysql password.
This one is a bit more touchy though ... so to be discussed.
The problem is that managing that mysql password in /etc/yunohost/mysql is a bit annoying (gotta call a damn dpkg-reconfigure to change or define it wtf) and it's actually a security risk to use it in command line as the password will show up to other unix users in `ps -ef` ... Same thing can be said for psql btw ...
As I realized today, we don't need to do this anymore. Mariadb ships a auth_socket/unix_socket plugin that allows to authenticate just from the fact that you're already root, which makes more sense than some funky password.
Adapt helpers to call `mysql` without password, and auto-migrate to enable unix_socket as auth plugin for root in the …
=> No need for mysql root password

src/yunohost/app.py, src/yunohost/backup.py, src/yunohost/certificate.py, src/yunohost/data_migrations/0017_postgresql_9p6_to_11.py, src/yunohost/diagnosis.py, src/yunohost/domain.py, src/yunohost/dyndns.py, src/yunohost/firewall.py, src/yunohost/hook.py, src/yunohost/log.py, src/yunohost/permission.py, src/yunohost/service.py, src/yunohost/settings.py, src/yunohost/ssh.py, src/yunohost/tools.py, src/yunohost/user.py, src/yunohost/utils/error.py, src/yunohost/utils/password.py, tests/test_i18n_keys.py
Follow-up of the rework of the webadmin in VueJS : there are some pretty obvious "bad UX" stuff in the way errors are handled ... which is in fact due to the lack of proper semantic for exceptions. Basically all MoulinetteError / YunohostError right now trigger a 400 error with no distinction between 
- "validation / form error" (for example trying to create a user that already exists, therefore interface should stay on the form and display the error there)
- "an app script miserably failed" (which should redirect to the corresponding log so hopefully people will share it)
See also https://github.com/YunoHost/moulinette/pull/271
- Introduce some `MoulinetteValidationError` and `YunohostValidationError` that corresponds to code 400 / Bad request.
- Classical `MoulinetteError` and …
=> Improve error semantic

data/helpers.d/utils
c.f. situations where app config files are supposedly tracked with a checksum, but using `ynh_setup_source` may overwrite them, defeating the entire purpose of the checksum stuff, Yunohost will later complain that the file got manually modified, etc.
People end up cp-ing the file elsewhere and cp-ing back to the /var/www/$app folder
Make it simpler using a `--keep="foo bar"` option for `ynh_setup_source`
Tested with helper unit tests bruh
Setup some sources, edit the file that should be overwritten, run `ynh_setup_source --keep="your.file"`, check that the file has not been overwritten
=> Add --keep to ynh_setup_source to keep files that may be overwritten during upgrades

data/helpers.d/utils
Today I was reading example_ynh and got mad after seeing some weird chown that I thought should be handled by the helpers directly instead of the packagers (at least we should have a decent default behavior)
After thinking about it, I realize that in many situations we probably have apps that do not correctly provide files or folders that may contain secrets .. hence they are world-readable and an attacker that has local a local shell on the machine could use this for privilege escalation.
Thing is, there seem to be a lot of focus on `chown` but it's easy to forget about `chmod` and the fact that by default files/folders are readable by `others` ... In fact, example_ynh currently recommends to `chown root: $final_path` ... This may sound like "SeCuRiTy HeLl Yeah !?" because you set the …
=> Sane default permissions for files added using ynh_add_config and ynh_setup_source

src/yunohost/log.py
https://forum.yunohost.org/t/borg-borg-server-deduplicated-encrypted-and-remote-backups/5006/29?u=ljf
Add passphrase to the banned keywords list
Yolo PR
Upgrade borg and search your password
=> [fix] Remove passphrase keyword from logs

data/templates/postfix/main.cf
The configuration of an SMTP relay supporting only SMTPS and not STARTTLS is not functional.
Issue [1725](https://github.com/YunoHost/issues/issues/1725)
Add `smtp_tls_security_level = encrypt` and `smtp_tls_wrappermode = yes` when `smtp.relay.port` is set to `465`.
...
...
=> [enh] Support SMTPS Relay

data/templates/nginx/security.conf.inc
Google is starting to use FLoC and it's a privacy nightmare, see https://www.eff.org/deeplinks/2021/03/google-testing-its-controversial-new-ad-targeting-tech-millions-browsers-heres
While destroying google would be a great thing in the meantime we can apparently disallow it using a nginx header, see https://diaspodon.fr/@etienne/106070042112522839
Tested on my prod and used https://securityheaders.com linked in the toot to see if it is working and the website is happy.
Apply the patch on your local nginx conf, reload nginx and check the headers or use security headers.
=> [enh] add header to disallow FLoC

data/actionsmap/yunohost.yml, locales/en.json, src/yunohost/backup.py
Going to the backup creation interface, there's no clue provided about the size of the to-be-created backup (which may also provide some clue about the time it'll take to create the archive, c.f. people backing up 100+GB of data)
Add a --dry-run option, meant to be used by the webadmin. Maybe we can implement a "Simulate" button or something on the webadmin that would add size annotations in the view. (We probably want this to be only triggered manually by the user because the dry-run ain't trivial, you still have to run all the app scripts to obtain the information of what's to be backedup, and there's also db dumps in the process)
Run `yunohost backup create --dry-run`
=> Add a --dry-run option to backup_create to fetch an estimate of the backup size

data/actionsmap/yunohost.yml, data/templates/nginx/plain/yunohost_admin.conf.inc, src/yunohost/app.py
c.f. https://github.com/YunoHost/issues/issues/1117
Currently, custom app install work by fetching **from the client** the raw manifest.json. This was good enough so far but recently break after I started advising removing the superflous ask strings ... But also it worked with tight-coupling to raw.githubuserstuff.com, etc
Add a `yunohost app manifest foobar`, which can also be fed an url, and is meant to be used by the API such that the backends fetch the manifest in a forge-agnostic way.
c.f. corresponding PR on yunohost-admin
=> Add route to fetch app manifest for custom app installs in a forge-agnostic way

data/helpers.d/utils, src/yunohost/app.py
After upgrade an app a copy of all scripts/* files into `/etc/yunohost/apps/$app/scripts` is performed.
If the app download (with the `ynh_setup_source` helper or not) a file in .tar.gz we can't remove it anymore with an error like:
```
root@domain:/ynh-dev# yunohost app remove lxd --debug
59   DEBUG initializing base actions map parser for cli
59   DEBUG loading actions map namespace 'yunohost'
60   DEBUG building parser...
67   DEBUG building parser took 0.006s
67   DEBUG acquiring lock...
73   DEBUG lock has been acquired
78   DEBUG loading python module yunohost.app took 0.005s
78   DEBUG processing action [406724.1]: yunohost.app.remove with args={'app': 'lxd'}
82   INFO Removing lxd...
171  INFO The operation 'Remove the 'lxd' app' could not be completed. Please share the full log …
```
=> Remove src filename

data/helpers.d/user, data/hooks/conf_regen/01-yunohost, data/templates/ssh/sshd_config
https://github.com/YunoHost/issues/issues/1784
Introduce new ssh.app and sftp.app groups
Apps can add their system user to this group by adding for example `--groups="ssh.app"` to `ynh_system_user_create`
Though we'll have to create PR to propagate that change on borg, restic, my_webapp
Zblerg idk, run the regen-conf, run the unit test for ynh_system_user_create, try to connect with the created user
=> Add ssh.app, sftp.app groups to cover my_webapp and borg needing ssh access

data/helpers.d/systemd
When upgrading an app, if the service is stopped or broken and the upgrade has `ynh_systemd_action --service_name=$app --action="stop"` with`--line_match="SOMETHING"`, the upgrade will fail because the line_math won't complete
having `ynh_systemd_action` checkingf if the service is already stopped
Ready
choose an app with an upgrade step `ynh_systemd_action --service_name=$app --action="stop" --line_match="SOMETHING"` => for example pleroma, mobilizon, wikijs, etc ...
install a previous version of the app on a fresh yunohost
stop the app service
try to upgrade, it will fail
install a previous version of the app on a fresh yunohost
stop the app service
apply the patch
try to upgrade, it will work ...
=> ynh_systemd_action: Fix case where service is already stopped

src/yunohost/app.py
Some end users received warning dedicated to packagers.
Remove it. 
Those warnings are in linter
...
=> [fix] Remove warning to user (transfered in linter)

data/helpers.d/utils
Ping @alexAubin :)
As a relative path that may lead to problems when ynh_setup_source is called after a `cd`.
=> Set YNH_APP_BASEDIR as an absolute path

data/templates/dnsmasq/plain/resolv.dnsmasq.conf, src/yunohost/utils/network.py
With 10 domains, and if shuffle of dns query put some down DNS resolver, we could wait diagnosis too much.
We have used resolver.timeout instead of resolver.lifetime...
https://www.dnspython.org/docs/1.16.0/dns.resolver-pysrc.html
Remove some "blinker" resolvers.
Ready
...
=> [fix] Diagnosis dns query taking an awful amount of time because of timeout

data/templates/postfix/main.cf
YunoHost refuses email attachment bigger than 21,8MB
Take into account the base64 transformation
Ready
Send an email with a 24MB attachment
=> [enh] Accept attachment of 25MB instead of 21,8MB

data/helpers.d/systemd
systemd action helper supposedly displays a message to warn that `the service xxx is starting` with a bunch of dots at the end as the script waits for the operation to finish or timeout
Except it's using `echo -n`, which doesn't flush the output and doesn't interface properly with the way Yunohost handle messages, thus the message is only displayed *after* the completion/timeout, which is pointless
Just display a "this is gonna take some time" message when we reach 30 sec
Yolocommited
Idk start a service that doesn't really start
=> Tweak ynh_systemd_action message : echo -n is pointless

data/templates/metronome/metronome.cfg.lua
As XMPP client encrypt the messages, optimization on server side like "dont forward the message to inactive client only if there is their name in the message's content" does not work.
deactivate the optimization
PENDING test
- Open your preferred client, put it in the background, wait to see "signaling client is inactive"
- Send an encrypted message to a group containing the first user
- Wait for the message to arrive. It should arrive really late
- Apply the change
- The message should arrive quickly
=> [metronome/xmpp] deactivate stanza mention optimization / have quick notification in chat group

data/templates/metronome/metronome.cfg.lua
Pub sub XEP060 allow several features see https://xmpp.org/extensions/xep-0060.html
Some problems happens when not activated:
- Avatars are not synchronized when contacts are not connected
- OMEMO need PUBSUB XEP060 and XEP0163 to correctly exchange keys https://xmpp.org/extensions/xep-0384.html#intro-overview 
Activate the module
Config done, PENDING approval
publish a new avatar, see if it synchronize with other device
connect a new user with a new device, disconnect it talk to him/her with OMEMO activated. message should be correctly encrypted even for the disconnected devices.
=> [metronome] activate module pubsub

src/yunohost/backup.py
Bindings created by some backup methods appears with their 'real' path in /etc/mtab, that may differ from the original /home/yunohost.backup/tmp/auto_xxx that is passed to _recursive_umount().
Traced as https://github.com/YunoHost/issues/issues/1809#issue-899123573
This fix applies realpath to the 'directory' parameter passed to _recursive_umount().
Tested OK on my own instance, where backups with Borg were failing (except the first one after a reboot) because of this issue (it was unable to clean temporary dir).
=> Apply realpath to find mounted points to unmount

.gitlab/ci/test.gitlab-ci.yml
The pipeline is slow. We could simply trigger jobs when the files involved change to speed it up.
We could simply trigger jobs when the files involved change to speed it up. Keep `root-tests` and `full-tests` running all the time
Doc: https://docs.gitlab.com/ee/ci/yaml/#only--except
To be merged before https://github.com/YunoHost/yunohost/pull/1249
...
...
=> ci triggered only on file changed

.gitlab-ci.yml, .gitlab/ci/test.gitlab-ci.yml, .gitlab/ci/translation.gitlab-ci.yml
- run the translation stage + tests on the translation keys only when the locale files have changed
- automatically run `remove_stale_translated_strings.py` (should we move this script to the `locales` folder?)
- split root-tests
- run test_helpers in full-tests
...
...
=> Move some tests

src/yunohost/ssh.py
`.ssh/` is created with `777` and break publickey authentication.
Fix YunoHost/issues#1770
Set permissions to 600.
I use `chmod()` instead of setting `mode=0o600` in `mkdir()` in hope this will magically fix someone's folder.
Tested with ynh-dev. :ok_hand:
Use `yunohost user ssh add-key`
=> [fix] set .ssh folder permissions to 600

src/yunohost/app.py
The functionality brought by PR https://github.com/YunoHost/yunohost/pull/1070 is not working anymore since Python3 I think, because of an `RuntimeError: dictionary changed size during iteration` error.
Use a new dictionary to store matching apps
Ready to review
yunohost app search [string]
for example :
yunohost app search caldav
yunohost app search agendav
=> [fix] yunohost app search fail because of dictionary error

data/helpers.d/php
Sometime composer doesn't have enough memory:
- Fix https://github.com/YunoHost-Apps/pixelfed_ynh/issues/145
- https://forum.yunohost.org/t/installation-drupal-impossible/16683
Increase memory limit: https://joshtronic.com/2020/05/25/increase-memory-list-for-composer/
Ready
...
=> Composer without limit

src/yunohost/domain.py
https://yunohost.org/en/administrate/overview/domains#non-latin-characters
Add an automatic conversion.
Here i do it just on add action. It could be made on all action with a domain argument AND reconvert the domain when it is displayed, however i think this PR is a minimal fix for this issue.
Tested in ynh-dev by adding domain café.com via cli.
Waiting automated test
...
=> [fix] Better support for non latin domain name

data/hooks/conf_regen/15-nginx, data/templates/nginx/yunohost_admin.conf.inc, data/templates/nginx/yunohost_api.conf.inc, locales/en.json, src/yunohost/settings.py
There's no way to allow webadmin access to some IP only.
https://github.com/YunoHost/issues/issues/1273
This PR add settings to enable and set the allow-list. This setting modify nginx config (`yunohost_admin.conf.inc` and `yunohost_api.conf.inc` with regenconf.
The allow-list is a list of IP, coma separated.
Tested with ynh-dev and working :ok_hand:.
There's one thing I'm not happy with, when a user set the `security.webadmin.allowlist` with an incorrect value (`192.10.0.0.`), the nginx config is changed even if `nginx -t` fails.
I could add some regexp in `settings.py`, near the type checks, but I'm not really ok with this solution.
Checkout this PR with ynh-dev and you can enable with :
```
yunohost settings set security.webadmin.allowlist -v True
yunohost settings set …
```
=> [enh] Add settings to block webadmin from outside

data/hooks/conf_regen/01-yunohost
https://forum.yunohost.org/t/mettre-lecran-en-veille/14675/18
...
This settings has been tested by bykepunk in /etc/systemd/logind.conf. The same in /etc/systemd/logind.conf.d has not been tested but documentation speak about it (don't know if [login] should be added!)
...
=> [fix] Avoid to suspend server if we close lidswitch

data/actionsmap/yunohost_completion.py, data/helpers.d/setting, data/hooks/conf_regen/01-yunohost, doc/generate_manpages.py, src/yunohost/app.py, src/yunohost/firewall.py, src/yunohost/regenconf.py, src/yunohost/service.py, tests/test_actionmap.py, tests/test_i18n_keys.py
Cron flood my email since ??? with things like:
```
/usr/lib/moulinette/yunohost/service.py:673: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```
Even if our yaml are not really untrusted it could be safer to load these yaml with the SafeLoader.
I tried with BaseLoader however there are some important differences:
```
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> yaml.safe_load("5.10")
5.1
>>> yaml.load("5.10", Loader=yaml.BaseLoader)
'5.10'
>>> yaml.load("5.10")
5.1
```
safe_load is a shortcut for `yaml.load("5.10", Loader=yaml.SafeLoader)`
Not yet tested
...
=> [fix] Avoid warning and use safeloader

data/actionsmap/yunohost.yml, src/yunohost/app.py
- Add --no-safety-backup option to "yunohost app upgrade" (https://github.com/YunoHost/issues/issues/1856)
- (no webadmin part)
=> Add --no-safety-backup option to "yunohost app upgrade"

data/helpers.d/multimedia, data/hooks/post_user_create/ynh_multimedia
When multimedia helpers create symbolic link to home folder of a user, it does not check if the user indeed has a home folder, which gives [this problem](https://forum.yunohost.org/t/calibre-web-manage-your-ebooks/6499/94) in case there is not and fail install/upgrade script.
add a check in the helper and in the post_user_create hook that will:
1/check that the folder used as home in /etc/passwd exists
2/ check that this folder is located in /home/ folder
In this case, symbolic link is created, otherwise, only folders located in /home/yunohost.multimedia/$user are created/
...
Well, I tested it locally to check if helpers and hooks still works, and it seems that yes... I don't know what else to do?
=> [Enh]Multimedia helper: check home folder

src/yunohost/log.py
This [issue](https://github.com/YunoHost-Apps/mumbleserver_ynh/issues/44) for Mumbleserver shows logs with clear password on it. 
Either change the password variable in mumbleserver or add `passwd` to obfuscated list.
=> Add passwd to be obfuscated

data/hooks/backup/18-data_multimedia, data/hooks/restore/18-data_multimedia
Multimedia directory is not backup and i receive request from borg_ynh users about that
Add a hook for saving multimedia directory
About legacy management, i don't know exactly what to do between:
- Nothing the multimedia dir is included by default after upgrade to the new yunohost version (could be problematic with daily backup on some instances)
- Create a migration (with an explanation and ability to skip) that deactivate the multimedia backup by creating a .nobackup inside this dir 
- Don't include by default this hook on yunohost backup create action
Ready
...
=> [fix] Add backup for multimedia files

data/templates/mysql/my.cnf
Nextcloud can install with the previous settings, however it display an error page on some real servers.
Increase to the config used in debian mariadb package
https://github.com/MariaDB/server/blob/10.3/debian/additions/my.cnf#L56
Ready tested on sans-nuage.fr
...
=> [fix] sort_buffer_size too small to make nextcloud work

src/yunohost/app.py
For now, we have to get [the value of final_path](https://github.com/YunoHost/test_apps/blob/6c9cf102006ae5bd05e078e1bac8526de91acf3a/config_app_ynh/scripts/config#L17) when we define a config panel script
Define it in the core
...
...
=> avoid to retrieve final path in the config panel scripts

src/yunohost/permission.py
I'm trying to fix the `backup_wordpress_from_3p8` test and I hit another bug:
Trying to restore the backup:
```
Do you really want to restore an already installed system? [y/N]: y
Info: Preparing archive for restoration...
Info: Restoring wordpress...
Info: The operation 'Create permission 'wordpress'' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20210917-155022-permission_create-wordpress' to get help
Error: Could not restore wordpress: Something unexpected went wrong: 
File "/usr/lib/moulinette/yunohost/backup.py", line 1452, in _restore_app
sync_perm=False,
File "/usr/lib/moulinette/yunohost/log.py", line 417, in func_wrapper
result = func(*args, **kwargs)
File …
```
=> remove created permission if error

data/hooks/diagnosis/80-apps.py
The grep match the commented lines
For example: https://github.com/YunoHost-Apps/vaultwarden_ynh/blob/c233d94d76cae449630c59ce228b7a3c72f8fa12/scripts/ynh_handle_app_migration#L136
Remove the commented lines
...
...
=> [Fix] App diagnosis grep

data/hooks/conf_regen/01-yunohost, data/hooks/conf_regen/02-ssl, data/hooks/conf_regen/03-ssh, data/hooks/conf_regen/06-slapd, data/hooks/conf_regen/09-nslcd, data/hooks/conf_regen/10-apt, data/hooks/conf_regen/12-metronome, data/hooks/conf_regen/15-nginx, data/hooks/conf_regen/19-postfix, data/hooks/conf_regen/25-dovecot, data/hooks/conf_regen/31-rspamd, data/hooks/conf_regen/34-mysql, data/hooks/conf_regen/35-redis, data/hooks/conf_regen/37-mdns, data/hooks/conf_regen/43-dnsmasq, data/hooks/conf_regen/46-nsswitch, data/hooks/conf_regen/52-fail2ban, src/yunohost/regenconf.py
Regenconf is confusing enough, we don't need those 'FORCE' and 'DRY_RUN' args which are in fact never used, nor that ugly `case`
Just call `do_$1_regen ${@:2}`
Yolocommited
...
=> Simplify regen conf scripts

bin/yunomdns
* The tool was crashing when a bad ip was provided to Zeroconf (a global ipv6 for example)
* We were parsing the output of iproute, but there already exists some good python libraries that do the job.
* Use `ifaddr`.
* Also, do some cleanup on the main function:
* b_ips are not necessary (we can use the `parsed_addresses` argument of ServiceInfo
* Add Python3 type hints
=> Fix yunomdns

src/yunohost/app.py
In 4.3.1.1, when i try to upgrade Searx i have this error message:
```
File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 497, in process
ret = self.actionsmap.process(arguments, timeout=30, route=_route)
File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 597, in process
File "/usr/lib/moulinette/yunohost/app.py", line 511, in app_upgrade
new_app_src = app_dict["id"]
KeyError: 'id'
```
When i run the function `app_dict = app_info("searx", full=True)`, I can isolate several `id`s fields:
```json
{
"manifest": {
"id": "searx"
},
"settings": {
"id": "searx"
},
"from_catalog": {
"id": "searx",
"manifest": {
"id": "searx"
}
}
}
```
Use the manifest's one, but I'm not sure if we want that one or …
=> fix app upgrade

data/actionsmap/yunohost.yml, locales/en.json, src/yunohost/domain.py, src/yunohost/dyndns.py, src/yunohost/tools.py
Boring stuff in dyndns.py like the ability to specify a custom dyndns host ... and ability to specify what ipv4/ipv6 to push on dyndns update ...
Also lack of resilience when ns0.yunohost.org is down .. because it's mapped to dyndns.yunohost.org and hmpf
We don't need those, drop them to simplify the code ...
\+ add ns1.yunohost.org for resolver redundancy
Yolocommited
Zblerg try to subscribe / update a test dyndns domain
=> Drop some YAGNI in dyndns.py + improve resilience w.r.t. ns0 / ns1 being down

src/yunohost/log.py
When a failure occurs during the upgrade, the first ynh_exit is catched. That will be the one during the backup. So the logs abstract does not contain the code execution of the failure.
Find the last ynh_exit in the logs by using a reversed iterator of the lines.
UNTESTED only for review.
Try to upgrade an app whose upgrade script fails (after backup).
=> Fix dump_script_log_extract_for_debugging 

data/hooks/diagnosis/24-mail.py, data/other/dnsbl_list.yml
For some DNS Spam blacklists (e.g. hostkarma), an answer to the DNS query does not necessarily mean that the IP is blacklisted. The actual answer needs to be read to find out whether it's blacklist, whitelist, other...
Add a property `non_blacklisted_return_code` to the blacklist servers that tells which answers should not be interpreted as "back-listed", [as suggested by zamentur](https://github.com/YunoHost/issues/issues/1873#issuecomment-917407489).
I only added the return codes for hostkarma, because it's the server that was affecting my instance. Any other that I should add?
c.f. comment linked above
=> [fix] Read DNS Blacklist answer and compare it against list of non-BL codes

src/yunohost/app.py, src/yunohost/tests/test_appurl.py
Closes https://github.com/YunoHost/issues/issues/1931
Some Git forges like SourceHut use tildes `~` to refer to usernames.
Allow tildes in the app repo URL regex.
Regex tested but not "live".
`yunohost app install https://git.sr.ht/~michalr/convos_ynh`
🤞
=> Allow tilde in username/organization for repo URLs

data/hooks/restore/18-data_multimedia
The restore of the multimedia folders doesn't work because we backup it with:
https://github.com/YunoHost/yunohost/blob/6854f23cca74fad1b131f5bdec7d92c7cc62aec4/data/hooks/backup/18-data_multimedia#L10
But during the restore, the script will search for something like `home/yunohost.multimedia`
Here some logs:
> 9272 DEBUG + ynh_restore_file --origin_path=/home/yunohost.multimedia --not_mandatory
9272 DEBUG + local legacy_args=odm
9273 DEBUG + args_array=([o]=origin_path= [d]=dest_path= [m]=not_mandatory)
9273 DEBUG + local -A args_array
9273 DEBUG + local origin_path
9273 DEBUG + local dest_path
9273 DEBUG + local not_mandatory
9273 DEBUG + ynh_handle_getopts_args --origin_path=/home/yunohost.multimedia --not_mandatory
9273 DEBUG + set +o xtrace
9306 DEBUG + …
=> [fix] hook restore multimedia

debian/postinst, debian/rules, src/yunohost/tools.py
Our current self-upgrade-from-API mecanics is madness.
This is related to the fact that during the upgrade of the `yunohost` package, dpkg / debian will auto-restart the webadmin. This has several drawbacks:
- when upgrading from the webadmin, we'll loose the websocket / log stream, and the session cookie is implicitly invalidated (because of how the webadmin cookie management works) ... and then it's not clear *when* the admin will be able to re-log
- apparently the API is stopped at the beginning of `postinst`, and started at the end ... but because our postinst includes regen-conf and diagnosis, this means that on slow hardware such as arm board, the API is gonna be down for possibly several minutes and that's spooky
The  current strategy therefore consists in separating "regular" …
=> WIP: Smarter API self-upgrade mechanics

src/yunohost/backup.py
I have enable the `compress_tar_archives` parameter, and when I delete a backup, each time I want to upgrade an app or list backups I have the error:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/yunohost.backup/archives/lxd-pre-upgrade2.tar'
If the file `.tar` exists, it should be a symlink to the `.tar.gz`, which is managed here:
https://github.com/YunoHost/yunohost/blob/16dba79a3983b979a19de1701773a5440ae9766f/src/yunohost/backup.py#L2602-L2604
Tested on my server
Enable compress_tar_archives:
> sudo yunohost settings set backup.compress_tar_archives -v 1
Create, remove, and then list backups
=> fix backup_delete when compress_tar_archives is True

data/hooks/conf_regen/03-ssh, data/templates/ssh/sshd_config, locales/en.json, src/yunohost/settings.py
People want to disable password auth with ssh (especially with the new diagnosis alert about fail2ban tentative).
https://forum.yunohost.org/t/high-number-of-authentication-failures-recently/18026/3?u=ljf
Allow to do:
```
yunohost settings set security.ssh.password_authentication -v no
```
Ready
If you have not modified your ssh conf:
```
yunohost settings set security.ssh.password_authentication -v no
```
=> [enh] Manage SSH PasswordAuthentication setting

src/yunohost/log.py
The args line in the metadata of a log file can leak some [sensitive data](https://paste.yunohost.org/aderirejeq.js)
Remove it
...
...
=> remove args for metadata

data/helpers.d/apt
We discovered several apps like onlyoffice and mautrix bridge had old dependencies on several instances.
The 
We suggest to force the upgrade to the last version accepted thanks to this change in `ynh_install_extra_app_dependencies`
NB: currently it conserves the old configuration, so the package need to upgrade it by running ynh_add_config or by running dpkg-reconfigure. We could add an option in this helper to do it, but i am not sure what is the good idea.
Untested / need point of view
With a repo with for example a top version of DEPENDENCY of 10
```
ynh_install_extra_app_dependencies --repo="SOME_REPO" --package="DEPENDENCY_NAME<=9"
ynh_install_extra_app_dependencies --repo="SOME_REPO" --package="DEPENDENCY_NAME"
dpkg -l | grep DEPENDENCY_NAME
```
=> [fix] Force dependencies upgrade even if previous version is accepted

share/actionsmap.yml, src/authenticators/ldap_admin.py, src/utils/error.py
While [working on the new "User Portal API"](https://github.com/YunoHost/yunohost/pull/1387), I realize that I'm gonna need more control over the way we create the cookie, because we must be able to easily check its authenticity from SSOwat' Lua code. The current mechanism with bottle's signing is great but not appropriate to allow another program to check the authenticity of the cookie, + it also pickles the object and it's gonna be hell to interface with Lua i'm suspecting ...
Move the cookie management logic to the authenticator (i.e. in yunohost instead of moulinette) for more flexibility in the cookie logic
Tested and working on my side (ie no regression)
Try to connect to the webadmin etc
=> api: Move cookie session management logic to the authenticator for more flexibility

data/hooks/conf_regen/43-dnsmasq
dnsmasq can't start if I [wlan0 interface is disabled](https://github.com/YunoHost-Apps/adguardhome_ynh/issues/34#issuecomment-1012405893)
Check the content of the `operstate` file
Not really tested in the battlefield
...
=> [dnsmasq] ensure interface is up

conf/mdns/yunomdns.service
After upgrade to bullseye the service complains:
```
Standard output type syslog is obsolete, automatically updating to journal.
Please update your unit file, and consider removing the setting altogether.
```
Follow the advice.
Ready, minor decision.
Just. Do. It!
=> [mdns] Set the StandardOutput to journal

conf/dovecot/dovecot.conf, conf/postfix/main.cf, conf/postfix/sni, hooks/conf_regen/19-postfix, hooks/conf_regen/25-dovecot
In a multi-domain context, postfix and dovecot always serve the main domain SSL certificates. This cause issue when users try to connect with a secondary domain.
- Fix https://github.com/YunoHost/issues/issues/1301
- Enable SNI support in postfix and dovecot.
Configuration from https://doc.dovecot.org/configuration_manual/dovecot_ssl_configuration/#with-client-tls-sni-server-name-indication-support and http://www.postfix.org/postconf.5.html#tls_server_sni_maps
- Works great with Thunderbird o/
- Maybe need testing on other mail clients but idk
- Pull this PR with `ynh-dev`
- Add 2 or more domains on YunoHost
- Create a user with a main on a secondary domain
- Try to log from a mail client
- Try to send a mail
=> [enh] Add SNI support for postfix and dovecot

src/diagnosis.py
Fix https://github.com/YunoHost/issues/issues/1967
Some list tricks :sunglasses: 
Not truly tested but should work great!
This is `names` :
```
['basesystem', 'ip', 'dnsrecords', 'ports', 'web', 'mail', 'services', 'systemresources', 'regenconf', 'apps']
```
Run those diagnosis!
=> [fix] reorder diagnosers

src/tests/test_app_config.py, src/utils/config.py
Running `yunohost foobar config get --full` doesn't return the list of choices for domain, user or other "dynamic-choices" questions.
As a result, the yunohost admin has some specific logic to fill the choices with pretty display values (eg adding a star for main domain, or display user with their fullname and email). But that logic could and should be handled by the core
during the `get()`, questions constructors are never called ... but they probably should ... but I don't have every edge case in mind to know if that's an issue
Testing and working on my side, but to be discussed about edge cases
Add dummy domain/user questions to the domain config panel
=> configpanels: config_get should return possible choices for domain, user questions (and other dynamic-choices questions)

conf/mdns/yunomdns.service
I had the service start before it was able to list any interface.
Make it rely on network-online.target instead of network.target
Done, ready to test, tested locally.
...
=> Enhance yunomdns service startup

src/app.py, src/utils/config.py
Domains and users appears empty when we install an app from the yunohost admin
This is a side effect of https://github.com/YunoHost/yunohost-admin/pull/426
Now, the admin doesn't compute choices and need them from the API
Give `choices` to the yunohost admin through the manifest
Working on my side o/
...
=> [fix] Compute choices for the yunohost admin when installing an app

share/config_domain.toml, src/utils/config.py
`filter` is now a simple expression, this allow filtering apps by id.
In the case of https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh, the manifest.json would look like this
```json
{
"arguments": {
"install": [
{
"name": "synapsenumber",
"type": "app",
"ask": {
"en": "Choose the local Synapse instance to communicate with mautrix_whatsapp.",
"fr": "Choisissez l'instance Synapse qui doit communiquer avec mautrix_whatsapp."
},
"filter": "match(id, 'synapse')"
},
]
}
```
and render in the webadmin like this:
=> configpanel: filter in AppQuestion

hooks/conf_regen/01-yunohost
`ps -ef` (or more generally, access to `/proc`) may leak secret info
Currently, the `hidepid` mechanism is only enabled via the experimental security setting
This proposes to enable it by default (since we're moving to Bullseye)
Yolocommited
...
=> security: Enable proc-hidepid by default

conf/postfix/main.cf
tls_server_chain_sni_maps doesn't exist
[tls_server_sni_maps](http://www.postfix.org/postconf.5.html#tls_server_sni_maps)
Done and tested
...
=> [fix] postfix sni tls_server_chain_sni_maps -> tls_server_sni_maps

helpers/hardware
due to localized vmstat in bullseye
`vmstat --stats --unit M | grep "free memory" | awk '{print $1}'` return nothing
`vmstat --stats --unit M` give expected values but with translated descriptions
force running the command in LANG C
...
...
=> Avoid grep issue with vmstat command

helpers/logging
Fix https://github.com/YunoHost/issues/issues/1982
When the result of a command start with a dash `-`, it's interpreted as a new argument.
Use the `--message` arg
yolocommitted :o
From a bash script
```
ynh_exec_warn ls -lah /etc/hosts
```
=> fix ynh_exec_*: ensure the arg message is used

helpers/logging
To adjust the weight parameter, you need to use the --time argument of ynh_script_progression and then need to remove it, and that for every occurrence. Sure, using an alias or a regular expression may help, but configuring the script may provide a more efficient way to alleviate this task.
The time is now always displayed when the scripts (install, backup, upgrade, etc.) are run in the CI environment while it can still be manually set while running outside.
I did not test my commit.
=> Always activate time when running inside CI tests

src/app.py
> hey, do you know if config_panel could be multi_instance? 😬
> the bookstack config_panel edit the config of the first installed bookstack instance, so not the instance I would like to configure
It seems config panel have the final_path loaded from the first instance instead the good one !
Use self.entity that contains the full app name (like nextcloud__2) instead of the app_id (the app name without the number, like nextcloud). 
Untested
...
=> [fix] Config Panel edits partially config of the first instance

helpers/string
Some apps restrict the characters to be used in random strings, e.g. hexadecimal keys.
Allow to select which characters can be returned by the helper
Done. Untested.
...
=> Improve ynh_string_random

helpers/apps
keeping the `\"`
`yunohost app install $one_app $one_argument`
will be
`yunohost app install galette --args "'domain=domain2.tld&path=/galette&is_public=1&admin=yalh&password=**********&database=mysql'"` 
with too much quotes
=> helpers: fix quoting issue in new ynh_install_apps helper

src/migrations/0021_migrate_to_bullseye.py
Lime2 boards have held package to avoid internet instability and the migration process check if there are some packages to upgrade.
Ignore those hold package
Untested
...
=> [fix] Allow lime2 to upgrade even if kernel is hold

helpers/apps
In case of using `ynh_install_apps --apps="appfoo"`, during install is do `yunohost app install appfoo --args 'appfoo'`, it will work but seems very strange
check if there is a `?` in each `$one_app_and_its_args`, if not, don't provide argument
ready
...
=> Fixing app without arguments

src/tools.py, src/user.py, src/utils/password.py
When someone do the postinstall with a 128+ char password, the person gets a message about the need for a 127- char password.
However when the person retry to postinstall, the postinstall is half made.So the second time it says  "The domain already exists" so the person have to reinstall or use the unknown reset script on https://github.com/YunoHost/yunoScripts/blob/master/resetPostinstall.sh
Do the check before to make changes.
In more i have added the checks on user account (not just admin) cause user account could have ssh permission too now.
Untested
...
=> [fix] Be able to redo postinstall after 128+ chars password

src/utils/config.py
Currently, if you have an app config panel that uses tags without restricting choices ( for example, `borg`'s one, with it's `app` field ), the web-admin will still use the component `TagsSelectizeItem` instead of `TagsItem` , making the option unchangeable from the web-admin.
This is due to the fact that the web-admin request the `--full` version of the config panel, and this returns by default an empty list for the choices, instead of `None`.
Simply change the default from an empty list to `None`
Ready to merge ? I was trying to think of edge cases where this could break something, but couldn't find one.
=> App Config Panel : Don't restrict choices if there's no choices specified

locales/en.json, src/yunohost/data_migrations/0021_migrate_to_bullseye.py
After migrating, the old virtual env for python apps ( located in /opt/ ) is no longer valid
Before upgrading, the migration script now creates a requirements file listing the different dependancies.
After upgrading the packages, the script deletes and recreates the virtual env from the generated requirements file
Draft
=> Saving app's venv in a requirements file, in order to regenerate it

src/tools.py
This allows special installation cases such as in a container, where disk_partitions(all=False) would not show virtual mount points.
When installing in a container, the postinstall step will complain about disk not being big enough. Actually, disk_partitions() only returns those mount points:
```
>>> psutil.disk_partitions()
[sdiskpart(device='/dev/mapper/luks-4e999104-04dc-4395-af70-0ce456540e15', mountpoint='/sys/fs/cgroup', fstype='ext4', opts='rw,nosuid,nodev,noatime', maxfile=255, maxpath=4096)]
```
all=True tells psutils to show all mountpoints, including virtual ones and non-physical partitions. We actually filter the returned list for the mountpoints / and /var, so there's no downside to this change.
Working
Install Yunohost in a podman container and enjoy
=> tools_postinstall: list all partitions (not only physical ones)

helpers/config
Config panel fails while deleting an uploaded file, while attempting to delete its checksum.
no need for `--update_only` flag
Ready.
Just. Do. It.
=> Fix ynh_delete_file_checksum in helpers/config

hooks/conf_regen/01-yunohost
After doing the yunohost initial configuration (postinstall), the logind service is not restarted even if the logind lidswitch config has been updated. So if we close the lidswitch (before rebooting) the computer is suspended.
Restart systemd-login in regen conf
Ready, but tested partially (i just restarted this service to make it work on an unrebooted laptop)
...
=> [fix] Lidswitch if no reboot

helpers/utils
When using the bind option in `config_panel.toml` with a values like `"encryption>allow:__FINALPATH__/config.yaml"` the config panel won't load and will be broken.
Use `-m1` parameter to Limit the number of grep matches to 1 here:
https://github.com/YunoHost/yunohost/blob/e4369274fa3379c279de4c8b6a19a85e06040805/helpers/utils#L517
and here:
https://github.com/YunoHost/yunohost/blob/e4369274fa3379c279de4c8b6a19a85e06040805/helpers/utils#L595
To avoid the following `tail` statements from breaking:
https://github.com/YunoHost/yunohost/blob/e4369274fa3379c279de4c8b6a19a85e06040805/helpers/utils#L547
https://github.com/YunoHost/yunohost/blob/e4369274fa3379c279de4c8b6a19a85e06040805/helpers/utils#L626
More info in the bug report: [#2003
](https://github.com/YunoHost/issues/issues/2003#top) …
=> [fix] Config panel nested bind statements

helpers/utils
Sometimes during upgrade of an app we need to completly remove previous sources before installing the new ones
Some examples:
- https://github.com/YunoHost-Apps/agora_ynh/blob/3ce3213030bcc533205259c7737df4c213bbd6f7/scripts/upgrade#L71-L83
- https://github.com/YunoHost-Apps/chuwiki_ynh/blob/098937aadc6495bed4ff5858cd09bcbde3f3050e/scripts/upgrade#L74-L90
- https://github.com/YunoHost-Apps/shaarli_ynh/blob/445198c4c555d6a5adedfc54b9112264f2559328/scripts/upgrade#L74-L96
- https://github.com/YunoHost-Apps/discourse_ynh/blob/ec974723113fa8f984af8ab47d1cc99765ae6c2f/scripts/upgrade#L108-L174
- https://github.com/YunoHost-Apps/focalboard_ynh/blob/76ae13bb2e4c5bc4efde3d3081c92282c35ce405/scripts/upgrade#L84-L104
And as --keep is already implemented, we have a simple way to do so
add an option …
=> Able to replace sources

share/actionsmap.yml, share/config_domain.toml, src/certificate.py, src/domain.py
- rework a bit the cache logic for domains and maindomain to keep only raw data
- add `--tree` arg to `yunohost domain list` to display a hierarchical tree of domains and subdomains
- add `yunohost domain info` to get aggregate data about dns configuration, cert status and apps installed on domain
Draft
```bash
yunohost domain list --tree
yunohost domain info
yunohost domain info mydomain.tld
```
`yunohost domain list --tree` should return something like:
```yaml
domains: 
dmn.ynh-dns-test.fr: 
my.dmn.ynh-dns-test.fr: 
my.long.sub.dmn.ynh-dns-test.fr: 
testy.ynh-dns-test.fr: 
ynh.local: 
main.sub.ynh.local: 
main: ynh.local
```
`yunohost domain info` should return something like:
```yaml
domains: 
dmn.ynh-dns-test.fr: 
certificate: 
acme_status: unknown
authority: self-signed
validity: …
```
=> Ability to "list" domain as a tree structure, + add a new domain_info endpoint

helpers/fail2ban, helpers/nginx, helpers/php, helpers/systemd
Able to define a specific path for some files ie outside of `/conf`
ynh_add_config directly handle the `$YNH_APP_BASEDIR/conf/` at https://github.com/YunoHost/yunohost/blob/551095aa7098c2ad4a8dbc9348cf80e4b5400f83/helpers/utils#L364-L370
and allow to define a specific path
So removing it from the helpers
Ready
...
=> Not need to force $YNH_APP_BASEDIR

share/registrar_list.toml
Recently added Provider "webgo" in lexicon-api leads to an stacktrace in yunohost (testing) when adding a domain which is registered there, since it is found by the lexicn-api, but is not in the yunohost registrar_list.
(I am also the author of the webgo provider for the lexicon-api)
Add webgo Provider into registrar_list
Done
I tested the whole implementation with about 20 Domains on webgo without any issue.
=> Add support for Webgo Registrar DNS

src/app_catalog.py
Do not fetch catalogs registered with no `url`
Required by https://github.com/YunoHost/ynh-dev/pull/66
=> appcatalog: do not fetch catalogs registered with no `url` (special case to be able to test app upgrades and stuff in dev envs)

src/app.py
Fix https://github.com/YunoHost/issues/issues/1974
Fix https://github.com/YunoHost/issues/issues/1178
Allow to install apps on `/foo2` even if there's already an app on `/foo`
It's not clear to me if there's any drawback doing this ... It seems to me that there was not actual reason to forbid this and may just have been a mythological "uh maybe nginx won't like it" but I dont see why it would ...
Yolocomitted
Try to install hextris on one /hextris, then another on /hextris2
=> Allow apps to be installed on a path sharing a common base, eg /foo and /foo2

data/helpers.d/postgresql
If app packager checks too soon for db existence (before postgres is installed) the error message is not very clear.
Just add a litte error message if psql cannot be found. The install crashes the same, but the packager now knows why, hopefully.
...
...
=> Better error message when psql is not there for database_exists

conf/nginx/server.tpl.conf, hooks/conf_regen/12-metronome, hooks/conf_regen/15-nginx, hooks/conf_regen/19-postfix, hooks/conf_regen/25-dovecot, hooks/conf_regen/31-rspamd, locales/en.json, share/actionsmap.yml, share/config_domain.toml, src/certificate.py, src/domain.py
https://github.com/YunoHost/issues/issues/1028
Propagate the existing mail/xmpp toggle to actual system configs during regen conf
Kinda tested on my side
Run ` yunohost domain config set your.domain.tld feature` and enable/disable some feature, check the impact on system confs
=> domains: propagate mail/xmpp enable/disable toggle to actual system configs

src/utils/config.py
https://github.com/YunoHost/issues/issues/2099
1. Use future_values instead of new_values (new_values includes only changed new values, instead of future_values, that includes all values updated with the already answered questions)
2. After hydrating the questions, make sure to overwrite each self.values[OPTION_ID] by a simple value and not a structured data
Ready (just tested on a server by copying the change manually not with ynh-dev)
Install hotspot and try to activate an hotspot
=> [fix] hotspot config panel fails in webadmin

locales/en.json, share/config_global.toml, src/app.py, src/settings.py
Changing ssowat's theme is annoying, have to manually edit conf.json.persistent in /etc/ssowat
Also a rework of https://github.com/YunoHost/yunohost/pull/631
Implement a global setting to choose the corresponding theme
Yolocommited, to be tested
Check the webadmin to check if new setting is there, try to change it, see if it's propagated in /etc/ssowat/conf.json
=> Add a global setting to choose SSOwat's theme

conf/fail2ban/postfix-sasl.conf, conf/fail2ban/yunohost-jails.conf, hooks/conf_regen/52-fail2ban
in order to prevent those 
```
Aug 31 22:23:52 hostxyz postfix/smtpd[38697]: warning: unknown[192.168.xx.xx]: SASL LOGIN authentication failed: authentication failure
Aug 31 22:23:52 hostxyz postfix/smtpd[38697]: lost connection after AUTH from unknown[192.168.xx.xx]
```
Too many login failures not taken into accounts by fail2ban
Apply jail conf and filter conf
...
...
=> Add postfix SASL login failure to a fail2ban jail

conf/dovecot/dovecot.sieve, conf/rspamd/rspamd.sieve
AFAIK this value is case sensitive. It is written as "Yes" in rspamd/milter_headers.conf
=> Fix flag case sensitivity in dovecot and rspamd sieve filter

hooks/conf_regen/37-mdns
Closes https://github.com/YunoHost/issues/issues/2115
Just don't force-disable avahi. Everyone should have it disabled by default by now (unless they didn't do upgrades for more than a year), so let's just stop doing that.
If we want to be more specific, we could comment out the entire yunohost block in avahi config if it's still enabled, and in that case disable avahi service. But i don't think that's necessary because this behavior has been default for so long now.
=> Don't disable avahi-daemon by force in conf_regen

.github/workflows/n_updater.yml
Node 12 version is deprecated since April 2022.
> Node.js 12 actions are deprecated. For more information see: [github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2
This PR is here to update actions to use Node 16 instead.
...
...
=> chore: update actions version to use node 16 version

helpers/mysql
Following an issue by a Castopode user: YunoHost-Apps/castopod_ynh#94
=> MySQL database backup does not include procedures.

helpers/utils
Output checksums if ynh_setup_source fails during their verification, to help maintainers check if it is a bug or persistent source change.
Make the error message a bit more verbose.
Untested in situ, but command works.
...
=> Output checksums if ynh_setup_source fails

helpers/string
This command doesn't work:
```
ynh_replace_string "Toto" "Toto@titi"
```
Replace the delimiter by something generally unused $'\001'
Waiting automatic test
...
=> [fix] Allow to do replace string with @

helpers/utils
With file like:
```
{
"tic": {
"toto": "titi"
},
"tac": {
"toto": "tutu"
},
```
This command fails
```
ynh_write_var_in_file --file=config.json --key=toto --value=tata --after="tic"
```
Here the kind of error messages:
```
sed: -e expression #1, char 173: unterminated `s' command
```
It's because `head -n1` is deactivated by the `|| echo YNH_NULL` just before... So we find several value in the key and get newline inside, so the sed command doesn't finish cause we insert a newline...
Use parenthesis to avoid that
Waiting automatic test
Tested manually on mattermost config json file
...
=> [fix] Write var in files with redundants keys

helpers/utils
This doesn't work due to the & char... cause in sed it means something
```
ynh_write_var_in_file --file=/var/www/mattermost/config/config.json --key=DataSource '--value=postgres://mattermost:**********@localhost:5432/mattermost?sslmode=disable&connect_timeout=10'
```
Escape it like in ynh_replace_string
Ready
...
=> [fix] Put a & into a config var

helpers/utils
This helper should replace only one occurence and not all occurencies...
Search the line where is the key and replace in the range after_line and key_line, to avoid to replace other identical key in other part of the file.
Tested manually on mattemost config file
...
=> [fix] ynh_write_var_in_file should replace one occurencies

conf/dovecot/dovecot.conf
This is reasonably important for the performance of clients such as Delta Chat. The plugins are bundled with dovecot by default (see https://wiki2.dovecot.org/Plugins ) so this should not be disruptive.
Clients can poll, but most are able to receive push notifications over imap as per RFC5423 ( https://datatracker.ietf.org/doc/html/rfc5423.html ). This improves the UX of IM-like clients considerably.
Enable the notify and push_notification plugins.
...
Start dovecot with the new config, connect with a client which can receive push notifications, compare apparent receipt time from a client perspective with the experience of a client doing polling instead and judge whether or not push is favourable.
=> Add push notification plugins

src/service.py
This is to handle decoding errors described in YunoHost/issues#2156
Pass `errors='replace'` to argument `open` command to override the default `strict` in `Codes`
The error doesn't seem to happen with gzip-ed logs. 
After gzip-ing a log that would through the decoding error with `open(file).read()` the `.gz` file did not through the error with `gzip.open(file).read()`
So I doesn't seem that `errors='replace'` argument needs to be passed to [`gzip.open(file)`](https://github.com/YunoHost/yunohost/blob/debian/11.1.10/src/service.py#L775)
...
...
=> Fix decoding errors not handled when trying to read service logs

src/settings.py
Running `yunohost settings set email.pop3.pop3_enabled -v 1` doesn't install dovecot-pop3d even if it was equal to 0 before.
Same with webadmin
This fix is simple the value is equal to True and not "True"
Tested on a prod instance
```
yunohost settings set email.pop3.pop3_enabled -v 0
yunohost settings set email.pop3.pop3_enabled -v 1
```
=> [fix] dovecot-pop3d is never installed

src/utils/resources.py
Installing an app to /opt/yunohost/__APP__ fails if it is the first app to be installed in /opt/yunohost.
Add the parents=True flag to mkdir.
...
Install [app v2 branch of p4p4j0hn/trilium_ynh](https://github.com/p4p4j0hn/trilium_ynh/tree/packaging_v2) with current dev branch and see the failure. Then try with this PR and it will work.
=> [Fixes 2158] Create parent dirs when provisioning install_dir

helpers/backup
cf many situations where file appear as "manually modified" on the CI despite no "manual" modification
Tweak behavior of helpers to save the original file and display the diff to help debug what's happening
Yolocommited
...
=> helpers: tweak behavior of checksum helper in CI context to help debug why file appear as 'manually modified'

helpers/systemd
we regularly see situation where YunoHost doesnt seem to detect that the service indeed started (line_match mechanism in ynh_systemd_action, etc). Though it's not clear why ...
Rework the mechanism such that we re-read `journalctl --since` in every iteration instead of dumping the output in a `tail -f` / `journalctl -f` and greppin that file
Yolocommited
...
=> helpers: more robust way to grep that the service correctly started ?

src/utils/resources.py
The non-webapp permission case seemed unsupported. 
Make sure `main` is populated, even with NoneTypes, and loosen the sanity check for it.
"Works for me", in my limited use-case of WireGuard Client app.
https://github.com/YunoHost-Apps/wireguard_client_ynh/pull/3
=> Handle undefined main permission url

src/utils/resources.py
In `_port_is_used`:
- cmd1 return 0 if the port is found
- there is no simple quote around the port number in `settings.yml`
If cmd1 OR (and not AND)cmd2 is true, then the port is used
...
Yolotested while packaging an app
...
=> trying to fix _port_is_used

helpers/utils, locales/en.json, src/app.py, src/backup.py, src/utils/resources.py
cf https://github.com/YunoHost/issues/issues/1978
- The whole key-value thing is not standard super (except that it's a source-able file, but is not used as such)
- It would be nice to have all sources declared in a single file rather than gazillion files for each arch or extra module
- YunoHost should automatically switch to the appropriate amd64 / armhf / i386 / ... source rather than the packager taking care of this
- The "SOURCE_FILENAME" option is confusing
- We are in the process of designing the future of the app's auto-upgrade.yml/sh hooks and having some additional info close to the app sources info could be useful to define "how to watch for new releases"
- Add support for a `sources` app resource in the manifest that is meant to declare the external assets to fetch to …
=> helpers: add support for a 'sources' app resources to modernize and replace app.src format

src/tests/test_questions.py, src/utils/config.py
Rework the questions/options tests and add multiple missing option types tests scenarios.
There's some tests that currently passes but probably shouldn't, some that do not but probably should.
You can search for `xfail`, `xpass`, and some `FIXME`s to have a quick look at those.
Plan is to fix the unexpected results on the pydantic migration if you agree with my comments.
There's a bunch of problems with nones () where things are not very clear what final None value we want.
Also added some quick fixes in `utils/config.py` to ease tests. @zamentur do you see any potential problems with those modifications? There might be magic stuff in bash helpers that I'm not aware of.
ok?
```bash
pytest src/tests/test_questions.py
```
=> [tests] Rework questions/options tests

src/utils/resources.py
`server_client_infos.url = "__SERVER_NAME__/.well-known/matrix "` in Dendrite's `manifest.toml` ends up in the CI with
```
6614 ERROR Provisioning, deprovisioning, or updating resources for dendrite failed: Domain '__SERVER_NAME__' unknown
```
Replace variables declarations with their values.
Untested.
Demo:
```
#!/usr/bin/python3
import re
infos={"url": "__SERVER_NAME__/.well-known/matrix", "additional_urls": ["__SERVER_NAME__/.well-known/matrix", "a__TEST__z__TEST2__"]}
if infos.get("url"):
for variable in re.findall(r"(__[A-Z0-9_]+__)", infos.get("url", "")):
infos["url"] = infos["url"].replace(
variable, "${"+variable.lower().replace("__","")+"}"
)
for i in range(0, len(infos.get("additional_urls", []))):
for variable in re.findall(r"(__[A-Z0-9_]+__)", infos.get("additional_urls", …
```
=> Support variables in permissions declaration

.github/workflows/codeql.yml
Silence CodeQL on hardcoded test passwords, but we lose code quality control.
=> Do not run CodeQL for tests

src/app.py, src/domain.py, src/settings.py, src/tests/test_questions.py, src/utils/configpanel.py, src/utils/form.py
PR  1/3 for the pydantic migration of config panel.
This is a separated PR to hopefully ease reviewing
This PR contains only function rename and code moves
form:
- rename `*Question`s to `*Option`s
- reorder `*Option`s
- rename `ARGUMENT_TYPE_PARSERS` to `OPTIONS`
- rename `Option._prevalidate()` to `Option._value_pre_validate()`
- rename `Option._post_parse_value()` to `Option._value_post_validate()`
configpanel:
- reorder methods
- rename `ConfigPanel._get_toml()` to `ConfigPanel._get_raw_config()`
- rename `ConfigPanel._load_current_values()` to `ConfigPanel._get_raw_settings()`
=> ConfigPanel: Before pydantic (renames) 1/3

src/app.py
```
$ touch doc/PRE_UPGRADE.d/5.44.0\~ynh1.md
$ yunohost app upgrade ghost -f . -F
Info: Now upgrading ghost...
File "/usr/bin/yunohost", line 77, in <module>
yunohost.cli(
File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 41, in cli
ret = moulinette.cli(
File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 111, in cli
Cli(
File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 507, in run
File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 584, in process
File "/usr/lib/python3/dist-packages/yunohost/app.py", line 676, in app_upgrade
notifications = _filter_and_hydrate_notifications(
File …
```
=> Fix current_version parsing for notifications

conf/nginx/security.conf.inc
Chromium [fails](https://github.com/YunoHost-Apps/jitsi_ynh/issues/113) to load a jitsi video conference, refusing to create a worker because it violates the Content Security Policy directive: "script-src https: data: 'unsafe-inline' 'unsafe-eval'".
Add a custom CSP for worker.
Proposal
1. Enable experimental security settings in tools / yunohost settings
2. Install jitsi_ynh app
3. Test the app with chromium
=> Update "worker" Content-Security-Policy header when in experimental security mode

helpers/apps, share/actionsmap.yml, src/app.py
Closes https://github.com/YunoHost/issues/issues/2041 
TODO:
To be extensively tested.
...
=> Offer a shell into an app environment

share/actionsmap.yml, src/domain.py
This issue https://github.com/YunoHost/issues/issues/2090 exists since 22 nov 2022, I think we could delete the deprecation and close the issue.
Delete actionmap and the corresponding function
Done
Clone then, use with ynh-dev.
=> [fix] Remove deprecated domain_dns_conf

src/diagnosers/12-dnsrecords.py
The dig of TXT for @ can returns multiple entries. In that case, the DNS diagnosis fails.
The modification preserves the handling of DMARC and the likes which use a single entry and a specfic domain name.
For single entry list, the behavior is preserved.
If mutliple TXT entries are defined for @, only the v=spf1 one is returned.
The diagnosic fails when multiple TXT entries are defined for @
Filter the v=spf1 one
...
...
=> diagnosis: Support multiple TXT entries for TLD

hooks/post_iptable_rules/52-fail2ban, src/firewall.py
Reloading firewall flushes all iptables rules to create new ones, dropping fail2ban rules in the same time.
Restarting fail2ban restores its iptables rules.
Proposal.
I'm new to yunohost, I don't know if/how it should be fixed.
With fail2ban activated, check the firewall status
```
Chain INPUT (policy DROP)
target     prot opt source               destination
f2b-recidive  tcp  --  anywhere             anywhere
f2b-sshd   tcp  --  anywhere             anywhere             multiport dports ssh
[...]
```
Reload yunohost firewall
```
```
The fail2ban rules are gone
```
Chain INPUT (policy DROP)
target     prot opt source               destination
[...]
```
=> keep fail2ban rules on firewall reload

helpers/apps, share/actionsmap.yml
Finished
Lock avoidance tested. PHP flags yolocommitted.
=> apps: Enhance app_shell()

src/app.py, src/tests/test_appurl.py
[Gitea](https://about.gitea.com/) has branch URL in form `https://domain.tld/gitea/path/<owner>/<repo>_ynh/src/branch/<branch_name>`.
It's impossible to install branch from non-default branch if repo is hosted in Gitea.
...
Adjust `APP_REPO_URL` to allow Gitea-specific syntax.
...
Ready I guess :)
...
Try installing apps from repo mirrored to Gitea. Should work with default branch, arbitrary branch, tag and commit hash.
...
=> Allow installation from gitea

conf/nginx/server.tpl.conf
OCSP stapling is in fact broken because nginx complains in the log file : 
`r3.o.lencr.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: r3.o.lencr.org, certificate: "/etc/yunohost/certs/domain.tld/crt.pem"`
Also related to : https://github.com/YunoHost/issues/issues/1099
I don't know why, but Nginx doesnt like 127.0.0.1 as a resolver, despite the fact that dnsmasq listens on 0.0.0.0:53 and a `dig` request on 127.0.0.1 does work ...
Using Google resolver works, but this is probably not what we want, so opening as draft PR only
Using Google resolver works, but this is probably not what we want, so opening as draft PR only
`openssl s_client -connect domain.tld:443 -status | grep OCSP` 
should display:
```
OCSP response: 
OCSP Response Data: …
```
=> Fix OCSP stapling ... but using tech giant resolvers :|

conf/dovecot/dovecot.conf, conf/postfix/main.cf, hooks/conf_regen/19-postfix, hooks/conf_regen/25-dovecot, src/app.py, src/utils/resources.py
c.f. https://github.com/YunoHost/issues/issues/947
This is not easy to configure an app to send emails. While packaging an app (transpay), it explicitly required to be able to auth on the mail server. I started creating a system user ... but realized it could not authenticated (because only LDAP accounts are able to with the current conf). 
Thanks to the help of @taziden I was able to configure dovecot to accept system users to authenticate. For this, a new passwd-like file `/etc/postfix/app_senders_login_maps` is added and filled with the appropriate app users.
```
foobar:{CRYPT}$6$SivRDh9NDh3w5.zs$Flq1MfFWq/RfVq3VvssWPwR2pMDWlTN87hretdavCUZlTwkROY1vmpqPxdEpeVg8AafmpDrGfbnyEwe7/5NX1/::::::allow_nets=127.0.0.1/24
```
But postfix also needs to be tweak to allow `foobar` to send emails with …
=> Allow system users to auth on the mail stack and send emails

helpers/php
`ynh_add_fpm_config` is horendously complicated
- Nobody actually uses `--use_template`, let's stop exposing this option
- Passing `--phpversion` explicitly shouldn't be needed, it grabs `$phpversion` implicitly, no need to pass it explicitly.
- Only one app (pihole) uses `--dedicated_service` ... despite that we tried to act in the past that it should be the defacto standard, but whatever, things are working okay-ish with the status quo, but let's deprecate this option and remove it in bookworm to simplify the code ...
- The whole thing about `--usage` / `--footprint` is unnecesarily complicated. Packagers shouldn't have to manage those settings manually as is currently often seen in packages. It should default to `low` by default, or use any existing `fpm_usage`/`fpm_footprint` if they …
=> apps: Simplify ynh_add_fpm_config helper

bin/yunopaste
As mentionned is this issue https://github.com/YunoHost/issues/issues/1291 , yunohost cli was doing weird.
A new CLI tool written in python, ip and domain protect is activated by default and can be disabled by parameter.
Here is an example: https://paste.yunohost.org/ubezadequh
Done
Replace yunopaste with the one of the pull request.
=> [fix/enh] Rewrite of yunopaste CLI tool

share/registrar_list.toml
In the domain's config panel:
```
Packagers: option api_protocol has 'choices' but has type 'string', use 'select' instead to remove this warning.
```
=> Gandi's `api_protocol` field should be a `select` type

src/authenticators/ldap_admin.py, src/authenticators/ldap_ynhuser.py
I could not log out from the new SSO. It would display the login form but the cookie was still there hiding in the shadows.
The cookie was created with path '/' so removing it only works if the same path is provided.
I unified all paths to '/' which seems to work. Maybe we should just not specify it.
=> Handle both cookies in the same way (please let me logout)

src/authenticators/ldap_ynhuser.py
As per the instructions here: https://github.com/YunoHost/issues/issues/2028#issuecomment-1676380458
=> Serialize the JWT token to a cookie string instead of failing

conf/nginx/plain/yunohost_sso.conf.inc
The new yunohost-portal package uses inline scripts in its current form so it should be allowed in the CSP for this route.
See also https://github.com/YunoHost/issues/issues/2028#issuecomment-1676380458
=> Allow inline scripts for yunohost-portal (nginx CSP)

share/actionsmap.yml
The help message from `yunohost app install --help`  was not clear about:
- how to set initial permissions
- how to bypass the post-install notification from the app (if any)
Both are required for a scripted (unattended) install.
=> Add information in yunohost app install --help

share/actionsmap.yml
Small typo in --continue-on-failure arg help in yunohost app_upgrade:
Continue to upgrade apps event if one or more upgrade failed instead of
Continue to upgrade apps even if one or more upgrade failed
Fix typo in share/actionsmap.yml
...
Run sudo yunohost app -h and check typo is fixed
...
=> [fix] typo in app_upgrade argument help

src/diagnosers/24-mail.py
https://github.com/YunoHost/issues/issues/2235
Use lower and assume that r["helo"] is always a string
Untested, but micro
...
=> [fix]  Diagnosis: reverse DNS check should be case-insensitive #2235

src/utils/resources.py
Upgrading an app from packaging v1 when db_name was different from `app` can causes issues
see https://github.com/YunoHost-Apps/glitchsoc_ynh/pull/142#issuecomment-1686145422
- Use the existing db_name setting during provisioning
Yolocommited
...
=> Use the existing db_name setting for database provising

src/app.py
"satefy" -> "safety"
Fixing the typo
=> app.py: fix typo in log statement

src/app.py
As observed in FitTrackee system user was not able to send mail. I narrowed it down to the following stanza(s)
manifest.toml:
```toml
[resources]
[resources.system_user]
allow_email = true
```
sample.py:
```python
import smtplib
import ssl
sender_email = "system_user@domain.tld"
username = "system_user"
password = "password"
host = "domain.tld"
port = 25
recipient = "some_user@some.domain.tld"
message = "From: %s\r\nTo: %s\r\n\r\nTest message" % (sender_email, recipient)
print(message)
connection_params = {}
context = ssl.create_default_context()
with smtplib.SMTP(
host, port, **connection_params
) as smtp:
smtp.set_debuglevel(2)
smtp.ehlo()
smtp.starttls(context=context)
smtp.ehlo()
smtp.login(username, password)
smtp.sendmail(sender_email, recipient, message)
smtp.quit()
``` …
=> Allow system users to send mails from IPv6 localhost.

conf/fail2ban/jail.conf
`jail.conf` is an old version
Update it to the [version used on bookworm](https://sources.debian.org/src/fail2ban/1.0.2-2/config/jail.conf/)
Yolocommitted, not tested
...
=> Update fail2ban jail conf

helpers/utils
There shouldn't be any trailing / for folders for ynh_setup_source, otherwise `folder/` will be restored in `folder/folder`
better example shown in command line, and in autogenerated doc
...
...
=> Fix missleading example for ynh_setup_source

src/utils/dns.py
OK, I concede it is technically not a TLD, but it fits the special case list for domains.
As per https://www.rfc-editor.org/rfc/rfc8375.html, domains ending by `home.arpa` are expected to solely be used locally.
=> Add home.arpa as special TLD

src/app.py
add `supports_purge` bool to `yunohost app info {app} --full` so that webadmin can display a checkbox to purge the app's data dir at app removal
=> app: add "support_purge" to app info

helpers/apt
Specifying in chuwiki
```toml
[resources.apt]
packages = [
"php7.4"
]
```
does not set `$phpversion`.
Allow sole `php7.4` to set `$phpversion`, instead of requiring `php7.4-whatever` (`-` (or for some reason `>` ) is required for previous RegEx to work).
WFM :P
#yolo
=> Allow `phpX.Y` as sole dependency for `$phpversion=X.Y`

.github/workflows/n_updater.yml
cf. https://github.com/YunoHost/yunohost/pull/1727, `n` versions are not displayed.
=> Display n version in auto-update PRs

conf/dovecot/dovecot.conf
For rspamd being able to learn ham or spam from messages being moved into spam/junk folders or out of them dovecot needs to know how spam/junk folders and trash folders are named.
The former rules narrowed the folders being recognized as spam/trash down to just 'Junk, SPAM, Trash' (case-senistive).
Since users and admins can change the foldernames and write their own seive filters to use those folders I think it is a big improvement if more folders will be recognized.
The change is supposed to accept some more commonly used folder names for spam and trash in a case-insensitive manner.
=> improve dovecots rspamd integration

conf/rspamd/redis.conf, hooks/conf_regen/31-rspamd
https://github.com/YunoHost/issues/issues/2266
without this rspamd does not use the redis database
=> add redis database configuration

src/log.py
When a script fails, we get sometimes:
```
ERROR Could not upgrade gitlab: Something unexpected went wrong: 
File "/usr/lib/python3/dist-packages/yunohost/hook.py", line 538, in hook_exec_with_script_debug_if_failure
operation_logger.dump_script_log_extract_for_debugging()
File "/usr/lib/python3/dist-packages/yunohost/log.py", line 749, in dump_script_log_extract_for_debugging
lines = [line.strip().split(": ", 1)[1] for line in lines]
File "/usr/lib/python3/dist-packages/yunohost/log.py", line 749, in <listcomp>
lines = [line.strip().split(": ", 1)[1] for line in lines]
IndexError: list index out of range
```
https://ci-apps-dev.yunohost.org/ci/job/10016
...
...
...
=> Fix dump script log extract for debugging

helpers/logging
npm install triggers this error:
> Error: There's quite a lot of warnings in the output ! If those warnings are coming from some app build step and ain't actual warnings, please redirect them to the standard output instead of the error output ...!
and it's right : it's some stderr we don't care about… Except when it fails!
a helper that prints the stderr when the command fails.
untested
=> Add ynh_exec_and_print_stderr_only_if_error that only prints stderr when command fails

helpers/config, src/utils/configpanel.py
When we create config panel, sometimes all a section or a panel is bound to a same config file. Always copy the bind property with the config file path is so much verbose !
Implements a sort of heritage between panel section and params, example:
```toml
[main]
name = ""
bind = ":__INSTALL_DIR__/public/organization.properties"
[main.section_1]
name = "General"
[main.section_1.foo]
bind = "toto:" # -> "toto:__INSTALL_DIR__/public/organization.properties"
[main.section_1.bar]
[main.section_1.aaa]
bind = "settings" # -> "settings"
[main.section_1.zzz]
bind = "null" # -> "null"
[main.section_1.plop]
bind = "plop()" # -> "plop()"
[main.section_2]
name = "Advanced"
bind = "advanced>:" # -> "advanced>:__INSTALL_DIR__/public/organization.properties"
[main.section_2.foo_2]
bind = "foo:" # -> …
```
=> [enh] bind heritage in config panel

src/firewall.py
When reloading the firewall, it can take several minutes when we have many IPs banned by Fail2Ban.
This is due to the use of the iptables/ip6tables command without the `-n` flag, so a reverse DNS resolution of each IP is requested.
Here's an example I have: 
```
454
real	4m33.729s
user	0m0.085s
sys	0m0.149s
real	0m0.010s
user	0m0.010s
sys	0m0.000s
```
Added the -n flag to the `iptable` and `ip6table` commands
- Currently test on a YunoHost by running the command `yunohost firewall reload`. 
- Run `yunohost firewall reload`
=> [enh] Reload firewall disable resolve IP

locales/en.json, locales/fr.json, src/backup.py
When the backup of an app fails for some reason because a backup file with the same name already exists, the error message `A backup archive with this name already exists.`. This error message does not give the name of the already existing backup, preventing the user to try and fix the error by himself (by deleting or moving the already existing backup file for example). 
Modify the error message to give the name of the already existing file inside it.
The code is ready to be merged. I modified the french and english translations, I don't know if we need the other translations to be modified before this PR is merged or if translate later will do.
- `touch /home/yunohost.backup/archives/test-backup-fix.tar`
- `yunohost backup create -n test-backup-fix  --app adguardhome`
And see the …
=> Fix backup error message if archive already exists

helpers/fail2ban, helpers/logrotate
Logrotate generated config files could have wrong permissions and in this case the log files are never rotated
See:
https://github.com/YunoHost/issues/issues/2242 and https://github.com/YunoHost-Apps/gotosocial_ynh/issues/110
Add a chmod to ensure that the generated config file permissions are correct
Could be reviewed and maybe merged
Not tested tho 
...
=> logrotate: fix generated config file perms

conf/dovecot/dovecot.conf
tells dovecot to create standard folders on first login if they do not exist and which folder names are used for special purposes like archive, spam/junk, sent, etc.
https://github.com/YunoHost/issues/issues/1456
This part of the solution creates new folders on first login. Missing patches to close the issue:
* adjust `antispam_spam` & `antispam_trash` for rspamd integration
* change global sieve script into a user sieve script that is copied on user creation (hook)
=> let dovecot create folders on first login

helpers/fail2ban
if the logfile doesn't exists (as in a fresh install), the helper will return an error because fail2ban WANTS the file to already exist
so in my packages, I do a `touch LOGFILE` before the helper to get around the problem
but it's better to fix that issue in the core
verify if the logfile exists, if not, create it:
```bash
if [ ! -f "$logpath" ]; then
touch "$logpath"
fi
```
ready but not tested
...
=> fail2ban: make sure the logfile exists

helpers/fail2ban
when the fail2ban helper is used with the --use_template argument, the `logpath` variable is not assigned, so there's an unbound error 
thanks to @Psycojoker who helped me to understand the bug ^w^
if `logpath` doesn't exist, get the logpath from the template and assign it to the `logpath` variable
replace any `__VAR__` in the logpath by their real variable using ynh_replace_vars
yolo
...
=> fix the fail2ban helper when using using --use_template arg

src/app.py, src/domain.py
Had a quick look at perf, in particular I noticed that the "permission" test takes unexpectedly long ...
Digging into it, I noticed that `hook_exec` (triggered by the `post_user_add/delete` hook) adds some delay, fixed by https://github.com/YunoHost/moulinette/commit/cfb840c5ccb8417494fb4d9556b59068abf4150e
1sec doesnt sound like much, but considering that we are likely to create/delete 2 or 3 user in every test, it can add up to a few minutes
Additionally, I realized that `import yunohost.domain` takes some time, and digging i found it's because `import yunohost.utils.configpanel` and in turn `import yunohost.utils.form` (which defines all the options classes) takes like 500ms on my machine (maybe more on an arm board)
I think ultimately sometime in the future we should switch to a …
=> perf: improve perf for a bunch of operations by lazy import + lazy define of config-panel related stuff

helpers/nginx, src/app.py
In change url script we need workaround like [this](https://github.com/YunoHost-Apps/seafile_ynh/blob/master/scripts/change_url#L14-L15) because path and domain are the old one and so somethings are set with old values.
Set correctly the domain and path with new values.
Patch on helper was tested here: https://github.com/YunoHost-Apps/seafile_ynh/blob/master/scripts/change_url#L27-L52
=> helpers: Further simplify the change url helper

helpers/utils
https://github.com/YunoHost/issues/issues/2296
I simply suggest here to die the script on the first patch failure
Tested
1. Install nextcloud with the oldstable branch
2. Upgrade nextcloud with the master branch
3. The upgrade should failed due to `Unable to apply patches` and not silently continue to upgrade the app
=> [fix] First source patches failure doesn't stop app script

src/user.py
Possible solution for https://github.com/YunoHost/issues/issues/2226
=> Only warn that mailbox is disabled for admins

conf/dovecot/dovecot.conf, conf/postfix/main.cf, src/app.py
Mail reply from app don't work
Add missing account registration on postfix for apps
Tested local and it worked
Install an app which support fully mail stack and replay by mail.
=> apps: add mailbox/IMAP support for apps that declared a system user with mail enabled

helpers/utils
the `--after` argument is not documented for `ynh_read_var_in_file` and `ynh_write_var_in_file`
add `--after=` in the usage section of `ynh_read_var_in_file` and `ynh_write_var_in_file`
finished
...
=> add --after= in the usage section of ynh_read_var_in_file and ynh_write_var_in_file

src/utils/resources.py
now with https://github.com/YunoHost/apps/pull/1960 the bot provides the changelog link when the update strategy is set to `latest_github_release`
document this behavior
...
...
=> [docs] document changelog link for latest_github_release

helpers/utils, src/app.py
* remove UPGRADE_FULL
* rename DOWNGRADE_FORCED -> DOWNGRADE
* rename UPGRADE_FORCED -> UPGRADE_SAME
* keep the helper ynh_check_app_version_changed behaviour for reverse compatibility.
I renamed because IMHO those `_FORCED` suffixes are not really useful, and not actually used the way they should:
https://github.com/search?q=org%3AYunoHost-Apps+UPGRADE_FORCED&type=code
useless code
remove code
=> app.py, helpers: Reword YNH_APP_UPGRADE_TYPE

helpers/apps
Tested.
`yunohost app shell` then `which pip` with pelican_ynh, for example.
=> Enhance app shells

locales/en.json
1025+ port could be listen as non root, so an evil user could overload the server to make ssh killed by oom_reaper and next run it's own fake daemon to gain access to the server by collecting password.
Advice to use a port under 1024.
Ready
...
=> [enh] Add help on ssh port

share/actionsmap.yml, src/tools.py
Addresses parts of https://github.com/YunoHost/issues/issues/2230
`yunohost tools basic-space-cleanup`
=> Add basic-space-cleanup command

src/utils/resources.py
Before this, provisionning might use twice the same port (second app install for example). Indeed, _port_is_used only checks processes and already installed apps. Not the current app being installed.
=> port resource: Fix port reuse during provisionning.

helpers/logrotate
```
logrotate /etc/logrotate.d/kavita
error: skipping "/var/log/kavita/*.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
```
https://forum.yunohost.org/t/logrotate-failed/28507
`chmod 640 "/var/log/$app"`
yolo
...
=> fix logs folders perms

.github/workflows/codeql.yml, .github/workflows/n_updater.yml
> The following actions uses node12 which is deprecated and will be forced to run on node16: peter-evans/create-pull-request@v3. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, peter-evans/create-pull-request@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> chores: update actions/checkout & peter-evans/create-pull-request to nodejs20

helpers/logrotate
https://forum.yunohost.org/t/cant-install-peertube-app/28736/5
Recent change in the creation of `/var/log/$app` directories make them not accessible. 😅 
`chmod 750` all the things.
Ready.
Fast
=> Fix logs directories access

maintenance/make_changelog.sh
- the `--global` in `git config --global --get` prevent to temporaryly set a name and email for the release
- if we squash a PR, we get boresome "co-authored" lines
- remove the `--global`
- filter "co-authored" lines
done
...
=> tools: make_changelog.sh enhancements

src/app.py
- In config panel not all app variables are available and it limit some config file to edit correctly
- Add env var as same as for others scripts.
Tested on my side and it provide the necessary variables.
Run the config panel script (`config`) and check with `env` command that `domain`, `path`... are provided.
=> Add generales var in config panel like domain, path, etc

README.md
- The link in `As [other components of YunoHost](https://yunohost.org/#/faq_en), this repository is licensed under GNU AGPL v3.` is broken
- many pictures does not have a proper alt text
- fixed the broken link
- add alt text
- also fixed minor markdown formating
done
=> Readme: add images alt text, fix some links and some markdown formating

.github/workflows/autoblack.yml, .gitlab/ci/lint.gitlab-ci.yml
We've moved all our code base to the autoblacks.yml github action for autoblacking our code but yunohost is still using a gitlab CI job for that.
The gitlab CI job obviously works and there is nothing wrong about it but uniformising everything with one tool is easier to maintain.
Use autoblack instead.
Works as expected but I'm waiting for an answer from @kay0u to see if we completely drop the gitlab job or if we convert it into a linting job that fails when black isn't happy.
It's a bit hard but you can change the target branch of the script to this MR and push it again and see if a PR is generated but it has already been tested on other projects since quite some time already so testing isn't really needed.
=> ci(autoblacks): switch from using gitlab CI to github actions for autoblacking code

helpers/config
Where are some issues with config panel when we use secial char on values. By example `\+33` as yunohost settings shown on config panel fail because `\` mean to escape next char but the next char should not be excaped and we have this error:
```
yaml.scanner.ScannerError: while scanning a double-quoted scalar
```
Following the specification of yaml (https://yaml.org/spec/1.2.2/#single-quoted-style), when we use single quote we only need to escape single quote. By this we avoid to need to escape multiple other chars which could be complicated.
Tested on synapse and it solve issues for `allowed_local_3pids_email` and `allowed_local_3pids_msisdn` settings which was problematic.
Tested on my side and it worked well
On any app which show an app settings into the config panel. Put some special …
=> Use single quote to return value to config panel

helpers/apt
Waiting on `ynh_wait_dpkg_free` could be really slow
On a quick machine
```
real    0m0.183s
user    0m0.059s
sys     0m0.093s
```
On slow machine (like raspi):
```
real    0m2.223s
user    0m0.602s
sys     0m1.484s
```
When we have multiple call  of `ynh_package_is_installed`  on the same package it could be really slow.
From my analyse `ynh_wait_dpkg_free` was added into `ynh_package_is_installed` probably just by generality to ensure that all apt helper wait on dpkg before to run but without a specific need.
I think we can remove this by default and add a specific option to enable it if specific need.
Tested with monitorix https://github.com/YunoHost-Apps/monitorix_ynh/pull/55 and it work well
Just run the helper `ynh_package_is_installed` with the option that you want to test.
=> helpers: Do not wait for dpkg lock when calling ynh_package_is_installed

helpers/utils
YunoHost/yunohost#1810 generates warnings on CI tests jobs:
https://ci-apps-dev.yunohost.org/ci/job/15001
```text
7690 INFO [#+++................] > Setting up source files...
8879 WARNING ls: cannot access '/etc/yunohost/hooks.d': No such file or directory
8879 WARNING ls: cannot access '/opt/yunohost': No such file or directory
8928 WARNING ls: cannot access '/etc/yunohost/hooks.d': No such file or directory
8928 WARNING ls: cannot access '/opt/yunohost': No such file or directory
```
https://ci-apps-dev.yunohost.org/ci/job/15036
```text
486  INFO [++++++++++..........] > Removing NGINX web server configuration...
502  WARNING ls: cannot access '/etc/yunohost/hooks.d': No such file or directory
502  WARNING ls: cannot access '/opt/yunohost': No such file or directory
1035 WARNING ls: …
```
=> helpers: fix 'ls: cannot access <folder> No such file or directory' errors on CI

src/tools.py
otherwise, if one fails, the following ones are not run.
=> Split log rm commands into separate shells

doc/generate_helper_doc.py, helpers/apt, helpers/backup, helpers/fail2ban, helpers/hardware, helpers/mysql, helpers/network, helpers/permission, helpers/postgresql, helpers/setting, helpers/string, helpers/user, helpers/utils
The helpers doc is bloated with internal or packaging v1 helpers which are now useless or deprecated
Add a `[packagingv1]` tag to ignore them during doc generation + flag some other helpers as internal
- `ynh_package_version` : internal
- `ynh_package_update` : internal
- `ynh_package_install`: internal
- `ynh_package_remove` : internal
- `ynh_package_autoremove` : internal
- `ynh_package_autopurge` : internal
- `ynh_install_app_dependencies` : packagingv1 (apt resource)
- `ynh_add_app_dependencies` : packagingv1 (apt resource)
- `ynh_remove_app_dependencies` : packagingv1 (apt resource)
- `ynh_install_extra_app_dependencies` : packagingv1 (apt resource)
- `ynh_backup_before_upgrade` : packagingv1 (handled by core)
- `ynh_restore_upgradebackup` : packagingv1 (handled by core)
- …
=> doc: Remove internal/packagingv1 helpers from helpers doc

helpers/apt
`ynh_install_extra_app_dependencies` leaves the extra repo hanging if `--name` parameter was provided.
remove `$name` repo, not default `$app`
???
Install with custom name, observe the world not burning.
=> Actually remove the newly added repo.

conf/slapd/config.ldif
Admin users are unable to modify ldap entries, getting following error: 0x32 (LDAP_INSUFFICIENT_ACCESS)
=> fix ldap write access for admin users

helpers/go
=> Add Go Helper to the core

helpers/nodejs
Node's corepack uselessly asking to confirm downloading Yarn
Let's set this to `0`: https://github.com/nodejs/corepack/blob/119fd2f43850f8a76d2d179850f094eeacc47e45/sources/httpUtils.ts#L69
Ready
...
=> Prevent yet another Node and Corepack madness

src/authenticators/ldap_ynhuser.py
If app specify private path it's impossible to access as `yunohost.portal` cookie is not forwarded when app is installed on subdomain.
Return cookie valid for `.domain.tld`, just like old `SSOWat` did. Come to think about it we should return cookies valid for all domains?
It worked once.
Install LimeSurvey from https://github.com/orhtej2/limesurvey_ynh/tree/patch-2 and see if you can access admin.
=> [bookworm] Return auth cookie valid for whole main domain.

src/utils/form.py
Due to a bug in the way forbidden keywords was added, some keywords was missing.
https://github.com/YunoHost/yunohost/pull/1845/files#diff-5e01fe3313064e3147b9fbde1ad38648caa5677bc926f91b9a740fce038ebde8L483
Indeed properties and defaults are not the forbidden keywords targeted.
List the good keywords and explain why they can't be used.
Ready
...
=> [fix] Forbidden keywords config panel

helpers/getopts
The usage of `echo` to output arguments to to a pipe leads to the problem that arguments that are valid to `echo` itself cannot be processed:
```
root@yt:~# TEST='-n'
root@yt:~# printf '%s\n' $TEST
-n
root@yt:~# echo "$TEST"
root@yt:~# echo "debug $TEST"
debug -n
```
Replacing `echo` with `printf` improves the situation.
=> Update getopts to accept arguments that are valid arguments to echo

helpers/helpers
If `source helpers` has no arguments passed, $@ is the main script arguments.
=> Fix helpers: actually that might be a bad idea to read arguments

helpers/helpers.v1.d/go
Instead, checkout the latest commit. Same for xxenv-latest.
=> helpers: goenv is broken when checking out latest master commit.

helpers/helpers.v1.d/hardware
This provides yunohost 2 things:
* Remove duplication and centralize code and bugfixes for easier maintainance
* The day the core supports swap, or we want to change the logic, these helpers can be changed to empty shells.
swap helpers everywhere in the apps.
=> Add swap helpers.

helpers/helpers.v1.d/utils
in [line 955](https://github.com/chri2/yunohost/blob/2bd76986a8e6d67bd8b9865cbb694ac1ec35383a/helpers/helpers.v1.d/utils#L955) the parameter is named different than in the functions help
=> helpers: Fix typo in ynh_read_manifest documentation

helpers/helpers.v1.d/go
goenv latest doesn’t call the plugin anymore, so i’m calling directly the plugin goenv-latest.
=> helpers/v1/go: fix call.

src/utils/resources.py
A wrong indentation leads to code executed at every for loop iteration. If multiple apt.extras resources, this fails at the first iteration.
=> resources.py apt: Fix when multiple extras are passed

conf/postfix/main.cf
If an app registers the sender address _app@doma.in_ **and** a yunohost account configured an alias for the same address the app will not be able to send emails anymore.
postfix asks the first map defined in smtpd_sender_login_maps and finds that the address _app@doma.in_ can be used as a sender address by the yunohost account having configured the alias and **then stops and doesn't look up the second list** for registered apps.
The unionmap instructs postfix to join a list from both sources and then return the match from that joined list which would then contain _yunohost_account_having_registered_alias, appname_ for the lookup of _app@doma.in_.
This allows the yunohost account having registered the alias and the app being registered to use the sender address to send email using that …
=> Update main.cf to allow aliases for sender addresses of apps

helpers/helpers.v2.1.d/apt, helpers/helpers.v2.1.d/php
- [fpm_usage/footprint is completely wtf and you need a PhD in both Bash and PHP-FPM to understand what these do](https://www.youtube.com/watch?v=qmsF3xbqnR8)
- The vast majority of php apps just set stuff to "low/low"
- The vast majority of `conf/extra_php-fpm.conf` is about setting upload_max_filesize, post_max_size, sometimes memory_limit, but we could just handle this from settings/variables ...
- The helper defines unecessary `fpm_config_dir` and `fpm_service` which can just be derived from `$php_version` so what the heck
- Drop the usage/footprint madness entirely
- The helper does everything most app want by default, no need anymore for a extra_php-fpm.conf except maybe for Nextcloud
- For apps that want to tweak common things (which shouldnt be necessary in the nominal case):
- …
=> helpers2.1: rework the fpm usage/footprint madness

helpers/helpers.v1.d/setting, helpers/helpers.v2.1.d/setting
Boring `if [ -z ${foo:-} ]` trick all over the place in upgrade scripts
`ynh_app_setting_set_default --key=foo --value=bar`
Sort of yolo
...
=> helpers: add a new ynh_app_setting_set_default to replace the unecessarily complex 'if [ -z ${foo:-} ]' trick

helpers/helpers.v2.1.d/sources, helpers/helpers.v2.1.d/utils
Only check if target is a child of install_dir.
Fixes https://github.com/YunoHost/issues/issues/2243
=> [helpers v2.1] Rework _ynh_apply_default_permissions

helpers/helpers.v2.1.d/utils
[yunohost/issues#2253](https://github.com/YunoHost/issues/issues/2253)
Before erroring out before file doesn't exist, we need to check two things:
* ! test -e target (target doesn't exist, or target is a broken symlink)
* ! test -L target (target is NOT a symlink)
...
...
=> Fix ynh_safe_rm: check if target is not a broken symlink before erorring out.

helpers/helpers.v2.1.d/sources
this is needed for invoiceninja, see https://github.com/YunoHost-Apps/invoiceninja5_ynh/pull/280
"tar" is not a recognized extension for `ynh_setup_source`. This breaks downloading tar-files during installation.
Add tar-support.
done
...
=> add support for downloading tar-files

src/diagnosis.py, src/service.py, src/tools.py
if the user deactivate some services, the diagnosis will raises errors because the service is not 	active
that's dumb, if the user deactivated a service using the ynh cli, ynh should know the service is deactivated on purpose
automatically ignore the service in diagnosis if it has been deactivated with the ynh cli
done
deactivate a service, see if the diagnosis raises an error, then re-activate the service
=> automatically ignore the service in diagnosis if it has been deactivated with the ynh cli

src/service.py
#1886 doesn't work... like really:
```text
yunohost service disable gitea
File "/usr/bin/yunohost", line 77, in <module>
yunohost.cli(
File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 41, in cli
ret = moulinette.cli(
File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 110, in cli
Cli(
File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 500, in run
File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 574, in process
File "/usr/lib/python3/dist-packages/yunohost/service.py", line 324, in service_disable
diagnosis_ignore({"services": [{"service": name}]})
File …
```
=> trying to fix #1886

src/app.py
In the ssowatconf, all my api permissions have the field `auth_header: null`
I think the correct value is `false` instead of `null`
Yolo applying this patch and `yunohost app ssowatconf`
...
=> ssowatconf: change auth_header from None to false

helpers/helpers.v1.d/apt, helpers/helpers.v2.1.d/apt
https://www.meilisearch.com/docs/learn/getting_started/installation
echo "deb [trusted=yes] https://apt.fury.io/meilisearch/ /" | sudo tee /etc/apt/sources.list.d/fury.list
=> helpers/apt: Support apt repositories with [trusted=yes]

src/migrations/0027_migrate_to_bookworm.py.disabled
`No matching distribution found for pkg_resources==0.0.0` during the python venv migration
Remove `pkg_resources` from the freeze
...
...
=> remove pkg_resources from pip freeze

share/dnsbl_list.yml
Since March 1st this service is behind a fair-use paywall, which generates lot of alert email confusing people whether their IP/domain is actually blocked, when actually it’s just the service failing.
See: https://knowledge.validity.com/s/articles/Accessing-Validity-reputation-data-through-DNS?language=en_US
https://forum.yunohost.org/t/senderscore-blacklist-blocklist-because-of-excessive-number-of-queries/30395
=> fix: Remove SenderScore from the dnsbl_list.yml file

conf/slapd/slapd.default
Some app are configured to connect to LDAP this way: `ldap://localhost:389`.
But currently, slapd listen only on IPv4. On my side I've this result with `ss`:
```
ss -ntlp | grep 389
LISTEN 0      1024       127.0.0.1:389        0.0.0.0:*    users:(("slapd",pid=1434,fd=9)) 
```
We have this issue here: https://forum.yunohost.org/t/seafile-11-0-9-cant-login-with-client/30504/2
Configure slapd to listen also on ipv6.
This is ready
Tested with netcat and now connection work with IPv4 and IPv6.
We can also test with `ss` with has this result:
```
ss -ntlp | grep 389
LISTEN 0      1024       127.0.0.1:389        0.0.0.0:*    users:(("slapd",pid=1434,fd=9))                                                                                                 
LISTEN 0      1024           [::1]:389 …
```
=> [Fix] Make slapd listen also on ipv6

src/app.py
The `env` arg of the  `_call_config_script` function is overwritten, which contains the value to update during the "config panel apply". The app config is not updated.
Reapply something similar (but simpler) to https://github.com/YunoHost/yunohost/commit/96494cbee478ad687a2a67cad57e6b60a9447037
...
...
=> appconfig panel: new values were replaced by default values

helpers/helpers.v1.d/apt, helpers/helpers.v2.1.d/apt
in the control file to manage dependencies, there are double commas which make `dpkg-deb --build` crash silently because we run it in a subshell
example: https://ci-apps-dev.yunohost.org/ci/job/17894
...
Tested with helpvers v1
...
=> Fix install from equivs

src/app.py
Attempts to solve:
Fixes https://github.com/YunoHost/issues/issues/684
Fixes https://github.com/YunoHost/issues/issues/2016
It basically adds an exception for app conflicts if an app is installed at the root of a domain and another app tries to add a `./well-known/foo` subpath, but keeps returning a conflict if any two apps try to register the same `./well-known/foo` subpath.
Finished? Untested.
...
=> [enh] exclude .well-known subpaths from conflict checks

conf/ssh/sshd_config
Via sftp when you load a file or a directory, the content uploaded has no group permission even if the parent dir has.
It's a bit shame if you want to share an app dir to a user like in this documentation PR https://github.com/YunoHost/doc/pull/1836/files
Set an appropriate umask.
Alternatively, we could define umask by user through gcos in ldap... But it's more difficult.
Currently in testing on a true server with a true person. I wait a bit if this person get an issue.
...
=> [enh] Tweak umask for SFTP

src/user.py
The `post_app_addaccess` and `post_app_removeaccess` are not triggered when adding or removing a user to / from a group with the commands `yunohost user group add` and `yunohost user group remove`
Add a `hook_callback` call in the appropriate function. 
To be tested
- install a app with `post_app_addaccess` and `post_app_removeaccess` hooks
- add a user into a group
- => `post_app_addaccess` hook is called
- remove a user from a group
- => `post_app_removeaccess` hook is called
This PR is related to https://github.com/YunoHost/issues/issues/2213
=> trigger hooks when adding or removing user into group

helpers/helpers.v2.1.d/sources
> Setting up source files...
> WARN: realpath: /var/cache/yunohost/app_tmp_work_dirs/app_ww4ms3a9/patches/main: Aucun fichier ou dossier de ce type
when installing feber, which uses helpers 2.1: https://github.com/YunoHost-Apps/feber_ynh/blob/master/manifest.toml#L23
and doesn't have a `patches` directory
check if the `patches` directory exists before trying to get its realpath
done
...
=> 2.1 helpers: check if patches dir exists before getting realpath

helpers/helpers.v2.1.d/utils
These two helpers are widely used and have been part of experimental helpers for over 5 years. Maybe it's time to include them so scripts don't have to include their own custom version?
Case in point, i found 3 different versions of `ynh_add_swap` used across apps:
- one that does `chattr +C`, which will not work on most filesystems like ext4
- one that checks for LXC (or LXD?) virtualization and skips the swap setup (because it would fail)
- one that does neither
In this PR, ynh_add_swap checks that no virtualization is used at all otherwise it just skips the setup.
=> Add ynh_add_swap and ynh_smart_mktemp to official helpers

helpers/helpers.v2.1.d/backup
Helper 2.1 `ynh_restore_everything` don't work.
We end with an error like this:
```
Exception: Original path for "etc/nginx/conf.d/ynh-11-app-c.dev.tille.ch.d/sogo.conf" not found
```
The reason of this is that in the helper we get the second collum on of the CSV and we need to take the first on which have the backup source path (so the target restore path)
Tested and if fixed the issue
Ready
Test an app which use this helper with the fix and without and see the difference.
=> Fix ynh_restore_everything

src/utils/system.py
...
...
...
Tested on my side:
```
yunohost: 
repo: unstable
version: 12.0.3+202408311800
yunohost-admin: 
repo: unstable
version: 12.0.2+202408311815
yunohost-portal: 
repo: testing
version: 12.0.2
moulinette: 
repo: unstable
version: 12.0.2+202408311815
ssowat: 
repo: unstable
version: 12.0.1+202407262030
```
=> Add yunohost-portal to the --version output

share/actionsmap.yml, src/user.py
https://forum.yunohost.org/t/mail-alias-for-all-users/29781
[This line](https://github.com/YunoHost/yunohost/blob/6aa9d0537284406c91687b63403789a339741776/src/user.py#L1145) mentions that the edition of `all_users` group can be allowed/forced with `--force`, but neither the actions maps nor the `user_group_add_mailalias` or `user_group_remove_mailalias` support that flag.
...
Ready
```
yunohost user group add-mailalias all_users everyone@domain.tld
yunohost user group add-mailalias all_users everyone@domain.tld --force
```
=> Allow to force-adding aliases for special groups

src/backup.py
```
Failed to format translated string 'backup_applying_method_custom': 'Calling the custom backup method '{method}'…' with arguments '()' and '{}, raising error: KeyError('method') (don't panic this is just a warning)
/var/www/borg/logging.conf') ... falling back to regular copy.
Failed to format translated string 'backup_method_custom_finished': 'Custom backup method '{method}' finished' with arguments '()' and '{}, raising error: KeyError('method') (don't panic this is just a warning)
```
during Borg backup.
Supply missing named parameters for format, they'll be ignored for 'copy' and 'tar' methods.
Tested once on live system, worked.
1. Run custom backup (restic, borg)
2. Sift through logs - there should be no i18n errors.
example output:
```
Calling the custom backup method …
```
=> Fixed string formatting for custom methods.

helpers/helpers.v2.1.d/backup
`ynh_backup "$data_dir"` runs (is elgible) during pre-upgrade backup.
Properly match paths?
we may consider extracting `is_in_dir` from `_ynh_apply_default_permissions` as it contains this logic already.
1. Install `filebrowser_ynh` (an app confirmed to use `data_dir` and helpers v2.1, use different app if needed)
2. Upload any file
3.a `yunohost app upgrade filebrowser -F`
Created backup should not include `data_dir`.
3b. Create backup (from cli, webadmin, whatever), choose `filebrowser`
Created backup should include `data_dir`.
=> apps/helpers2.1: Properly detect 'is_data' (data dir or log folder) when calling ynh_backup

src/utils/resources.py
it generates documentation with only \ instead of two \ in here
```
autoupdate.asset.amd64 = ".*\.amd64.tar.gz"
autoupdate.asset.i386 = ".*\.386.tar.gz"
autoupdate.asset.armhf = ".*\.arm.tar.gz"
```
add \\ in the script to get a second \ in the documentation.
...
...
=> doc: in autoupgrade doc, double slash ends up as single slash in the doc, but double slash is really needed, so further escape the slashes

src/utils/configpanel.py
if a config panel bind key was not found in the app config file, the showed error is misleading: `Config panel question '{option['id']}' should be initialized with a value during install or upgrade.`
i would like to put a different message to differenciate the two errors, but the script logic doesn't seem to allow it, so i just put a small hint at the end
done
put a key bind that is NOT in the config file, so the script will not found it
=> configpanel: error adjust to hint if the bind key wasn't found

conf/nginx/tls_passthrough.conf, hooks/conf_regen/15-nginx, locales/en.json, share/config_global.toml
That allows a domain to be configured as well as an IP as destination for TLS passthourgh.
Also we now can (and need to) specify a destination port.
=> TLS passthrough: Allow a destination domain to be configured

src/tools.py
```
Traceback (most recent call last):                                                                                            
File "/usr/lib/python3/dist-packages/yunohost/tools.py", line 588, in tools_shell                                           
from IPython import embed                                                                                                 
ModuleNotFoundError: No module named 'IPython'
```
...
Ready
...
=> [fix] Bad catch IPython missing

src/backup.py
When we restore an archive, hooks are not restored !
NB: this bad situation is fixed after the next app upgrade (each app upgrade redeploy app hooks).
Restored it from the hooks listed in the package.
That means manual user change on apps hooks directly inside /etc/yunohost/hooks.d/ should disappear... Those disappears also after an upgrade...
Untested
```
yunohost app install forgejo
yunohost backup create -n forgejo --apps forgejo
yunohost app remove forgejo
tree /etc/yunohost/hooks.d
yunohost restore -n forgejo
tree /etc/yunohost/hooks.d
```
=> [fix] Redeploy hooks after restore

src/authenticators/ldap_ynhuser.py
https://github.com/YunoHost/doc/pull/2509
https://github.com/YunoHost/SSOwat/pull/231
https://github.com/YunoHost/package_linter/pull/164
https://github.com/YunoHost/issues/issues/2445
Add in the HTTP header some HEADER with the information with the authenticated user.
We have 3 case of usage of the SSO (maybe more ??)
1. The application only use the Authentication header with the user information (not the password), trust this information and automatically authenticate the user. In some case the header could be also the user email, we have this case with seafile.
2. The application, use the auth basic information, with the user and password and if the credential are OK, the user is authenticated. This is the case by example for SOGo, which use also the password to transmit the credential …
=> #2445: Pass email, username and fullname as header for ssowat

src/app.py
Non-webapps that do not have a `main` permission thus get no label. That's expected, there is no need to display it as a warning that can be reiterated a lot of times during some operations.
(e.g. incus, wireguard_client)
Lower the warning to debug level.
Ready
...
=> Lower logging about failure to retrieve app label

src/certificate.py
Cryptpad's sandbox domain can either be:
- `sandbox-domain.example`
- `sandbox.domain.example`
First case cannot be included in the SAN list of the hook.
Detect if the hook lists a full domain (if it has a dot), and do not assume it is a subdomain of the app's domain
Ready
I'm preparing a PR for Cryptpad to test this.
=> Support domains in cert_alternate_names hook

src/migrations/0030_rebuild_python_venv_in_bookworm.py
see https://forum.yunohost.org/t/yunohost-12-0-beta-bookworm/30496/84
the migration process kill that 2 apps as they use a custom python version
add them to the ignore list
...
...
=> Migration don't rebuilt venv for homeassistant and immich

src/utils/dns.py
cf. https://www.icann.org/en/board-activities-and-meetings/materials/approved-resolutions-special-meeting-of-the-icann-board-29-07-2024-en#section2.a
=> 'internal' is a reserved TLD for private networks

src/app.py, src/domain.py, src/settings.py, src/utils/configpanel.py, src/utils/form.py
Update some config panel + form typing for upcoming migration to pydantic v2
- use `|` instead of `Union`
- use `ClassVar` for class private attributes
- repeat default values for Options attribute (required in pydantic-v2)
=> typing: pre pydantic v2

src/app.py
PR #1647 added the ability to install `/.well-known/` entries on domains, that already have an app on `/`. However, if you try this the other way around (install app on `/` after `/.well-known/` entry) you get an error. This also breaks updating for the app installed on `/`.
Update the conflict detection
Works on my machine™
Install an app that supports putting its `/.well-known/` entries on a separate domain (I used `conduit`) and then install another app on the root of the same domain.
=> [fix] Allow apps to be installed on / if another app is using /.well-known/

helpers/helpers.v2.1.d/mysql
During an upgrade of wordpress:
> WARNING - /usr/share/yunohost/helpers.v2.1.d/mysql: ligne 36: character_set : variable sans liaison
I think there is a typo, replace `character_set` by `default_character_set` should fix the issue
...
...
=> fix unset variable in helper 2.1 mysql

helpers/helpers.v1.d/getopts, helpers/helpers.v1.d/setting, helpers/helpers.v2.1.d/utils, src/app.py
YunoHost/issues#2467 - apps with helpers 2.1 don't get PHP sourced correctly in shell
Use helpers 2.1 for spawning the shell
WFM
1. Install `castopod` or `lychee`
2. `yunohost app shell castopod`
3. `php --version` should NOT be 7.4
=> Fix PHP sourcing in helpers 2.1 + don't flood bash salad when opening "yunohost app shell"

helpers/helpers.v2.1.d/fail2ban
The fail2ban logpath isn't always `/var/log/$app/*.log`. It could be /var/log/syslog.
Also, it overwrites the possibly already existing permission (that could allow the group to write in $logdir).
This PR reduces this behaviour to logdir _**creation**_.
=> Fix fail2ban helper for non-/var/log/$app paths

src/backup.py, src/tools.py
Moulinette.prompt may raise NotImplementedError exception, but not NotImplemented, which is not an exception
prompt raise:
- [`NotEmplementedError`](https://github.com/YunoHost/moulinette/blob/61610ce976fc4fbdd77d5d988d5269c18c4c3f3b/moulinette/interfaces/api.py#L553)
- [`MoulinetteError`](https://github.com/YunoHost/moulinette/blob/61610ce976fc4fbdd77d5d988d5269c18c4c3f3b/moulinette/interfaces/cli.py#L569)
- [`MoulinetteValidationError`](https://github.com/YunoHost/moulinette/blob/61610ce976fc4fbdd77d5d988d5269c18c4c3f3b/moulinette/interfaces/cli.py#L636)
...
...
...
=> Confusion between `NotImplemented` and `NotImplementedError`

src/tests/test_user-group.py, src/user.py
One can remove the last user from the admins group and loose access to the server.
...
...
...
=> Prevent to remove the last user from admins

src/utils/resources.py
In manifest.toml, using regexp in `<permission>.url` [is implemented and works](https://github.com/YunoHost/yunohost/blob/54e5aaefa308c542d85d59bc443e858a45937731/src/permission.py#L387-L390), but [is a secret](https://doc.yunohost.org/en/packaging_apps_resources#properties-for-each-perm-), from documentation standpoint !
Document it :)
Ready
=> Document the possibility of using regex in <permission>.url property

src/app.py
On the chat: 
> About RAM requirement for installation. For forgejo [manifest](https://jo.trax.im/fork/forgejo_ynh/src/branch/master/manifest.toml) I have (not my doing; this has been like this for at least months):
> 
> ```
> [integration]
> disk = "150M"
> ram.build = "50M"
> ram.runtime = "2G"
> ```
> 
> Install proceeds fine, but "app upgrade" complains "This app requires 2G RAM to install/upgrade but only 716.0M is available..."
> 
> (Using Yunohost 11.2.30)
> 
> That seems to be a wrong warning. Do I misunderstand it? Couldn't find an open issue with search for "requires RAM".
Consider the app is already running, before upgrade operation, so no need to ask for available ram in more. 
Untested
...
=> [fix] Wrong warning runtime ram missing during upgrade

.gitlab/ci/install.gitlab-ci.yml
This is required when our pull requests add new dependencies that were not installed in preinstall incus images
=> On CI tests, run apt update before install

share/actionsmap.yml, src/app.py
Some apps require 12.x even though they should work on 11.x.
The idea is to merge this to `dev` then backport to `bullseye`.
Allow users to ignore required YNH version, even if it may break.
To be tested.
Install Nextcloud 30.x on YNH 11.x
=> Allow ignoring of YNH version.

debian/control, doc/generate_bash_completion.py, share/actionsmap.yml, src/disks.py, src/storage.py
Rel: YunoHost/issues#1823.
Add API for getting infos on hard drives.
=> Storage managment API: disks infos

src/authenticators/ldap_ynhuser.py
https://github.com/YunoHost-Apps/synapse_ynh/issues/497
After more investigation it seem to be related to the `samesite` settings of the `yunohost.portal` cookie.
So I did 2 test one with yunohost 11 and one with yunohost 12. With this process:
- Install synapse
- Install element (on the yunohost instance)
- Login on the SSO
- Try to login on matrix from the local element instance
- Pass on Yunohost 11
- Pass on Yunohost 12
- Try to login on matrix from https://app.element.io (which is a completely other domain)
- Pass on Yunohost 11
- Fail on Yunohost 12
Now try to do this small fix on yunohost 12 and see that it solve the issue. 
Note that there was already a discussion about this some year ago here: https://github.com/YunoHost/SSOwat/pull/103
Use the same settings than on bullseye for …
=> Use samesite lax for portal cookies

.gitlab-ci.yml
…t anymore.
See https://about.gitlab.com/blog/2023/08/15/removing-tags-from-small-saas-runner-on-linux/
...
...
...
...
=> Remove the tag docker from the code_quality workflow. It doesn't exist anymore.

helpers/helpers.v2.1.d/utils
See https://github.com/systemd/systemd/issues/14723, it looks like it doesn't fix the issue
=> yunohost app shell: fix env loading by remove 'ignore_errors=yes' from systemctl show output in some cases

helpers/helpers.v2.1.d/permission
Somes app are broken by #1917. cf https://github.com/YunoHost-Apps/synapse_ynh/issues/518
Do the same cleanup than on helper v1
Done.
To be honest, I didn't test this at all but as it's the same change than on helper v1 it should be ok.
=> Cleanup label parameters in helpers v2.1

src/firewall.py
"Both" is not accepted for the cmd:
`yunohost firewall allow Both 1234"
```
❯ sudo yunohost firewall allow Both 1234
File "/usr/bin/yunohost", line 108, in <module>
main()
File "/usr/bin/yunohost", line 97, in main
yunohost.cli(
File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 41, in cli
ret = moulinette.cli(
^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 140, in cli
).run(args, output_as=output_as, timeout=timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 521, in run
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Fix "Both" protocol for firewall allow/disallow

src/firewall.py
...
...
Tested on my prod lul
...
=> Add check_status on UPnP device, rework how to detect if there is an UPnP device

helpers/helpers.v1.d/nodejs, helpers/helpers.v1.d/ruby, helpers/helpers.v2.1.d/go, helpers/helpers.v2.1.d/nodejs, helpers/helpers.v2.1.d/ruby, helpers/helpers.v2.1.d/utils, src/tests/test_app_resources.py, src/utils/resources.py, tests/test_helpers.sh, tests/test_helpers.v2.1.d/ynhtest_nodejs_ruby_go_composer.sh
Redundant code in app packages, nodejs / ruby / go / composer should be managed declaratively like apt deps etc
Implement them as resource
Kinda yolo, not complete
The code is kind of a mess because it needs to call bash commands with proper env vars x_x
=> Helpers / app resources: simplify helpers and implement new resources for nodejs/ruby/go/composer

helpers/helpers.v2.1.d/apt
I had an error because `apt-mark auto` was called without any argument.
We want a non-empty array here
...
...
=> fix ynh_apt_install_dependencies_from_extra_repository

helpers/helpers.v2.1.d/0-utils
Similar issue to here: https://github.com/systemd/systemd/issues/14723
I got a case where `yunohost app shell` could not work. In fact, `systemctl show [...] -p EnvironmentFiles --value` returned `/path/to/somefile.env (ignore_error=no)`
I just strip any string matching ` (ignore_error=...)`, assuming that it can only be followed by words and digits.
Ready
`yunohost app shell <app>`
I can provide a more detailed example of how to reproduce if you want to (I am developing a package for which I got the issue).
=> Fix `yunohost app shell` when `systemctl show` outputs ` (ignore_error=no)`

src/utils/form.py
prompt might be called with words = None instead of an empty list.
```
Unhandled exception in event loop:
File "/usr/lib/python3/dist-packages/prompt_toolkit/buffer.py", line 1939, in new_coroutine
await coroutine(*a, **kw)
File "/usr/lib/python3/dist-packages/prompt_toolkit/eventloop/async_context_manager.py", line 79, in __aexit__
await self.gen.athrow(typ, value, traceback)
File "/usr/lib/python3/dist-packages/prompt_toolkit/eventloop/async_generator.py", line 42, in aclosing
yield thing
File "/usr/lib/python3/dist-packages/prompt_toolkit/buffer.py", line 1763, in async_completer
async for completion in async_generator:
File "/usr/lib/python3/dist-packages/prompt_toolkit/completion/base.py", line 326, in get_completions_async
async for completion in completer.get_completions_async( …
```
=> Fix form prompt when option is a "choice" but with no options

helpers/helpers.v1.d/config, helpers/helpers.v2.1.d/config
`ynh_app_config_get_one $short_setting $type $bind` fails when `$type = "text"` and `$bind = "settings"` trigering a config panel read error.  
This is due to current "subhelper" `_ynh_app_config_get_one` calling `ynh-app-setting-get` with the wrong syntax. It is now updated as per the syntax described both for [helpers v2.1](https://doc.yunohost.org/en/packaging_apps_helpers_v2.1#ynh-app-setting-get) and [helpers v1](https://github.com/YunoHost/yunohost/blob/6830ebc6cea29a2d713fab14f8cbdc02b134cde8/helpers/helpers.v1.d/setting#L23)
Tested successfully with both CLI (`yunohost app config get marl --full --debug`) & webUI (displaying config panel) using testing branch of `marl_ynh` in which `archives_paths` config option falls into the problematic case.
=> Fix helper `ynh_app_config_get_one`

helpers/helpers.v2.1.d/backup
Issue [2512](https://github.com/YunoHost/issues/issues/2512)
Add parameter substitution to BACKUP_CORE_ONLY
...
...
=> Fix BACKUP_CORE_ONLY not set

src/app.py
Some apps, like monitorix (cf. https://github.com/YunoHost-Apps/monitorix_ynh/pull/81) need a hook for app pre upgrade
Add the hook
Ready
...
=> Add pre_app_upgrade hook

src/app.py
I am trying to add a button in the config panel for Silverbullet ([commit](https://github.com/YunoHost-Apps/silverbullet_ynh/commit/50b3d9ebcb66d055c20e21d906c58261179ffff8)).
When I click on the button, I get the below error:
```
File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 430, in process
ret = self.actionsmap.process(arguments, timeout=30, route=_route)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 579, in process
^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/yunohost/app.py", line 1964, in app_action_run
operation_logger = OperationLogger("app_action_run", app)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Fix app_action_run operation logger instanciation

share/config_domain.toml, src/portal.py
Not having other domains' apps is a special use case, and newbies will just want to see all apps.
It's more intuitive to set it to True
=> Change default value of show_other_domains_apps to True

src/tools.py
The `logger.warn` is deprecated so it throws annoying deprecation warnings:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
Migrates to `logger.warning`. Also fixes a few typos along the way.
=> Resolve logger warnings

conf/dnsmasq/plain/resolv.dnsmasq.conf
A lot of our dns resolvers list doesn't answer anymore (several german resolvers). Sometimes dnsmasq doesn't answer anymore...
Remove them
Better solution: consider configuring an internal resolver with unbound to avoid this kind of mess
Ready
...
=> [fix] Remove unavailable dns resolvers

helpers/helpers.v2.1.d/0-utils, helpers/helpers.v2.1.d/apt
"--message" comes with the message for some helpers2.1 (e.g. https://ci-apps-dev.yunohost.org/ci/job/12302)
Remove them as they are not needed anymore.
Ready
...
=> remove --message in helpers2.1

conf/nginx/server.tpl.conf
Closes https://github.com/YunoHost/issues/issues/2593
Ready to merge
...
=> fix(nginx): remove deprecated OCSP

helpers/helpers.v2.1.d/templating, src/hook.py, src/utils/jinja_filters.py
Iterating over complex data in template is a pain, because ne need delimiter and it's not strong solution
By example, this part of code could be simplified with jinja filters: https://github.com/YunoHost-Apps/forgejo_ynh/blob/75750de715f852989780ddb95f86d43410cc8253/scripts/login_source.sql#L34-L37
Use json, toml or yaml serialization and decode in template with filters
Tested locally and it seem working
Just made a file `test.j2` with: 
```
from json to yaml
{{ hellovar | from_json | to_yaml }}
from json to json
{{ hellovar | from_json | to_json }}
from json to toml
{{ hellovar | from_json | to_toml }}
from yaml to json
{{ hellovaryaml | from_yaml | to_json }}
from toml to json
{{ hellovartoml | from_toml | to_json }}
```
And then run `j2 test.j2 --filters …
=> Add jinja filter to load and dump json, yaml and toml

helpers/helpers.v2.1.d/utils
If one source the helpers with `set -u`, we have an error telling that `YNH_APP_ACTION` is empty.
In other part of the code, we ensure to test its value defaulting to an empty string. Let's also do that here.
Ready
Run `set -u` before sourcing the helpers:
```
root@ynh-dev:/ynh-dev# bash
root@ynh-dev:/ynh-dev# export YNH_HELPERS_VERSION=2.1
root@ynh-dev:/ynh-dev# set -eu
root@ynh-dev:/ynh-dev# source /usr/share/yunohost/helpers
bash: YNH_APP_ACTION: unbound variable
```
=> YNH_APP_ACTION is not guaranteed to be set

share/registrar_list.toml
Lexicon version is way to old
Adapt the registrar_list for the latest version of lexicon (based on https://dns-lexicon.github.io/dns-lexicon/configuration_reference.html)
Requires https://github.com/YunoHost/lexicon/pull/3
...
=> Update registrars list

debian/install, debian/rules, doc/generate_zsh_completion.py, doc/zsh_completion.j2, share/actionsmap.yml
There is no auto-completion suggestions for ZSH.
Follow up on PR #1034.
Add auto-completion to ZSH, by generating that completion file from `share/actionsmap.yml`
As `yunohost` needs to be called with `sudo`, completion may ask for password to autocomplete.
- updated PR #1034 to the latest commit
- tested all completions
Run the script with:
```
python3 doc/generate_zsh_completion.py
```
It will create a file `yunohost_zsh_completion` in the `doc` folder.
Move and rename the created file to `/usr/local/share/zsh/site-functions/_yunohost` (or `/usr/share/zsh/vendor-completions/_yunohost`, that is where yunohost installation will install it).
Restart zsh to test the completions.
=> Add a zsh completion file (automatically generated)
